### ISSUE TITLE
Tpetra: compilation error under CUDA 8.0.44

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1671]
@trilinos/tpetra 

Tpetra is failing to compile on one of MueLu's nightly builds on geminga that uses CUDA 8.0.44.  The error is
```
trilinos-test/OPENMPI_1.8.7_RELEASE_DEV_MueLu_KOKKOS_REFACTOR_CUDA_8.0.44/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp(1698): error: identifier "tfecfFuncName" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00003892_00000000-7_Tpetra_MultiVector_LONG_INT_LONG_SERIAL.cpp1.ii".
```

The dashboard is [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3083879).

In case it's helpful, the following modules are loaded:
```
module load sems-env
module load kokkos-env
module load sems-cmake/3.5.2
module load sems-gcc/5.3.0
module load sems-boost/1.58.0/base
module load sems-python/2.7.9
module load sems-zlib/1.2.8/base
module load kokkos-cuda/8.0.44
module load kokkos-nvcc_wrapper/1
module load kokkos-openmpi/1.8.7/cuda
module load sems-superlu/4.3
module load sems-hdf5/1.8.12/parallel
module load sems-netcdf/4.3.2/base
```

**Comment by jhux2** [comment]
The reason is that ```tfecfFuncName``` is only defined if HAVE_TPETRA_DEBUG is also defined.  The latter is not because this is a release build.

Adding the macro guard
```
#ifdef HAVE_TPETRA_DEBUG
#endif 
```
around the call to ```TEUCHOS_TEST_FOR_EXCEPTION_CLASS_FUNC``` on line 1698 fixes the issue.

**Comment by aprokop** [comment]
@jhux2 Fixed in #1662 I believe.

**Comment by jhux2** [comment]
Yes, @aprokop beat me to the punch and fixed this in develop.  However, there's a build warning in release mode

```
Tpetra_MultiVector_def.hpp(1410): warning: variable "tfecfFuncName" was declared but never referenced
```

`TEUCHOS_TEST_FOR_EXCEPTION_CLASS_FUNC` is only ever used in this method when `HAVE_TPETRA_DEBUG` is defined, so I believe my suggested patch is still relevant.

**Comment by jhux2** [comment]
Basically a duplicate of #1662.
