### PR TITLE
fix(Intrepid2): implicit by-copy capture of this is deprecated warnings

### PR DESCRIPTION
**Pull request by maartenarnst**
@mperego @CamelliaDPG 

This PR fixes "implicit by-copy capture of this is deprecated" warnings when compiling `Intrepid2` after:
- https://github.com/trilinos/Trilinos/pull/13437

The PR Trilinos#13437 uses lambdas that capture class variables, but the implicit capture of `this` is deprecated. When we compile with `nvcc` with `cuda` 12.6 and `gcc` 13.3 as the host compiler and C++20 standard, we get compilation errors. 

This PR is a proposed solution with "capture with initializer".

### CODE REVIEW

**Review by mperego — APPROVED** [review]
This looks good to me, thanks for doing this.

We now require the commits to be signed off. In your case I think that doing
`git commit -s --amend`
and then push should be enough

**Comment by maartenarnst** [comment]
Hi @mperego. I have just rebased, signed and pushed again. Hopefully it will work now :)

**Comment by mperego** [comment]
Hi @maartenarnst, the commit message should contain
`Signed-off-by: Author Name <authoremail@example.com>`

https://github.com/trilinos/Trilinos/pull/13698/checks?check_run_id=35079608734

**Comment by sebrowne** [comment]
> @trilinos/framework Is this an issue with AT2 or do we need to add @maartenarnst to some group?

He will need to have somebody from Sandia re-run the workflow.  I believe the 'Developers' part of that message is inaccurate.  I just clicked re-run and it is running now.
