### PR TITLE
tacho: fix unused variable triggering -Werror

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/shylu @iyamazaki 

## Motivation

Fix `-Werror=unused-variable` breaking PR_gcc-openmpi-openmp builds, crept in with #13318 and encountered in PRs #13334 and https://github.com/trilinos/Trilinos/pull/13332

```
https://github.com/trilinos/Trilinos//blob/d8badb3e29a5693d5ec638d02da83d32d261cee8/workspace/PR_gcc-openmpi-openmp/Trilinos/packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp#L2059 :17: error: unused variable 's0' [-Werror=unused-variable]
           auto &s0 = _h_supernodes(_h_level_sids(pbeg));
```

The compilation errors likely contributed to `TrilinosInstallTests_doInstall` test failures in the `rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables` jobs with output:

```
...
CMake Error at /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/src/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/src/libtacho.a":
  No such file or directory.
Call Stack (most recent call first):
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/cmake_install.cmake:47 (include)
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/cmake_install.cmake:52 (include)
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/cmake_install.cmake:277 (include)

```

## Related Issues

* Blocks #13334 and https://github.com/trilinos/Trilinos/pull/13332

### CODE REVIEW

**Comment by ndellingwood** [comment]
@iyamazaki can you review + approve? I think this is the culprit you ran into with https://github.com/trilinos/Trilinos/pull/13332

**Review by iyamazaki — APPROVED** [review]
Thank you for the fix, @ndellingwood.

**Comment by ndellingwood** [comment]
@trilinos/framework @achauphan @sebrowne  I was hoping this PR would resolve issues with the [rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=1781633&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and) CI job in CI, but I'm still seeing the following problems that are blocking a couple other open PRs, can you help with some guidance?

* cdash reports 1 compilation error, but nothing is showing when clicking on the link: https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1781657

* TrilinosInstallTests_doInstall is still failing with the following output:
```
CMake Error at /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/src/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/src/libtacho.a":
  No such file or directory.
Call Stack (most recent call first):
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/cmake_install.cmake:47 (include)
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/cmake_install.cmake:52 (include)
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/cmake_install.cmake:272 (include)
```

**Review by iyamazaki — DISMISSED** [review]

**Comment by iyamazaki** [comment]
I am not sure how Amesos2 issue affect Tacho building...

**Comment by jhux2** [comment]
@ndellingwood This is one error:
```/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp:2057:30: error: unused variable 'pbeg' [-Werror=unused-variable]
```

and this should fix it:
```

**Comment by ndellingwood** [comment]
@iyamazaki the amesos2 push was just a wild guess based on a -Werror I ran into with https://github.com/trilinos/Trilinos/pull/13334 , the compilation errors aren't showing on cdash so it's hard to know what else needs fixing

@jhux2 thanks, I'll include that change

**Comment by jhux2** [comment]
@ndellingwood My reproducer for the failing build completed successfully after making the one change I mentioned above.

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by achauphan** [comment]
@ndellingwood I've been looking through the CI logs for that gcc-openmpi-openmp build in this PR and the other PRs you've mentioned and I am still not entirely sure why those errors aren't displaying at all in CDash. It mentions 1 build error for NOX, but when looking into its subproject build, https://trilinos-cdash.sandia.gov/build/1781657, there appears to again be no errors...

**Comment by lucbv** [comment]
Looks like AT2 is running twice, once as `(pull_request)` and once as `(pull_request_review)`, this looks like an unfortunate duplication that might lead to large resources over-consumption especially when considering that the old auto-tester is also running. @trilinos/framework can you have a look to optimize the use of resources a bit?

**Comment by ndellingwood** [comment]
@achauphan thanks for checking through the logs and confirming, it is an odd issue. Hopefully that last commit resolves the issues, I have a separate reproducer build in progress in case anything else occurs

**Comment by jhux2** [comment]
@ndellingwood My PR reproducer build was clean with the last set of commits.
