### ISSUE TITLE
STK::SIMD AVX512 Support Does Not Work on Sky Lake Xeon with GCC 7.2.0

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#2050]
GCC 7.2.0 has initial support for AVX512 instruction generation but does not appear to have all of the intrinsic functions within its header files. When compiling for Sky Lake Xeon (which has AVX512F), this causes compilation failures.

Is there a way to disable the STK::SIMD from using the AVX512 for now so we can get the rest of the code to use automatic vectorization?

@trilinos/stk 
@srajama1 

```
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp: In function ‘stk::simd::Bool stk::simd::operator<(const stk::simd::Double&, const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:91:21: error: ‘_mm512_cmplt_pd_mask’ was not declared in this scope
   return simd::Bool(_mm512_cmplt_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:91:21: note: suggested alternative: ‘_mm512_cmp_pd_mask’
   return simd::Bool(_mm512_cmplt_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~
                     _mm512_cmp_pd_mask
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp: In function ‘stk::simd::Bool stk::simd::operator<=(const stk::simd::Double&, const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:95:21: error: ‘_mm512_cmple_pd_mask’ was not declared in this scope
   return simd::Bool(_mm512_cmple_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:95:21: note: suggested alternative: ‘_mm512_cmp_pd_mask’
   return simd::Bool(_mm512_cmple_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~
                     _mm512_cmp_pd_mask
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp: In function ‘stk::simd::Bool stk::simd::operator>(const stk::simd::Double&, const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:99:21: error: ‘_mm512_cmplt_pd_mask’ was not declared in this scope
   return simd::Bool(_mm512_cmplt_pd_mask(y._data, x._data));
                     ^~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:99:21: note: suggested alternative: ‘_mm512_cmp_pd_mask’
   return simd::Bool(_mm512_cmplt_pd_mask(y._data, x._data));
                     ^~~~~~~~~~~~~~~~~~~~
                     _mm512_cmp_pd_mask
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp: In function ‘stk::simd::Bool stk::simd::operator>=(const stk::simd::Double&, const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:103:21: error: ‘_mm512_cmple_pd_mask’ was not declared in this scope
   return simd::Bool(_mm512_cmple_pd_mask(y._data, x._data));
                     ^~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:103:21: note: suggested alternative: ‘_mm512_cmp_pd_mask’
   return simd::Bool(_mm512_cmple_pd_mask(y._data, x._data));
                     ^~~~~~~~~~~~~~~~~~~~
                     _mm512_cmp_pd_mask
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp: In function ‘stk::simd::Bool stk::simd::operator==(const stk::simd::Double&, const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:107:21: error: ‘_mm512_cmpeq_pd_mask’ was not declared in this scope
   return simd::Bool(_mm512_cmpeq_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:107:21: note: suggested alternative: ‘_mm512_cmp_pd_mask’
   return simd::Bool(_mm512_cmpeq_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~
                     _mm512_cmp_pd_mask
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp: In function ‘stk::simd::Bool stk::simd::operator!=(const stk::simd::Double&, const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:111:21: error: ‘_mm512_cmpneq_pd_mask’ was not declared in this scope
   return simd::Bool(_mm512_cmpneq_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleOperators.hpp:111:21: note: suggested alternative: ‘_mm512_cmpneq_epi8_mask’
   return simd::Bool(_mm512_cmpneq_pd_mask(x._data, y._data));
                     ^~~~~~~~~~~~~~~~~~~~~
                     _mm512_cmpneq_epi8_mask
In file included from /ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/Avx512.hpp:27:0,
                 from /ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/Simd.hpp:12,
                 from /ascldap/users/sdhammo/git/nalucfd-github-repo/include/SimdInterface.h:18,
                 from /ascldap/users/sdhammo/git/nalucfd-github-repo/include/master_element/MasterElement.h:17,
                 from /ascldap/users/sdhammo/git/nalucfd-github-repo/src/ActuatorLinePointDrag.C:17:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp: In function ‘stk::simd::Double stk::math::cbrt(const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp:53:23: error: ‘_mm512_cbrt_pd’ was not declared in this scope
   return simd::Double(_mm512_cbrt_pd(x._data));
                       ^~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp:53:23: note: suggested alternative: ‘_mm512_sqrt_pd’
   return simd::Double(_mm512_cbrt_pd(x._data));
                       ^~~~~~~~~~~~~~
                       _mm512_sqrt_pd
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp: In function ‘stk::simd::Double stk::math::log(const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp:57:23: error: ‘_mm512_log_pd’ was not declared in this scope
   return simd::Double(_mm512_log_pd(x._data));
                       ^~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp:57:23: note: suggested alternative: ‘_mm512_or_pd’
   return simd::Double(_mm512_log_pd(x._data));
                       ^~~~~~~~~~~~~
                       _mm512_or_pd
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp: In function ‘stk::simd::Double stk::math::log10(const stk::simd::Double&)’:
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp:61:23: error: ‘_mm512_log10_pd’ was not declared in this scope
   return simd::Double(_mm512_log10_pd(x._data));
                       ^~~~~~~~~~~~~~~
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp:61:23: note: suggested alternative: ‘_mm512_loadu_pd’
   return simd::Double(_mm512_log10_pd(x._data));
                       ^~~~~~~~~~~~~~~
                       _mm512_loadu_pd
/ascldap/users/sdhammo/trilinos/20171203/openmpi/2.1.2/gcc/7.2.0/include/stk_simd/avx512/./Avx512DoubleMath.hpp: In function ‘stk::simd::Double stk::math::exp(const stk::simd::Double&)’:
```

**Comment by mhoemmen** [comment]
@mrtupek would know!  I think we can add a work-around macro.

**Comment by nmhamster** [comment]
@mhoemmen @mrtupek @trilinos/stk - for now I have added this to my CMake config and it seems to be working `-DCMAKE_CXX_FLAGS:STRING="-DUSE_STK_SIMD_NONE" `

**Comment by spdomin** [comment]
I thought that by default SIMD is inactive and requires:

-DTrilinos_ENABLE_STKSimd:BOOL=ON \

@alanw0 would probably know. There are some cases I would like to disable SIMD. In the last, omission of the above supports this use case.

**Comment by spdomin** [comment]
With all of the STK_SIMD work, could @alanw0 or @mrtupek comment on what is now the fully supported platforms? For example, is AMD covered now?

**Comment by alanw0** [comment]
In a recent sprint review we showed a slide of which platforms/instruction-sets are known-to-work, known-not-to-work and not-known. I'll dig up that slide and send it to you.

**Comment by alanw0** [comment]
![stk_simd_support](https://user-images.githubusercontent.com/18755013/116903041-202da200-abf9-11eb-8b0a-ad335455ca4d.JPG)
(Trying to add an image showing stk-simd current platform support. Not sure if that's possible. If it doesn't show up, get further support by emailing stk-ngpteam@sandia.gov.)
