### ISSUE TITLE
ROL:  ROL HIP compile

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#11401]
Greetings,

Recently I was trying to compile with HIP using rocm 5.3 and got the following error:

/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/ROL_TpetraMultiVector.hpp:83:23: error: reference to __host__ function 'apply' in __host__ __device__ function
        X_(i,j) = f_->apply(X_(i,j));
                      ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/HIP/Kokkos_HIP_Parallel_Range.hpp:81:5: note: called by 'exec_range<void>'
    m_functor(i);
    ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/HIP/Kokkos_HIP_Parallel_Range.hpp:102:22: note: called by 'operator()'
      this->template exec_range<WorkTag>(iwork);
                     ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/HIP/Kokkos_HIP_KernelLaunch.hpp:114:11: note: called by 'hip_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<ROL::TPMultiVector::unaryFunc<double>, Kokkos::RangePolicy<Kokkos::Experimental::HIP>, Kokkos::Experimental::HIP>, 1024U, 1U>'
  driver->operator()();
          ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/ROL_Elementwise_Function.hpp:59:16: note: 'apply' declared here
  virtual Real apply( const Real &x ) const = 0;

Is there a build option to get around this for ROL? I'm using the following cmake config:

export OMPI_CXX=hipcc
cmake -DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_CXX_STANDARD:STRING=17 \
-DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_OpenMP=OFF \
-DKokkos_ENABLE_HIP=ON \
-DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE=ON \
-DKokkos_ENABLE_DEPRECATED_CODE=OFF \
-DTrilinos_ENABLE_KokkosKernels=ON \
-DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
-DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
-DTrilinos_ENABLE_Amesos2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DTpetra_INST_HIP=ON \
-DXpetra_ENABLE_Kokkos_Refactor=ON \
-DMueLu_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DMueLu_ENABLE_TESTS=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF \
-DCMAKE_INSTALL_PREFIX=. \
..

Thanks for any help!

**Comment by cgcgcg** [comment]
@trilinos/rol

**Comment by dridzal** [comment]
@Adrian-Diaz : I don't think there is a build option to get around that, but I don't know much about HIP.  Is the issue that the apply() function can't be executed on the device?  It is likely that @gregvw or @mperego know more about this.

Having said that, ROL's elementwise operations that are at the core of the issue are *not* required by all ROL algorithms.  If the algorithm you use doesn't require ROL's elementwise operations, it may be possible to provide options to "turn them off," i.e., have a version of the ROL/Tpetra vector that only uses standard vector space operations.

**Comment by gregvw** [comment]
Sorry, I am not familiar with HIP,  but I agree with not using algorithms that require Elementwise until we can implement an alternative Elementwise approach.

**Comment by Adrian-Diaz** [comment]
So far it's been compiling with CUDA somehow, but that not unusual with some std functions that aren't flagged either I've noticed. Would anything break if the elementwise apply function was just flagged with KOKKOS_FUNCTION or KOKKOS_INLINE_FUNCTION?

**Comment by kpwelsh** [comment]
@dridzal 

I have an update on desired timelines on our end. We are planning deployment to an HPC using AMD GPUs. Would the ROL team be able to implement this fix by sometime next month?

**Comment by dridzal** [comment]
@kpwelsh :  I believe that is feasible.  @gregvw , can you provide a status update?
In addition to the developed capability (which is close to complete), we need to perform a code review and we need sufficient test coverage.  We can probably do some basic GPU testing with CUDA, but we may have to rely on the community to test with HIP.  I think the issues are not limited to HIP.

**Comment by gregvw** [comment]
@dridzal : I currently have a working generic mechanism to apply variadic elementwise functions to an arbitrary number of `ROL::Vectors` that does not use any virtual function calls. This has been implemented and pushed on the dev fork. Additionally, I have (outside of ROL) implemented a generic container that can hold either `const ROL::Vector<Real>* const` or `const Real* const` values (using an encapsulated `union` of all things). I have a  working test that can handle arbitrarily many scalar or Vector arguments (again without virtual calls) and am currently incorporating it into ROL. I also have my previous `ROL::KokkosVector` class that I am updating to use the same machinery. It might be time to fire a warning shot on that code review.
