### PR TITLE
Ifpack2: Fix #13118 and cleanup copy-pasted function

### LINKED ISSUE #13118: Ifpack2: Compilation errors in Ifpack2_Experimental_RBILUK_def.hpp with cuda/12.4 and c++20
## Bug Report
@trilinos/ifpack2 

### Description
Attempting a Cuda build with Trilinos using cuda/12.4 and c++20 support enabled failed to compile in ifpack2:
```
/home/ndellin/Trilinos/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp(366): error: function "Ifpack2::RILUK<MatrixType>::makeLocalFilter [with MatrixType=Tpetra::RowMatrix<double, int, longlong, Tpetra_KokkosCompat_KokkosCudaWrapperNode>]" (declared at line 598 of /home/ndellin/Trilinos/packages/ifpack2/src/Ifpack2_RILUK_decl.hpp) is inaccessible
    this->A_local_ = makeLocalFilter<MatrixType>(this->A_);
                     ^
          detected during instantiation of "void Ifpack2::Experimental::RBILUK<MatrixType>::initialize() [with MatrixType=Tpetra::BlockCrsMatrix<double, int, longlong, Tpetra_KokkosCompat_KokkosCudaWrapperNode>]" at line 58 of /home/ndellin/Trilinos/Build/SemsCuda1240_OpenMPI416-pristine/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_DOUBLE_INT_LONG_LONG_CUDA.cpp

/home/ndellin/Trilinos/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp(366): error: type name is not allowed
    this->A_local_ = makeLocalFilter<MatrixType>(this->A_);
                                     ^
          detected during instantiation of "void Ifpack2::Experimental::RBILUK<MatrixType>::initialize() [with MatrixType=Tpetra::BlockCrsMatrix<double, int, longlong, Tpetra_KokkosCompat_KokkosCudaWrapperNode>]" at line 58 of /home/ndellin/Trilinos/Build/SemsCuda1240_OpenMPI416-pristine/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_DOUBLE_INT_LONG_LONG_CUDA.cpp

/home/ndellin/Trilinos/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp(366): error: function "Ifpack2::RILUK<MatrixType>::makeLocalFilter [with MatrixType=Tpetra::RowMatrix<double, int, longlong, Tpetra_KokkosCompat_KokkosCudaWrapperNode>]" (declared at line 598 of /home/ndellin/Trilinos/packages/ifpack2/src/Ifpack2_RILUK_decl.hpp) is inaccessible
    this->A_local_ = makeLocalFilter<MatrixType>(this->A_);
                     ^
          detected during instantiation of "void Ifpack2::Experimental::RBILUK<MatrixType>::initialize() [with MatrixType=Tpetra::RowMatrix<double, int, longlong, Tpetra_KokkosCompat_KokkosCudaWrapperNode>]" at line 58 of /home/ndellin/Trilinos/Build/SemsCuda1240_OpenMPI416-pristine/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_DOUBLE_INT_LONG_LONG_CUDA.cpp
/home/ndellin/Trilinos/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp(366): error: type name is not allowed
    this->A_local_ = makeLocalFilter<MatrixType>(this->A_);
                                     ^
          detected during instantiation of "void Ifpack2::Experimental::RBILUK<MatrixType>::initialize() [with MatrixType=Tpetra::RowMatrix<double, int, longlong, Tpetra_KokkosCompat_KokkosCudaWrapperNode>]" at line 58 of /home/ndellin/Trilinos/Build/SemsCuda1240_OpenMPI416-pristine/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_DOUBLE_INT_LONG_LONG_CUDA.cpp
4 errors detected in the compilation of "/home/ndellin/Trilinos/Build/SemsCuda1240_OpenMPI416-pristine/packages/ifpack2/src/Ifpack2_Experimental_RBILUK_DOUBLE_INT_LONG_LONG_CUDA.cpp".
```

### Steps to Reproduce
1. SHA1: 8d8159e1d6fbe4c45c89c39c082e307bf78a4c43
2. Configure: (sems modules)
```bash

export TRILINOS_DIR=<your-path>
export KOKKOS_DIR=$TRILINOS_DIR/packages/kokkos

module load sems-gcc/13.2.0 sems-cuda/12.4.0 sems-openblas/0.3.10 sems-openmpi/4.1.6 sems-cmake sems-ninja

export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="20" \
 -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_CUDA=ON \
  -DTPL_ENABLE_BLAS:STRING=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:STRING=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
   -DLAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_CUSPARSE:BOOL=ON \
  -DTPL_ENABLE_CUBLAS:BOOL=ON \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_COMPLEX=ON \
 -DTrilinos_ENABLE_OpenMP=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
   -D Kokkos_ENABLE_TESTS=ON \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Belos=ON \
   -D Belos_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
  -DTrilinos_ENABLE_ShyLU_NodeTacho=OFF \
\
$TRILINOS_DIR
```

### PR DESCRIPTION
**Pull request by brian-kelley**
makeLocalFilter was copy-pasted verbatim from RILUK (private static member) to RBILUK_def (free function). #13118 was because this also caused ambiguous name lookup.

Instead, just make the function public static in RILUK so that it can replace all usages of the copy in RBILUK.

Verified the fix on ascicgpu

@trilinos/ifpack2

## Related Issues

* Closes #13118

### CODE REVIEW

**Comment by ndellingwood** [comment]
The ATS2/gcc10-openmpi416-EXPERIMENTAL, gcc830-serial-EXPERIMENTAL, and  cuda11-uvm-EXPERIMENTAL  jobs failed due to connectivity issues, e.g.:
```
    Error when uploading file: /home/Trilinos/build/Testing/20240619-1051/Update.xml
   Error message was: Failed to connect to sems-cdash-son.sandia.gov port 443 after 140356 ms: Couldn't connect to server
   Problems when submitting via HTTP
>>> Update submit: FAILED
>>> - The ERROR code is -1
```
