### PR TITLE
Kokkos promotion

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation

Snapshot Kokkos Ecosystem 4.4.0 to Trilinos

## Related Issues

* A modification to a stk ngp mesh test is included with sha 757c58ba8588b988df39149415549d406ecaef45, discussed in https://github.com/trilinos/Trilinos/issues/13328
@alanw0 @ldh4 - the sha should be easy to cherry-pick to the the stk repo, if that change is acceptable

## Testing

Various nightly testing jobs of release candidate, AT will handle the rest

### CODE REVIEW

**Comment by alanw0** [comment]
Looks good to me, we are incorporating the stk change into the sierra/stk repo.

**Review by alanw0 — APPROVED** [review]

**Comment by ndellingwood** [comment]
Re: the rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables job failure in TrilinosInstallTests_doInstall reporting:
```
...
CMake Error at /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/src/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/src/libtacho.a":
  No such file or directory.
Call Stack (most recent call first):
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/tacho/cmake_install.cmake:47 (include)
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/packages/shylu/shylu_node/cmake_install.cmake:52 (include)
  /scratch/trilinos/workspace/PR_gcc-openmpi-openmp/pull_request_test/cmake_install.cmake:277 (include)
```

This also occurred in https://github.com/trilinos/Trilinos/pull/13332 with unrelated changes. The job referenced above also did not post any compilation errors. @trilinos/framework @sebrowne can you help us understand the underlying issue?
There was a merge of changes to Tacho yesterday #13318 prior to this PR submission, but that Tacho PR ran through CI and any issues with that PR should have shown up in testing of that PR?

**Comment by ndellingwood** [comment]
Build errors are showing up for Tacho in the latest round of testing https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1778541 , those errors are due to `-Werror=unused-variable` but that should not be related to changes in this PR since Tacho was not modifed, sample error snip:
```
[workspace/PR_gcc-openmpi-openmp/Trilinos/packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp:2059](https://github.com/trilinos/Trilinos//blob/d8badb3e29a5693d5ec638d02da83d32d261cee8/workspace/PR_gcc-openmpi-openmp/Trilinos/packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp#L2059):17: error: unused variable 's0' [-Werror=unused-variable]
           auto &s0 = _h_supernodes(_h_level_sids(pbeg));
```

Maybe there was a change to the CI config flags after https://github.com/trilinos/Trilinos/pull/13318 was submitted and passed testing, and so the unused variables were not flagged in that PR?

**Comment by achauphan** [comment]
@ndellingwood yes new flags were introduced in #13308 and merged into develop late afternoon yesterday. #13318 passed its AutoTester run a day prior to the new flags being introduced, but got merged only yesterday :(

**Review by dalg24 — APPROVED** [review]

**Review by lucbv — APPROVED** [review]

**Comment by ndellingwood** [comment]
Rebased on top of develop with merge of https://github.com/trilinos/Trilinos/pull/13337 , ready to retest

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
It looks like AT-2 is adding tests when I submit a review but not canceling out old ones it already started?

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
Could we please move forward and merge?

**Comment by ndellingwood** [comment]
@dalg24 merged
