### ISSUE TITLE
Teuchos broken in Nightly Linux-GCC-4.4.7-MPI_OPT_DEV_XYCE build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1688]
**CC:** @trilinos/framework, @trilinos/teuchos, @ibaned 

**Description:**

Looks like Teuchos is failing to build in the Linux-GCC-4.4.7-MPI_OPT_DEV_XYCE build for all recorded time as shown by:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-09-04&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.4.7-MPI_OPT_DEV_XYCE&field2=buildstarttime&compare2=84&value2=now

For example, the most recent build this morning at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3091595

shows the Teuchos **library** build failures at:

* https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3091596

which shows the error:

```
In file included from /jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/teuchos/parser/src/Teuchos_Reader.cpp:10:
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/teuchos/parser/src/Teuchos_string.hpp:16: error: using ‘typename’ outside of template
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/teuchos/parser/src/Teuchos_string.hpp:22: error: using ‘typename’ outside of template
```

**Comment by bartlettroscoe** [comment]
@ibaned, I think this is the new TeuchosParser code you added a while back.  Can you take a look?  Should be easy to fix.

**Comment by ibaned** [comment]
Oh, I guess this is on me. I've been using GCC 6.1.0 with `--std=c++98`, but I guess that doesn't fully replicate the limitations of GCC 4.4.7. I'll try to fix this soon.

**Comment by ibaned** [comment]
Okay, submitted a proposed fix as #1689

**Comment by ibaned** [comment]
@bartlettroscoe should we see one of these builds every day?

**Comment by bartlettroscoe** [comment]
> should we see one of these builds every day?

Yup.  The link above:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-09-04&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.4.7-MPI_OPT_DEV_XYCE&field2=buildstarttime&compare2=84&value2=now

show you all the builds in recorded history.  You can see the most recent build today at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3093333

which shows Teuchos (and every other package) passing 100%

Thanks!

Closing as complete.
