### ISSUE TITLE
MueLu: compilation errors with AggregationStructuredAlgorithm_kokkos in Cuda builds with Kokkos post-4.0

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#11634]
## Bug Report
@trilinos/muelu 

### Description
When compiling Trilinos using kokkos develop branch, compilation fails in Cuda builds in MueLu in the `AggregationStructuredAlgorithm_kokkos` related code apparently due to inclusion of `Teuchos::FancyOStream` (which are host-only) in functors dispatched to device, for example in this portion of the code:
https://github.com/trilinos/Trilinos/blob/b30c097bc1488b1ea70df42da4acf5428c9b13ad/packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_kokkos_def.hpp#L159-L168

From a skim of the code, possibly due to the `IndexManager_kokkos` member (`geoData`)?

Here is a portion of an error snip:
```
22:06:32 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp(448): error: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::basic_string") from a __device__ function("Kokkos::Impl::ParallelScan< ::MueLu::AggregationStructuredAlgorithm_kokkos<int, long long,  ::Kokkos::Compat::KokkosDeviceWrapperNode< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> > ::computeGraphRowPtrFunctor,  ::Kokkos::RangePolicy< ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::initial const") is not allowed
22:06:32 
22:06:32 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp(448): error: identifier "std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::basic_string" is undefined in device code
22:06:32 
22:06:32 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp(448): error: calling a __host__ function("Teuchos::RCP< ::Teuchos::basic_FancyOStream<char,     ::std::char_traits<char> > > ::RCP") from a __device__ function("Kokkos::Impl::ParallelScan< ::MueLu::AggregationStructuredAlgorithm_kokkos<int, long long,  ::Kokkos::Compat::KokkosDeviceWrapperNode< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> > ::computeGraphRowPtrFunctor,  ::Kokkos::RangePolicy< ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::initial const") is not allowed
22:06:32 
22:06:32 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp(448): error: identifier "Teuchos::RCP< ::Teuchos::basic_FancyOStream<char,     ::std::char_traits<char> > > ::RCP" is undefined in device code
```

### Steps to Reproduce
1. SHA1:  kokkos-promotion branch ab6f4d20c468108803e90b49e348560b96090edd (includes compatibility updates to intrepid2 and stokhos), built with Kokkos develop branch
2. Configuration: this should work on Weaver rhel8 queue:

```bash
module purge
module load git cmake/3.24.2 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1
module load openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1
module load boost/1.70.0/gcc/8.3.1
export OMPI_CXX=$KOKKOS_PATH/bin/nvcc_wrapper

TESTS=ON

cmake \
 -D CMAKE_CXX_COMPILER=`which mpicxx` \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER=`which mpicc` \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER=`which mpifort` \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 -D CMAKE_CXX_STANDARD=17 \
 -D BUILD_SHARED_LIBS=OFF \
\
 -D TPL_ENABLE_CUDA:STRING=ON \
 -D TPL_ENABLE_MPI:STRING=ON \
 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \
 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \
 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \
\
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_Netcdf=OFF \
\
 -D Trilinos_ENABLE_COMPLEX=ON \
 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_EXAMPLES=OFF \
\
 -D Trilinos_ENABLE_Kokkos=ON \
 -D Kokkos_ENABLE_CUDA=ON \
 -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
 -D Kokkos_ENABLE_CUDA_UVM=ON \
 -D Kokkos_ARCH_VOLTA70=ON \
 -D Kokkos_ARCH_POWER9=ON \
 -D Kokkos_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_KokkosKernels=ON \
 -D KokkosKernels_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Tpetra=ON \
 -D Tpetra_ENABLE_CUDA=ON \
 -D Tpetra_ENABLE_SERIAL=ON \
 -D Tpetra_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Sacado=ON \
 -D Sacado_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Belos=ON \
 -D Belos_ENABLE_TESTS=${TESTS} \
\
 -D Trilinos_ENABLE_Zoltan2=ON \
 -D Zoltan2_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Ifpack2=ON \
 -D Ifpack2_ENABLE_TESTS=${TESTS} \
 \
 -D Trilinos_ENABLE_Amesos2=ON \
 -D Amesos2_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Teuchos=ON \
 -D Teuchos_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Zoltan2Sphynx=OFF \
 -D Trilinos_ENABLE_Stokhos=ON \
 -D Stokhos_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Intrepid2=ON \
 -D Intrepid2_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_MueLu=ON \
 -D MueLu_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Panzer=ON \
 -D Trilinos_ENABLE_SEACAS=OFF \
 -D Trilinos_ENABLE_ShyLU_NodeTacho=OFF \
\
-D Kokkos_ENABLE_DEPRECATED_CODE_3=ON \
\
$TRILINOS_DIR
```

If testing with Kokkos and KokkosKernels develop branches, these are the options to allow for source override when creating symbolic links to the respective repos inside the Trilinos source directory:
```
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
```

**Comment by cgcgcg** [comment]
@lucbv ?

**Comment by ndellingwood** [comment]
Testing with release-candidate-4.0.01 branches and recent updates to Trilinos I know longer see this issue. Closing
