### ISSUE TITLE
Kokkos-kernels: error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

### ISSUE THREAD

**Issue by eugeneswalker** [trilinos/Trilinos#12014]
## Bug Report
@crtrott 

### Description
Trying to build Trilinos master branch at
* c1da34c8137b2f002b7020130f536682446a77ad from Fri Jun 30 22:41:57 2023 -0500

Is failing using:
* CUDA 11.8
* GCC 11.2.0

I did a `git bisect` and it looks like, all else equal, the issue is arising from the update to kokkos snapshot
* https://github.com/trilinos/Trilinos/commit/05540e26c01b013781c85b2a0957691035153984

```
...
/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1830): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1865): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

6 errors detected in the compilation of "/build/packages/kokkos-kernels/sparse/eti/generated_specializations_cpp/bspgemm_numeric/Sparse_bspgemm_numeric_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp".
[277/3491] Building CXX object packages/kokkos-kernels/CMakeFiles/kokkoskernels.dir/sparse/eti/gene...v_mv_struct_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o
ninja: build stopped: subcommand failed.
```

### Steps to Reproduce

CMake script: [cmake.sh.txt](https://github.com/trilinos/Trilinos/files/11939637/cmake.sh.txt)
CMake output: [cmake-output.txt](https://github.com/trilinos/Trilinos/files/11939666/cmake-output.txt)
Ninja output: [nohup.txt](https://github.com/trilinos/Trilinos/files/11939656/nohup.txt)

```
$> docker run -it esw123/trilinos-ci:2023-05-01
root@174dbab9d850:/ git clone https://github.com/trilinos/Trilinos.git
root@174dbab9d850:/ (cd Trilinos && git checkout c1da34c8137b2f002b7020130f536682446a77ad)
root@174dbab9d850:/ mkdir build
root@174dbab9d850:/ cd build

root@174dbab9d850:/ export CUDA_ROOT=/opt/trilinos-ci-deps/view
root@174dbab9d850:/ export NVCC_WRAPPER_DEFAULT_COMPILER=g++
root@174dbab9d850:/ export KOKKOS_CXX=g++
root@174dbab9d850:/ export MPICH_CXX=nvcc_wrapper

root@174dbab9d850:/ ./cmake.sh ../Trilinos
# See cmake-output.txt attached above for output
...
root@174dbab9d850:/ time ninja -j48
...
FAILED: packages/kokkos-kernels/CMakeFiles/kokkoskernels.dir/sparse/eti/generated_specializations_cpp/gauss_seidel_apply/Sparse_gauss_seidel_apply_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o
/opt/trilinos-ci-deps/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/mpich-4.1.1-svkefu2g7e2steurvfwwlsluph4ixqqz/bin/mpic++ -DKOKKOS_DEPENDENCE -Dkokkoskernels_EXPORTS -I/build -I/build/packages/kokkos-kernels/blas -I/Trilinos/packages/kokkos-kernels/blas -I/build/packages/kokkos-kernels/graph -I/Trilinos/packages/kokkos-kernels/graph -I/build/packages/kokkos-kernels/ode -I/Trilinos/packages/kokkos-kernels/ode -I/build/packages/kokkos-kernels -I/Trilinos/packages/kokkos-kernels/common/src -I/Trilinos/packages/kokkos-kernels/common/unit_test -I/Trilinos/packages/kokkos-kernels/batched -I/build/packages/kokkos-kernels/batched/eti -I/Trilinos/packages/kokkos-kernels/batched/dense/src -I/Trilinos/packages/kokkos-kernels/batched/dense/impl -I/Trilinos/packages/kokkos-kernels/batched/dense/unit_test -I/Trilinos/packages/kokkos-kernels/batched/sparse/src -I/Trilinos/packages/kokkos-kernels/batched/sparse/impl -I/Trilinos/packages/kokkos-kernels/batched/sparse/unit_test -I/Trilinos/packages/kokkos-kernels/blas/src -I/Trilinos/packages/kokkos-kernels/blas/impl -I/Trilinos/packages/kokkos-kernels/blas/eti -I/build/packages/kokkos-kernels/blas/eti -I/Trilinos/packages/kokkos-kernels/blas/tpls -I/Trilinos/packages/kokkos-kernels/graph/src -I/Trilinos/packages/kokkos-kernels/graph/impl -I/Trilinos/packages/kokkos-kernels/graph/eti -I/build/packages/kokkos-kernels/graph/eti -I/Trilinos/packages/kokkos-kernels/sparse/src -I/Trilinos/packages/kokkos-kernels/sparse/impl -I/Trilinos/packages/kokkos-kernels/sparse/eti -I/build/packages/kokkos-kernels/sparse/eti -I/Trilinos/packages/kokkos-kernels/sparse/tpls -I/Trilinos/packages/kokkos-kernels/ode/src -I/Trilinos/packages/kokkos-kernels/ode/impl -I/Trilinos/packages/kokkos-kernels/ode/unit_test -I/build/packages/kokkos/core/src -I/Trilinos/packages/kokkos/core/src -I/build/packages/kokkos -I/Trilinos/packages/kokkos/core/src/../../tpls/desul/include -I/build/packages/kokkos/containers/src -I/Trilinos/packages/kokkos/containers/src -I/build/packages/kokkos/algorithms/src -I/Trilinos/packages/kokkos/algorithms/src -I/build/packages/kokkos/simd/src -I/Trilinos/packages/kokkos/simd/src -isystem /opt/trilinos-ci-deps/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/cuda-11.8.0-3ormlrvy4nksp2zzvustwmh6k4khhcrw/include -isystem /opt/trilinos-ci-deps/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/openblas-0.3.23-rfka6emvjf67auwa2dwzh4mx757ewmcp/include -isystem /opt/trilinos-ci-deps/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/metis-5.1.0-cfyxpccu64h64r2nglgvxofktyitdspg/include -pedantic -Wall -Wno-long-long -Wwrite-strings    -extended-lambda -Wext-lambda-captures-this -arch=sm_80  -O2 -g -DNDEBUG -std=c++17 -fPIC -extended-lambda -Wext-lambda-captures-this -arch=sm_80 -MD -MT packages/kokkos-kernels/CMakeFiles/kokkoskernels.dir/sparse/eti/generated_specializations_cpp/gauss_seidel_apply/Sparse_gauss_seidel_apply_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o -MF packages/kokkos-kernels/CMakeFiles/kokkoskernels.dir/sparse/eti/generated_specializations_cpp/gauss_seidel_apply/Sparse_gauss_seidel_apply_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o.d -o packages/kokkos-kernels/CMakeFiles/kokkoskernels.dir/sparse/eti/generated_specializations_cpp/gauss_seidel_apply/Sparse_gauss_seidel_apply_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o -c /build/packages/kokkos-kernels/sparse/eti/generated_specializations_cpp/gauss_seidel_apply/Sparse_gauss_seidel_apply_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp
/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1720): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1734): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1791): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1797): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1830): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

/Trilinos/packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp(1865): error: __host__ or __device__ annotation on lambda requires --extended-lambda nvcc flag

6 errors detected in the compilation of "/build/packages/kokkos-kernels/sparse/eti/generated_specializations_cpp/gauss_seidel_apply/Sparse_gauss_seidel_apply_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp".
ninja: build stopped: subcommand failed.

real	0m55.373s
user	5m44.360s
sys	2m42.724s
```

CC @nchaimov @wspear

**Comment by brian-kelley** [comment]
@eugeneswalker I was getting the same thing because the ``nvcc_wrapper`` in my PATH was for an older Kokkos, and it just needed to be updated: https://github.com/kokkos/kokkos/issues/6170

**Comment by eugeneswalker** [comment]
> @eugeneswalker I was getting the same thing because the `nvcc_wrapper` in my PATH was for an older Kokkos, and it just needed to be updated: [kokkos/kokkos#6170](https://github.com/kokkos/kokkos/issues/6170)

Yep, upgrading to kokkos-nvcc-wrapper 4.0.1 resolved it! Thank you!
