### ISSUE TITLE
Question: Teuchos::ParameterLists and non printable entries like enum class

### ISSUE THREAD

**Issue by csteimer** [trilinos/Trilinos#13204]
## Question
Dear Teuchos developers, 

In the past my research group has made extensive use of Teuchos::ParameterList in our inhouse FEM Multiphysics Code. Before #12699 we (unknowingly) abused the missing Parameter Entry validation to set enums and enum class into Parameter Lists. I have added a minimum working example below to showcase our little workaround and the current problem. We do not really care for meaningful print output of our Parameters as the are used internally. Now, that the Validation has been activated and debugged, our entire framework which heavily relies on this combination of enum classes and Parameter Lists, no longer compiles as the static_assert check for printable parameter entries is triggered for enum class during compilation due to the missing implicit type conversion. 

My question now is: 

Would it be possible to make the printability of a parameter optional ? Is there another work around that still allows us to use enum class with Teuchos::ParameterLists? I have not been able to come up with a solution myself with the existing functionality i found in Teuchos. 

Any help or remarks would be highly appreciated as the code base is very large and refactoring this mechanism would be substantial work. 

Many Greetings, 
Christopher Steimer

Mentioning @bartlettroscoe 

<details><summary>Minimal example</summary>

```c++
#include <Teuchos_ParameterList.hpp>
#include <Teuchos_StandardParameterEntryValidators.hpp>
#include <Teuchos_RCP.hpp>
#include <string>


enum Color { RED, GREEN, BLUE };

enum class Shape { CIRCLE, SQUARE, TRIANGLE };

int main() {
    Teuchos::RCP<Teuchos::ParameterList> paramList = Teuchos::rcp(new Teuchos::ParameterList("MyParameters"));
    
    const std::string docu = "";
    const std::string value_name = "val";
    const std::string parameter_name = "someName";
    Teuchos::setStringToIntegralParameter<Color>(parameter_name, value_name, docu, Teuchos::tuple<std::string>(value_name), Teuchos::tuple<Color>(Color::RED), paramList.getRawPtr());
    Teuchos::setStringToIntegralParameter<Shape>(parameter_name, value_name, docu, Teuchos::tuple<std::string>(value_name), Teuchos::tuple<Shape>(Shape::CIRCLE), paramList.getRawPtr());

    return 0;
}
```
</details>

**Comment by csteimer** [comment]
@mayrmt

**Comment by mayrmt** [comment]
@team/teuchos @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@csteimer, does the above example fail to compile?  If you could provide a PR with a Teuchos unit test the reproduces the error, then that would help.  If I can see exactly where this fails, it will be easier to determine how hard it would be to fix this.

**Comment by csteimer** [comment]
> **Updated: 2024-07-03 12:24 PM ET**
> 
> @csteimer, does the above example fail to compile or fail at runtime? If you could provide a PR with a Teuchos unit test the reproduces the error, then that would help. If I can see exactly where this fails, it will be easier to determine how hard it would be to fix this.

It fails to compile. 

As mentioned in the description, since the backwards compatibility breaking fix in #21699,  the static_assert within the cooresponding ParameterEntryValidator is now enforced correctly (I do realize that this was a bug which has been fixed and we unknowingly abused). 

I will create a PR that won't compile, but the problem is very easily reproducable. Create a ParameterList and try to set an enum class ... it will trigger the static_assert with the error:

```
/Teuchos_ParameterEntry.hpp:336:88: error: static assertion failed: ParameterList values must be printable
  336 |   static_assert(std::is_same<typename Teuchos::is_printable<T>::type, std::true_type>::value, "ParameterList values must be printable");
  ``` 
  
  This assert makes sense, as enum class do not have implicit type conversion like enum and thus won't print out the underlying type. We would still like to be able to continue working with enum class to ensure type safety in our code.

**Comment by csteimer** [comment]
see #13206

**Comment by bartlettroscoe** [comment]
@csteimer, thanks for putting in PR #13206. 

> Now, that the Validation has been activated and debugged, our entire framework which heavily relies on this combination of enum classes and Parameter Lists, no longer compiles as the static_assert check for printable parameter entries is triggered for enum class during compilation due to the missing implicit type conversion.

Specifically, which `static_assert()` calls where triggering the build errors in your FEM code?  I see you added some more `static_assert()` checks in #12699 but what checks were failing in your app?

I will try to reproduce the build errors locally and get a better sense of what is happening here and then get back to you.

**Comment by csteimer** [comment]
> @csteimer, thanks for putting in PR #13206.
> 
> > Now, that the Validation has been activated and debugged, our entire framework which heavily relies on this combination of enum classes and Parameter Lists, no longer compiles as the static_assert check for printable parameter entries is triggered for enum class during compilation due to the missing implicit type conversion.
> 
> Specifically, which `static_assert()` calls where triggering the build errors in your FEM code? I see you added some more `static_assert()` checks in #12699 but what checks were failing in your app?
> 
> I will try to reproduce the build errors locally and get a better sense of what is happening here and then get back to you.

I simpley split up the original `static_assert()` into two asserts to check if it failes due to the comparability or the printability condition. It fails due to the printability assertion.

**Comment by bartlettroscoe** [comment]
@csteimer, I don't remember what is going on with the `Teuchos::is_printable` traits class involved in the build error shown https://github.com/trilinos/Trilinos/pull/13206#issuecomment-2219194013 (and thank you for putting in that PR and that reproducer).

It looks like @ibaned set up support for these checks in the commit 9f352b44e210a4d1d6d9b766ff4ede2a67812fcb with the commit message:

>     Teuchos: Relax requirements of Teuchos::any
>    
>    By using C++11 template metaprogramming, we can
>    continue to support the comparison and print
>    extensions of Teuchos::any while still having
>    a safe compilation path in the case that the
>    held type doesn't have comparison or print operators.
>    Exceptions will be thrown if an unsupported operation
>    is attempted.
>    We can even automatically detect whether types
>    have this support by using SFINAE techniques.
>    This safely allows users to hold types in
>    Teuchos::any that don't have both comparison and
>    print operators.

With a little Git searching, it looks like that commit was part of PR #2196 from 2018.  It sounds like that PR supports the type of use case you have described in that issue where it should support types that don't support comparison or printability?  (NOTE: It appears I reviewed that PR but I have no memory of this at all as it was over 6 years ago).

I am wondering if there needs to be similar tweaks to the parameter validation software as were put in to the Teuchos::ParamterEntry class in PR #2196?

@csteimer, would you be willing to look over PR #2196 and see how the changes in that PR might be applied to fix this issue you are having?  If not, I will need to dig into this code again and refresh my memory of what is going on here to suggest a solution.

**Comment by csteimer** [comment]
> @csteimer, would you be willing to look over PR #2196 and see how the changes in that PR might be applied to fix this issue you are having? If not, I will need to dig into this code again and refresh my memory of what is going on here to suggest a solution.

I had a look at the mentioned PR and I believe the following is the case: 

- The merged changes affected mostly the `Teuchos::Reader` Class. Due to the changes to `Teuchos::any` it then supported non-printable types. This however did not extend to the `ParameterEntry` class.

-  Regarding the `ParameterList` you [commented](https://github.com/trilinos/Trilinos/pull/2196/files#r164585867) the following: 

> I think the downside of these changes is that when people try to insert a type into a Teuchos::ParameterList that does not support the needed operators operator==() and operator<<() that instead of getting a compile-time error as they did before, they will now get a runtime error. That is not the end of the world but compile-time errors are typically desired over runtime errors. The former will be caught right away and the latter may not be caught until much later when it really hurts.
>
>Could we put in extra compile-time checks in the Teuchos::ParameterList related class code that asserts that the underlying type has the needed operators? I guess you could do that with a compile-time assert template and typedecl() calls like shown here, right?

This was achieved by adding the `static_assert` in `Teuchos_ParameterEntry.hpp`:
```
  static_assert(std::is_same<typename Teuchos::is_comparable<T>::type, std::true_type>::value &&
                std::is_same<typename Teuchos::is_printable<T>::type, std::true_type>::value,
                "ParameterList values must be comparable and printable!");
```
However, I checked and without this `static_assert` an error is only run at runtime when the parameter list is to be printed.
E.g. for trying to print a parameter list with a std::vector<int> set as a parameter it throws an error like: 

```
59: 56. ParameterList_NonPrintableParameterEntries_UnitTest ... test std::vector<int> = 
59:  
59:  p=0: *** Caught standard std::exception of type 'std::runtime_error' :
59:  
59:   /home/trilinos/trilinos-src/packages/teuchos/core/src/Teuchos_any.hpp:136:
59:   
59:   Throw number = 19
59:   
59:   Throw test that evaluated to true: true
59:   
59:   Trying to print type St6vectorIiSaIiEE which is not printable
```
If the parameter list is never printed it doesn't throw an error. 

Would it possibly be an option to make non-printable parameter list entries a configuration option (so to say the "unsafe" non-default option)? It would then be up to the user to ensure propper use of the parameter list entries. 

Maybe it could also be an option to not throw an error in case of non-printability, but instead simply print the name and a template type deduction or something similar for a minimal amount of debug information, as this is what the printability is used for most I would guess. 

These are some of the options I can come up with at the top of my head. I hope this short summary is of help.

**Comment by bartlettroscoe** [comment]
@csteimer, perhaps it is best then to remove the `static_assert()` calls and improve the runtime error message when someone tries to print a Teuchos::ParameterList where one or more of the entries does not support printability?  We would need some unit tests that tried to print Teuchos::ParameterList object with one or more Teuchos::ParameterEntry objects that can't be printed and then catch the exception and check the error message.

**Comment by csteimer** [comment]
I can take a look at it!

**Comment by mayrmt** [comment]
PR #13206 closes this issue.
