### ISSUE TITLE
Error compiling Trilinos with SuperLU

### ISSUE THREAD

**Issue by dpo** [trilinos/Trilinos#563]
I'm using SuperLU 5.2.1 on OSX 10.9. Compiling Trilinos with SuperLU enabled yields the error

```
/tmp/trilinos-20160818-10767-s2jqhc/Trilinos-trilinos-release-12-6-4/packages/amesos/src/Amesos_Superlu.cpp:479:5: error: no matching function for call to 'dgssvx'
    dgssvx( &(SLUopt), &(data_->A),
    ^~~~~~
/usr/local/opt/superlu/include/superlu/slu_ddefs.h:111:1: note: candidate function not viable: requires 22 arguments, but 21 were provided
dgssvx(superlu_options_t *, SuperMatrix *, int *, int *, int *,
^
```

Looking through [one of the SuperLU examples](https://gist.github.com/79b384cb51e8a2692b886907a23f52d5), it is the `GlobalLU_t Glu` argument that is missing. I can't submit a patch due to my (lack of) understanding of Amesos and C++ but hopefully, you'll see what's missing.

Thanks.

**Comment by mhoemmen** [comment]
Trilinos is known to work with SuperLU 4.3.  SuperLU 5 has a different interface.

**Comment by dpo** [comment]
Right but SuperLU 5 has been with us for over a year. Is the upgrade in the cards?

**Comment by mhoemmen** [comment]
@trilinos/amesos @trilinos/amesos2

**Comment by srajama1** [comment]
SuplerLU 5 was released few months ago and this is the first request for it. We can do this.

**Comment by srajama1** [comment]
My bad. I didn't realize this was for SuperLU and not SuperLU_Dist. Also, I see you want it for Amesos (not Amesos2). This will be very low priority for us as we recommend moving to Amesos2. Supporting it in Amesos2 will be useful for a number of people so we can add it to the list.

What is the target application ? Can you give little more context ?

**Comment by dpo** [comment]
@srajama1 Thanks for pointing that out. I don't have a specific application and I'm happy to use Amesos2 instead of Amesos if it's more useful for people. I'm one of the maintainers of Homebrew/Science trying to make the Trilinos formula as useful as possible by default.

**Comment by mhoemmen** [comment]
btw @srajama1 and his colleagues made Amesos2 work with Epetra objects as well as Tpetra objects, so you might be able to switch to Amesos2 even if you want to keep using Epetra objects.

**Comment by bavier** [comment]
This seems to be a duplicate of #379, which was translated to pull request #411

**Comment by srajama1** [comment]
Thanks, @bavier . I wasn't aware of the #379 at all. It would be better to reference @trilinos/amesos2 . I will start searching on label more often.

**Comment by aprokop** [comment]
If this is a duplicate, why is it still open? Closing.
