### ISSUE TITLE
Trilinos: does not build on Windows with LLVM-11.0, clang-cl

### ISSUE THREAD

**Issue by jrobcary** [trilinos/Trilinos#8202]
## Bug Report
@trilinos/\<TPetra\>

### Description
This is a companion issue to #8200 (https://github.com/trilinos/Trilinos/issues/8200), but with LLVM-11.0, clang-cl,
to document the failure  to build Trilinos on Windows without CUDA.  The goal is to have the new stack that allows 64b indices.

### Steps to Reproduce
1. SHA1:  [e4ca51d4b3ebd1937507dfe92ea6d495ef4ee7b8]
1. Configure script:  [
[grating.txcorp.com-trilinos-sercomm-configsh.txt](https://github.com/trilinos/Trilinos/files/5385432/grating.txcorp.com-trilinos-sercomm-configsh.txt)
]
1. Configure log:  [
[grating.txcorp.com-trilinos-sercomm-config.txt](https://github.com/trilinos/Trilinos/files/5385434/grating.txcorp.com-trilinos-sercomm-config.txt)
]
1. Build log:  [
[nmake.txt](https://github.com/trilinos/Trilinos/files/5385548/nmake.txt)
]

27 errors:
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src/Amesos2_Superlu_def.hpp(762,18): error: no member named 'LargeDiag' in namespace 'SLU'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(119,17): error: no matching function for call to 'trilinos_btf_l_order'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(126,16): error: no matching function for call to 'trilinos_btf_l_strongcomp'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(132,17): error: no matching function for call to 'trilinos_amd_l_order'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(138,16): error: no matching function for call to 'trilinos_colamd_l'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\epetra\src\Epetra_SerialComm.h(83,42): error: allocating an object of abstract class type 'Epetra_SerialComm'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\intrepid2\src\Shared\Intrepid2_PolylibDef.hpp(880,43): error: use of undeclared identifier 'M_PI'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\intrepid2\src\Shared\Intrepid2_PolylibDef.hpp(886,20): error: use of undeclared identifier 'M_PI'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\kokkos\core\src\impl/Kokkos_ChaseLev.hpp(196,13): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\kokkos\core\src\impl/Kokkos_ChaseLev.hpp(256,11): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\kokkos-kernels\src\sparse/KokkosSparse_CrsMatrix.hpp(699,19): error: no member named 'atomic_assign' in namespace 'Kokkos'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(292,7): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(303,7): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(340,7): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(396,11): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_EpetraRowMatrix.cpp(74,71): error: allocating an object of abstract class type 'Epetra_SerialComm'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(262,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(279,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(296,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(327,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(344,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(374,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(390,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(421,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(441,3): error: use of undeclared identifier 'ssize_t'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\zoltan2\core\src\input\Zoltan2_InputTraits.hpp(472,3): error: use of undeclared identifier 'ssize_t'
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by mayrmt** [comment]
@trilinos/tpetra

**Comment by jrobcary** [comment]
Some of these errors are due to the fact that long is 4 bytes on Windows64, but 8 bytes on Linux64.  Others that for Windows, ssize_t is not defined, so one should use ptrdiff_t:

`#if defined(_MSC_VER)
#include <stddef.h>
#ifndef ssize_t
#define ssize_t ptrdiff_t
#endif
#else
#include <unistd.h>
#endif`

M_PI comes from

`#if defined(_MSC_VER) || defined(_WIN32) && defined(__ICL)
// M_PI, M_SQRT2, etc. are hidden in MSVC by #ifdef _USE_MATH_DEFINES
  #ifndef _USE_MATH_DEFINES
  #define _USE_MATH_DEFINES
  #endif
  #include <math.h>
#endif` 

I'll fix some of the low hanging fruit.

**Comment by jrobcary** [comment]
Now down to the 14 errors:

No idea about this:

D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src/Amesos2_Superlu_def.hpp(762,18): error: no member named 'LargeDiag' in namespace 'SLU'

1. These are due, I think, to long being a different size on Windows.  Not sure how to fix.

D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(119,17): error: no matching function for call to 'trilinos_btf_l_order'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(126,16): error: no matching function for call to 'trilinos_btf_l_strongcomp'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(132,17): error: no matching function for call to 'trilinos_amd_l_order'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src\KLU2\Include/klu2_ordinaltraits.h(138,16): error: no matching function for call to 'trilinos_colamd_l'

2. No idea on this yet:

D:\winsame\cary\vorpalall-dev3\Trilinos\packages\epetra\src\Epetra_SerialComm.h(83,42): error: allocating an object of abstract class type 'Epetra_SerialComm'

3. No idea on these yet:

D:\winsame\cary\vorpalall-dev3\Trilinos\packages\kokkos\core\src\impl/Kokkos_ChaseLev.hpp(196,13): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\kokkos\core\src\impl/Kokkos_ChaseLev.hpp(256,11): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\kokkos-kernels\src\sparse/KokkosSparse_CrsMatrix.hpp(699,19): error: no member named 'atomic_assign' in namespace 'Kokkos'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(292,7): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(303,7): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(340,7): error: call to 'atomic_compare_exchange_strong' is ambiguous
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(396,11): error: call to 'atomic_compare_exchange_strong' is ambiguous

4. Same as 2.

D:\winsame\cary\vorpalall-dev3\Trilinos\packages\tpetra\core\src\Tpetra_EpetraRowMatrix.cpp(74,71): error: allocating an object of abstract class type 'Epetra_SerialComm'

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by kddevin** [comment]
Changing title of issue; these compiler errors are not all in Tpetra.
@trilinos/kokkos @trilinos/kokkos-kernels @trilinos/amesos2 @trilinos/epetra @trilinos/tpetra

**Comment by crtrott** [comment]
The Kokkos 3.3.1 release (#8490 ) should fix the Kokkos issues.

**Comment by jrobcary** [comment]
Kokkos is indeed fixed.  Thanks.  How does that get into trilinos?

**Comment by csiefer2** [comment]
@jrobcary Are you still having problems with Windows builds?
