### ISSUE TITLE
MueLu: Compilation error with rocm/6.2.1, MueLu_CombinePFactory_def.hpp:81:23: error: reference to __host__ function 'operator=' in __host__ __device__ function

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#14442]
## Bug Report
@trilinos/muelu 

### Description
While testing Trilinos in a Hip build with rocm/6.2.1 and c++20 (I'm not sure c++20 is relevant, but was enabled in my testing) I ran into the following compilation error:

```
[1564/8800] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp.o
FAILED: packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp.o 
/spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/openmpi-4.1.5-zjwyjs6jgmnclzxwlhmaf3mwvxqiapir/bin/mpicxx -DKOKKOS_DEPENDENCE -DUSE_PROF_API=1 -D__HIP_PLATFORM_AMD__=1 -I/root/build -I/root/Trilinos/packages/muelu/src -I/root/Trilinos/packages/muelu/src/Graph -I/root/Trilinos/packages/muelu/src/Graph/BrickAggregation -I/root/Trilinos/packages/muelu/src/Graph/Containers -I/root/Trilinos/packages/muelu/src/Graph/HybridAggregation -I/root/Trilinos/packages/muelu/src/Graph/MatrixTransformation -I/root/Trilinos/packages/muelu/src/Graph/PairwiseAggregation -I/root/Trilinos/packages/muelu/src/Graph/StructuredAggregation -I/root/Trilinos/packages/muelu/src/Graph/StructuredAggregation/coupled -I/root/Trilinos/packages/muelu/src/Graph/StructuredAggregation/uncoupled -I/root/Trilinos/packages/muelu/src/Graph/UncoupledAggregation -I/root/Trilinos/packages/muelu/src/Graph/UserAggregation -I/root/Trilinos/packages/muelu/src/Headers -I/root/Trilinos/packages/muelu/src/Interface -I/root/Trilinos/packages/muelu/src/Interface/FacadeClasses -I/root/Trilinos/packages/muelu/src/Misc -I/root/Trilinos/packages/muelu/src/MueCentral -I/root/Trilinos/packages/muelu/src/Operators -I/root/Trilinos/packages/muelu/src/Rebalancing -I/root/Trilinos/packages/muelu/src/Smoothers -I/root/Trilinos/packages/muelu/src/Transfers/BaseClass -I/root/Trilinos/packages/muelu/src/Transfers/BlackBox -I/root/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers -I/root/Trilinos/packages/muelu/src/Transfers/BlockedTransfers -I/root/Trilinos/packages/muelu/src/Transfers/Classical -I/root/Trilinos/packages/muelu/src/Transfers/Energy-Minimization -I/root/Trilinos/packages/muelu/src/Transfers/Energy-Minimization/Solvers -I/root/Trilinos/packages/muelu/src/Transfers/GeneralGeometric -I/root/Trilinos/packages/muelu/src/Transfers/Generic -I/root/Trilinos/packages/muelu/src/Transfers/Geometric-Interpolation -I/root/Trilinos/packages/muelu/src/Transfers/Matrix-Free -I/root/Trilinos/packages/muelu/src/Transfers/Petrov-Galerkin-SA -I/root/Trilinos/packages/muelu/src/Transfers/SemiCoarsen -I/root/Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation -I/root/Trilinos/packages/muelu/src/Transfers/User -I/root/Trilinos/packages/muelu/src/Utils -I/root/Trilinos/packages/muelu/src/Utils/ForwardDeclaration -I/root/Trilinos/packages/muelu/src/../adapters/xpetra -I/root/Trilinos/packages/muelu/src/../adapters/tpetra -I/root/Trilinos/packages/muelu/src/../adapters/stratimikos -I/root/Trilinos/packages/muelu/src/../adapters/thyra -I/root/Trilinos/packages/muelu/src/Transfers/PCoarsen -I/root/build/packages/muelu/src -I/root/build/packages/teuchos/core/src -I/root/Trilinos/packages/teuchos/core/src -I/root/build/packages/kokkos -I/root/build/packages/kokkos/core/src -I/root/Trilinos/packages/kokkos/core/src -I/root/build/packages/kokkos/containers/src -I/root/Trilinos/packages/kokkos/containers/src -I/root/build/packages/kokkos/algorithms/src -I/root/Trilinos/packages/kokkos/algorithms/src -I/root/build/packages/kokkos/simd/src -I/root/Trilinos/packages/kokkos/simd/src -I/root/Trilinos/packages/teuchos/parser/src -I/root/Trilinos/packages/teuchos/parameterlist/src -I/root/build/packages/teuchos/parameterlist/src -I/root/Trilinos/packages/teuchos/comm/src -I/root/Trilinos/packages/teuchos/numerics/src -I/root/Trilinos/packages/teuchos/remainder/src -I/root/build/packages/teuchos/remainder/src -I/root/build/packages/teuchos/kokkoscompat/src -I/root/Trilinos/packages/teuchos/kokkoscompat/src -I/root/build/packages/teuchos/kokkoscomm/src -I/root/Trilinos/packages/teuchos/kokkoscomm/src -I/root/Trilinos/packages/tpetra/tsqr/src -I/root/build/packages/tpetra/tsqr/src -I/root/build/packages/kokkos-kernels/blas -I/root/Trilinos/packages/kokkos-kernels/blas -I/root/build/packages/kokkos-kernels/lapack -I/root/Trilinos/packages/kokkos-kernels/lapack -I/root/build/packages/kokkos-kernels/graph -I/root/Trilinos/packages/kokkos-kernels/graph -I/root/Trilinos/packages/kokkos-kernels/ode -I/root/build/packages/kokkos-kernels -I/root/Trilinos/packages/kokkos-kernels/common/src -I/root/Trilinos/packages/kokkos-kernels/common/impl -I/root/Trilinos/packages/kokkos-kernels/batched -I/root/build/packages/kokkos-kernels/batched/eti -I/root/Trilinos/packages/kokkos-kernels/batched/dense/src -I/root/Trilinos/packages/kokkos-kernels/batched/dense/impl -I/root/Trilinos/packages/kokkos-kernels/batched/sparse/src -I/root/Trilinos/packages/kokkos-kernels/batched/sparse/impl -I/root/Trilinos/packages/kokkos-kernels/blas/src -I/root/Trilinos/packages/kokkos-kernels/blas/impl -I/root/Trilinos/packages/kokkos-kernels/blas/eti -I/root/build/packages/kokkos-kernels/blas/eti -I/root/Trilinos/packages/kokkos-kernels/blas/tpls -I/root/Trilinos/packages/kokkos-kernels/lapack/src -I/root/Trilinos/packages/kokkos-kernels/lapack/impl -I/root/Trilinos/packages/kokkos-kernels/lapack/eti -I/root/build/packages/kokkos-kernels/lapack/eti -I/root/Trilinos/packages/kokkos-kernels/lapack/tpls -I/root/Trilinos/packages/kokkos-kernels/graph/src -I/root/Trilinos/packages/kokkos-kernels/graph/impl -I/root/Trilinos/packages/kokkos-kernels/graph/eti -I/root/build/packages/kokkos-kernels/graph/eti -I/root/Trilinos/packages/kokkos-kernels/sparse/src -I/root/Trilinos/packages/kokkos-kernels/sparse/impl -I/root/Trilinos/packages/kokkos-kernels/sparse/eti -I/root/build/packages/kokkos-kernels/sparse/eti -I/root/Trilinos/packages/kokkos-kernels/sparse/tpls -I/root/Trilinos/packages/kokkos-kernels/ode/src -I/root/Trilinos/packages/kokkos-kernels/ode/impl -I/root/Trilinos/packages/tpetra/core/compat -I/root/build/packages/tpetra/core/compat -I/root/Trilinos/packages/tpetra/core/src -I/root/Trilinos/packages/tpetra/core/src/kokkos_refactor -I/root/build/packages/tpetra/core/src -I/root/Trilinos/packages/tpetra/core/inout -I/root/build/packages/tpetra/core/inout -I/root/Trilinos/packages/tpetra/core/ext -I/root/build/packages/tpetra/core/ext -I/root/Trilinos/packages/xpetra/src/CrsGraph -I/root/Trilinos/packages/xpetra/src/CrsMatrix -I/root/Trilinos/packages/xpetra/src/BlockedCrsMatrix -I/root/Trilinos/packages/xpetra/src/DistObject -I/root/Trilinos/packages/xpetra/src/Export -I/root/Trilinos/packages/xpetra/src/Headers -I/root/Trilinos/packages/xpetra/src/Import -I/root/Trilinos/packages/xpetra/src/Map -I/root/Trilinos/packages/xpetra/src/BlockedMap -I/root/Trilinos/packages/xpetra/src/MultiVector -I/root/Trilinos/packages/xpetra/src/BlockedMultiVector -I/root/Trilinos/packages/xpetra/src/BlockedVector -I/root/Trilinos/packages/xpetra/src/Matrix -I/root/Trilinos/packages/xpetra/src/Operator -I/root/Trilinos/packages/xpetra/src/Platform -I/root/Trilinos/packages/xpetra/src/RowGraph -I/root/Trilinos/packages/xpetra/src/RowMatrix -I/root/Trilinos/packages/xpetra/src/StridedMap -I/root/Trilinos/packages/xpetra/src/Utils -I/root/Trilinos/packages/xpetra/src/Utils/ForwardDeclaration -I/root/Trilinos/packages/xpetra/src/Vector -I/root/build/packages/xpetra/src -I/root/Trilinos/packages/thyra/core/src -I/root/Trilinos/packages/thyra/core/src/interfaces/operator_vector/fundamental -I/root/Trilinos/packages/thyra/core/src/interfaces/operator_vector/extended -I/root/Trilinos/packages/thyra/core/src/support/operator_vector/client_support -I/root/Trilinos/packages/thyra/core/src/support/operator_vector/adapter_support -I/root/Trilinos/packages/thyra/core/src/interfaces/operator_solve/fundamental -I/root/Trilinos/packages/thyra/core/src/interfaces/operator_solve/extended -I/root/Trilinos/packages/thyra/core/src/support/operator_solve/client_support -I/root/Trilinos/packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental -I/root/Trilinos/packages/thyra/core/src/support/nonlinear/model_evaluator/client_support -I/root/Trilinos/packages/thyra/core/src/interfaces/nonlinear/solvers/fundamental -I/root/Trilinos/packages/thyra/core/src/support/nonlinear/solvers/client_support -I/root/build/packages/thyra/core/src -I/root/Trilinos/packages/thyra/core/example/operator_vector -I/root/Trilinos/packages/rtop/src -I/root/Trilinos/packages/rtop/src/interfaces -I/root/Trilinos/packages/rtop/src/support -I/root/Trilinos/packages/rtop/src/ops_lib -I/root/Trilinos/packages/rtop/src/lapack -I/root/build/packages/rtop/src -I/root/Trilinos/packages/thyra/adapters/tpetra/src -I/root/Trilinos -I/root/build/packages/amesos2/src -I/root/Trilinos/packages/amesos2/src -I/root/Trilinos/packages/amesos2/src/KLU2/Include -I/root/Trilinos/packages/amesos2/src/KLU2/Source -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/AMD/Include -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/COLAMD/Include -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/BTF/Include -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/UFconfig -I/root/build/packages/common/auxiliarySoftware/SuiteSparse/src -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CAMD/Include -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CCOLAMD/Include -I/root/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/KLU/Include -I/root/build/packages/shylu/shylu_node/tacho/src -I/root/Trilinos/packages/shylu/shylu_node/tacho/src -I/root/Trilinos/packages/shylu/shylu_node/tacho/src/impl -I/root/build/packages/belos/src -I/root/Trilinos/packages/belos/src -I/root/build/packages/belos/tpetra/src -I/root/Trilinos/packages/belos/tpetra/src -I/root/build/packages/belos/xpetra/src -I/root/Trilinos/packages/belos/xpetra/src -I/root/build/packages/teko/src -I/root/Trilinos/packages/teko/src -I/root/Trilinos/packages/teko/src/NS -I/root/Trilinos/packages/teko/src/Tpetra -I/root/Trilinos/packages/stratimikos/adapters/amesos2/src -I/root/build/packages/stratimikos/adapters/amesos2/src -I/root/Trilinos/packages/ifpack2/src -I/root/build/packages/ifpack2/src -I/root/Trilinos/packages/zoltan2/core/src -I/root/build/packages/zoltan2/core/src -I/root/Trilinos/packages/zoltan2/core/src/algorithms -I/root/Trilinos/packages/zoltan2/core/src/algorithms/partition -I/root/Trilinos/packages/zoltan2/core/src/algorithms/order -I/root/Trilinos/packages/zoltan2/core/src/algorithms/color -I/root/Trilinos/packages/zoltan2/core/src/algorithms/match -I/root/Trilinos/packages/zoltan2/core/src/algorithms/map -I/root/Trilinos/packages/zoltan2/core/src/algorithms/zoltan -I/root/Trilinos/packages/zoltan2/core/src/environment -I/root/Trilinos/packages/zoltan2/core/src/include -I/root/Trilinos/packages/zoltan2/core/src/input -I/root/Trilinos/packages/zoltan2/core/src/models -I/root/Trilinos/packages/zoltan2/core/src/problems -I/root/Trilinos/packages/zoltan2/core/src/TpetraCrsColorer -I/root/Trilinos/packages/zoltan2/core/src/util -I/root/Trilinos/packages/zoltan2/core/src/directory -I/root/build/packages/zoltan/src -I/root/Trilinos/packages/zoltan/src/include -I/root/Trilinos/packages/zoltan/src/all -I/root/Trilinos/packages/zoltan/src/coloring -I/root/Trilinos/packages/zoltan/src/graph -I/root/Trilinos/packages/zoltan/src/ha -I/root/Trilinos/packages/zoltan/src/hier -I/root/Trilinos/packages/zoltan/src/hsfc -I/root/Trilinos/packages/zoltan/src/lb -I/root/Trilinos/packages/zoltan/src/matrix -I/root/Trilinos/packages/zoltan/src/order -I/root/Trilinos/packages/zoltan/src/par -I/root/Trilinos/packages/zoltan/src/params -I/root/Trilinos/packages/zoltan/src/tpls -I/root/Trilinos/packages/zoltan/src/phg -I/root/Trilinos/packages/zoltan/src/rcb -I/root/Trilinos/packages/zoltan/src/reftree -I/root/Trilinos/packages/zoltan/src/simple -I/root/Trilinos/packages/zoltan/src/timer -I/root/Trilinos/packages/zoltan/src/Utilities/Communication -I/root/Trilinos/packages/zoltan/src/Utilities/DDirectory -I/root/Trilinos/packages/zoltan/src/Utilities/Timer -I/root/Trilinos/packages/zoltan/src/Utilities/shared -I/root/Trilinos/packages/zoltan/src/zz -I/root/build/packages/shylu/shylu_node/fastilu/src -I/root/Trilinos/packages/shylu/shylu_node/fastilu/src -I/root/Trilinos/packages/ifpack2/adapters/thyra -I/root/build/packages/ifpack2/adapters -I/root/Trilinos/packages/stratimikos/adapters/belos/src -I/root/Trilinos/packages/stratimikos/adapters/belos/src/tpetra -I/root/build/packages/stratimikos/adapters/belos/src -I/root/build/packages/stratimikos/adapters/belos/src/../../../src -I/root/build/packages/stratimikos/src -I/root/Trilinos/packages/stratimikos/src -I/root/build/packages/anasazi/src -I/root/Trilinos/packages/anasazi/src -I/root/Trilinos/packages/anasazi/src/../thyra/src -I/root/Trilinos/packages/anasazi/src/../tpetra/src -I/root/build/packages/anasazi/tpetra/src -I/root/Trilinos/packages/anasazi/tpetra/src -I/root/build/packages/anasazi/tpetra/util/ModeLaplace -I/root/Trilinos/packages/anasazi/tpetra/util/ModeLaplace -I/root/build/packages/intrepid2/src -I/root/Trilinos/packages/intrepid2/src/Cell -I/root/Trilinos/packages/intrepid2/src/Discretization/Basis -I/root/Trilinos/packages/intrepid2/src/Discretization/FunctionSpaceTools -I/root/Trilinos/packages/intrepid2/src/Discretization/Integration -I/root/Trilinos/packages/intrepid2/src/Orientation -I/root/Trilinos/packages/intrepid2/src/Projection -I/root/Trilinos/packages/intrepid2/src/Shared -I/root/Trilinos/packages/intrepid2/src -I/root/build/packages/shards/src -I/root/Trilinos/packages/shards/src -I/root/build/packages/sacado/src -I/root/Trilinos/packages/sacado/src -I/root/Trilinos/packages/sacado/src/new_design -I/root/Trilinos/packages/sacado/src/template -I/root/Trilinos/packages/sacado/src/parameter -I/root/Trilinos/packages/sacado/src/mpl -isystem /root/Trilinos/packages/kokkos/tpls/desul/include -isystem /root/Trilinos/packages/kokkos/tpls/mdspan/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/rocthrust-6.2.1-ttnxq5h4zftkldmrtfphvzqwxebkouqe/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/rocprim-6.2.1-py5iu6nbpdhlr3o3cfqivk6qj7q5gs4v/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/hip-6.2.1-6aipx6xfvbtd2w44avi5necf46yxcbfr/include -isystem /spack/opt/spack/linux-rhel9-zen2/gcc-11.5.0/boost-1.86.0-zh7i5qqg6kmkkrmmxs3jew76ainfriga/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/openblas-0.3.28-hghimn3tvswxuwp6cdqlrauai5jmtoen/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/metis-5.1.0-ksfws6tni6clergm7yjb4x5vfefywp3r/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/rocblas-6.2.1-toelfpseg2nyyztrqafwq4pvpayerhzg/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/rocsparse-6.2.1-e2yzvswixlv3vo5va4pzh6wkavy5dx25/include -isystem /spack/opt/spack/linux-rhel9-zen3/gcc-11.5.0/rocsolver-6.2.1-fjjds2mjo5mmzzea7vz57kqnhj2agig7/include -O3 -DNDEBUG -std=c++20 -fno-gpu-rdc --offload-arch=gfx90a -x hip --offload-arch=gfx90a -MD -MT packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp.o -MF packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp.o.d -o packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp.o -c /root/build/packages/muelu/src/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp
In file included from /root/build/packages/muelu/src/Utils/ExplicitInstantiation/ETI_MueLu_CombinePFactory.cpp:18:
/root/Trilinos/packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp:81:23: error: reference to __host__ function 'operator=' in __host__ __device__ function
   81 |         values(index) = Scalar(1.0);
      |                       ^
/root/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP_ParallelFor_Range.hpp:44:5: note: called by 'exec_range<void>'
   44 |     m_functor(i);
      |     ^
/root/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP_ParallelFor_Range.hpp:70:22: note: called by 'operator()'
   70 |       this->template exec_range<WorkTag>(iwork);
      |                      ^
/root/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP_KernelLaunch.hpp:76:3: note: called by 'hip_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<(lambda at /root/Trilinos/packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp:78:7), Kokkos::RangePolicy<int, Kokkos::HIP>>>'
   76 |   driver();
      |   ^
/root/Trilinos/packages/kokkos/core/src/Kokkos_Complex.hpp:130:12: note: 'operator=' declared here
  130 |   complex& operator=(const std::complex<RealType>& src) noexcept {
      |            ^
1 error generated when compiling for gfx90a.
```

@trilinos/muelu would something like this be the correct way to resolve the issue (I'm not sure if value_type vs scalar_value_type should be used)?

```diff
diff --git a/packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp b/packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp
index 5f55ab34586..1c3ae3cf3d7 100644
--- a/packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp
+++ b/packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp
@@ -78,7 +78,7 @@ constructIdentityProlongator(const Teuchos::RCP<const Xpetra::Map<LocalOrdinal,
       KOKKOS_LAMBDA(const LocalOrdinal index) {
         rowptr(index) = index;
         colind(index) = index;
-        values(index) = Scalar(1.0);
+        values(index) = typename values_type::value_type(1.0);
         if (index == (numLocal - 1)) {
           rowptr(numLocal) = numLocal;
         }
```

### Steps to Reproduce
1. SHA1:  056b17a63cda530f560c965cda30b1e410687f35
1. Configure script:  Tested in container on Caraway MI250 queue, here is the cmake line:

```bash
cmake -B "${BUILD_DIR}" -G Ninja -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" -D CMAKE_CXX_COMPILER="$(which mpicxx)" -D CMAKE_C_COMPILER="$(which mpicc)" -D CMAKE_Fortran_COMPILER="$(which mpifort)" -D CMAKE_BUILD_TYPE:STRING=RELEASE -D CMAKE_CXX_STANDARD=20 -D BUILD_SHARED_LIBS=OFF -D TPL_ENABLE_CUDA:STRING=${ENABLE_CUDA} -D TPL_ENABLE_CUSPARSE:STRING=${ENABLE_CUDA} -D TPL_ENABLE_ROCBLAS:STRING=${ENABLE_HIP} -D TPL_ENABLE_ROCSPARSE:STRING=${ENABLE_HIP} -D TPL_ENABLE_ROCSOLVER:STRING=${ENABLE_HIP} -D TPL_ENABLE_MPI:STRING=ON     -D MPI_BASE_DIR:PATH="${OPENMPI_ROOT}"     -D MPI_BIN_DIR:PATH="${OPENMPI_ROOT}/bin"     -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" -D TPL_ENABLE_BLAS:STRING=ON     -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib"     -D BLAS_LIBRARY_NAMES:STRING="openblas" -D TPL_ENABLE_LAPACK:STRING=ON     -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include"     -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib"     -D LAPACK_LIBRARY_NAMES:STRING="openblas" -D TPL_ENABLE_Boost=ON     -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include"     -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" -D TPL_ENABLE_BoostLib=ON     -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include"     -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" -D TPL_ENABLE_HDF5=ON     -D HDF5_INCLUDE_DIRS="${HDF5_ROOT}/include"     -D TPL_HDF5_LIBRARIES="${CONFIG_HDF5_LIBS}" -D TPL_ENABLE_Netcdf=ON -D TPL_Netcdf_PARALLEL=ON     -D TPL_Netcdf_INCLUDE_DIRS="${NETCDF_C_ROOT}/include"     -D TPL_Netcdf_LIBRARIES="${CONFIG_NETCDF_ALL_LIBS}" -D TPL_ENABLE_SuperLU:BOOL=OFF     -D SuperLU_INCLUDE_DIRS:FILEPATH="${SUPERLU_ROOT}/include"     -D SuperLU_LIBRARY_DIRS:FILEPATH="${SUPERLU_ROOT}/lib"     -D SuperLU_LIBRARY_NAMES:STRING="superlu" -D TPL_ENABLE_METIS:BOOL=ON     -D METIS_INCLUDE_DIRS:PATH="${METIS_ROOT}/include"     -D METIS_LIBRARY_DIRS:PATH="${METIS_ROOT}/lib"     -D METIS_LIBRARY_NAMES:STRING="metis" -D TPL_ENABLE_ParMETIS:BOOL=OFF -D TPL_ENABLE_Matio=OFF -D Trilinos_ENABLE_COMPLEX=ON -D Trilinos_ENABLE_OpenMP=${ENABLE_OPENMP} -D Trilinos_ENABLE_TESTS=ON -D Trilinos_ENABLE_EXAMPLES=OFF -D Trilinos_ENABLE_Kokkos=ON     -D Kokkos_ENABLE_CUDA=${ENABLE_CUDA}     -D Kokkos_ENABLE_HIP=${ENABLE_HIP}     -D Kokkos_ENABLE_OPENMP=${ENABLE_OPENMP}     -D Kokkos_ENABLE_THREADS=OFF     -D Kokkos_ENABLE_SERIAL=ON     -D Kokkos_ARCH_VEGA90A=ON     -D Kokkos_ENABLE_IMPL_VIEW_LEGACY=ON -D Trilinos_ENABLE_Teuchos=ON -D Trilinos_ENABLE_Tpetra=ON     -D Tpetra_INST_CUDA=${ENABLE_CUDA}     -D Tpetra_INST_HIP=${ENABLE_HIP}     -D Tpetra_INST_SYCL=OFF     -D Tpetra_INST_OPENMP=${ENABLE_OPENMP}     -D Tpetra_INST_SERIAL=ON -D Trilinos_ENABLE_Sacado=ON -D Trilinos_ENABLE_Stokhos=ON -D Trilinos_ENABLE_Amesos2=ON -D Trilinos_ENABLE_Ifpack2=ON -D Trilinos_ENABLE_Zoltan2=ON -D Trilinos_ENABLE_MueLu=ON -D Trilinos_ENABLE_Phalanx=ON -D Trilinos_ENABLE_Panzer=ON -D Trilinos_ENABLE_Adelus=ON  ${TRILINOS_DIR}
```

**Comment by MalachiTimothyPhillips** [comment]
@ndellingwood This will be fixed once https://github.com/trilinos/Trilinos/pull/14434 is merged in.

**Comment by MalachiTimothyPhillips** [comment]
> [@ndellingwood](https://github.com/ndellingwood) This will be fixed once [#14434](https://github.com/trilinos/Trilinos/pull/14434) is merged in.

I picked over the MueLu change to https://github.com/trilinos/Trilinos/pull/14444.

**Comment by MalachiTimothyPhillips** [comment]
@ndellingwood I'm going to go ahead and close this since we got #14444 merged. Feel free to reopen if needed.
