### ISSUE TITLE
Panzer, Intrepid2: Compilation errors with cuda/12.4 + gcc/13.2.0

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#13135]
## Bug Report
@trilinos/panzer  @trilinos/intrepid2 

### Description
When testing a Cuda build with cuda/12.4 and gcc/13.2.0 I encountered compilation errors with Panzer, though they refer to Intrepid2 files:

```
FAILED: packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/evaluators/Panzer_Dirichlet_Residual_EdgeBasis.cpp.o
...
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:580:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  580 |   OrientationTools<T>::ortCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:421:205: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  421 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortCoeffData;
      |                                                                                                                                                                                                             ^
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:584:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  584 |   OrientationTools<T>::ortInvCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:422:205: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  422 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortInvCoeffData;
```

### Steps to Reproduce
1. SHA1:  4c2c77595fa7c3c22dd609491e33d6b011692fb9
1. Configure script:  (sems modules)
```bash
export TRILINOS_DIR=<your-path>
export KOKKOS_DIR=$TRILINOS_DIR/packages/kokkos

module load sems-gcc/13.2.0 sems-cuda/12.4.0 sems-openblas/0.3.10 sems-openmpi/4.1.6 sems-cmake sems-ninja
module list
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

export TPETRA_ASSUME_GPU_AWARE_MPI=0

# Configure Trilinos
cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="17" \
 -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_CUDA=ON \
  -DTPL_ENABLE_BLAS:STRING=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:STRING=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
   -DLAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_CUSPARSE:BOOL=ON \
  -DTPL_ENABLE_CUBLAS:BOOL=ON \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_COMPLEX=ON \
 -DTrilinos_ENABLE_OpenMP=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
   -D Kokkos_ENABLE_TESTS=OFF \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Belos=ON \
   -D Belos_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Intrepid2=ON \
   -D Intrepid2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Panzer=ON \
   -D Panzer_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_MueLu=ON \
   -D MueLu_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
  -DTPL_ENABLE_Netcdf=OFF \
  -DTrilinos_ENABLE_ShyLU_NodeTacho=OFF \
  -DTrilinos_ENABLE_SEACAS=OFF \
$TRILINOS_DIR

make -j16
```

**Comment by jhux2** [comment]
@CamelliaDPG I've also hit this error.  I'm using the same gcc and CUDA versions as @ndellingwood.   I tried commenting out https://github.com/trilinos/Trilinos/blob/b895aa6850943911c4b9388249a00a4d372f601e/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp#L545-L551

That results in the error:
```
/projects/sems/install/rhel8-x86_64/sems-compilers/binutils/2.42/gcc/8.3.0/bl7yrdz/bin/ld: packages/panzer/adapters-stk/src/libpanzer-stk.so.16.1.0: undefined reference to `Intrepid2::OrientationTools<Kokkos::Cuda>::ortCoeffData[abi:cxx11]'
/projects/sems/install/rhel8-x86_64/sems-compilers/binutils/2.42/gcc/8.3.0/bl7yrdz/bin/ld: packages/panzer/adapters-stk/src/libpanzer-stk.so.16.1.0: undefined reference to `Intrepid2::OrientationTools<Kokkos::Cuda>::ortInvCoeffData[abi:cxx11]'
collect2: error: ld returned 1 exit status
```

**Comment by mperego** [comment]
@ndellingwood and @jhux2 , I don't understand what the compiler is trying to do. Where are these `__remove_cv`  coming from, e.g., `__remove_cv(int)`? Also, `Panzer_Dirichlet_Residual_EdgeBasis` is not even using `OrientationTools<T>`, it's using `Impl::OrientationTools`.

@jhux2 can you try commenting out the `OrientationTools` entries in `Panzer_Dirichlet_Residual_EdgeBasis_impl.hpp`? If the compile error goes away we can try to re-implent that class without using `OrientationTools`.

**Comment by jhux2** [comment]
@mperego Will do.  Meanwhile, I've found that the compile is successful with `sems-cuda/11.4.2` and  `sems-gcc/8.5.0`.

**Comment by jhux2** [comment]
@mperego Perhaps I don't understand what you're asking for.  I see the error, for example, in this case:

```
/jhu/trilinos/Trilinos-trilinos/packages/panzer/disc-fe/src/Panzer_Interpolation.cpp
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:547:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  547 |   OrientationTools<T>::ortCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:388:222: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  388 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortCoeffData;
      |                                                                                                                                                                                                                              ^
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:551:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  551 |   OrientationTools<T>::ortInvCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:389:222: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  389 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortInvCoeffData;
```

**Comment by mperego** [comment]
OK, thanks. So it's not only triggered by `Panzer_Dirichlet_Residual_EdgeBasis`. B.t.w. are the Intrepid2 tests on? 

What I don't understand from the error is why at line `Intrepid2_OrientationTools.hpp:547`, the compiler add `__remove_cv`:
```
std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > 
```

whereas at line `Intrepid2_OrientationTools.hpp:388` it doesn't have the  `__remove_cv`:
```
std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > 
```

Tomorrow I'm meeting with @rppawlo and @CamelliaDPG  and we can talk about this, unless it gets resolved sooner.

**Comment by jhux2** [comment]
> B.t.w. are the Intrepid2 tests on?

No.  Only MiniEM in Panzer is enabled.

**Comment by CamelliaDPG** [comment]
@mperego I agree those `__remove_cv` things are weird, but I think they will just remove the const prefix from the wrapped type (if any), so that the real difference is between

```
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
```

and

```
std::__cxx11::basic_string<char>
```

Although, those *look* like they should be the same type.  @jhux2 Could you put the code below somewhere (maybe above the OrientationTools class declaration) and see if it compiles with gcc 13.2.0 and cuda 12.4?

```
template<typename U, typename V>
constexpr bool same = std::is_same_v<U, V>;

using type1 = std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >;
using type2 = std::__cxx11::basic_string<char>;

static_assert(same<type1,type2>, "type1 and type2 should match!");
```

**Comment by jhux2** [comment]
@CamelliaDPG So here, for example?

https://github.com/trilinos/Trilinos/blob/b895aa6850943911c4b9388249a00a4d372f601e/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp#L72

**Comment by CamelliaDPG** [comment]
@jhux2 Yes, please.  (I modified the code in my comment, btw, to add some additional asserts.)

**Comment by jhux2** [comment]
After adding the code, I still see the same error.
```
es/panzer-disc-fe.dir/Panzer_Interpolation.cpp.o -c /ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/panzer/disc-fe/src/Panzer_Interpolation.cpp
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:554:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  554 |   OrientationTools<T>::ortCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:395:222: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  395 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortCoeffData;
      |                                                                                                                                                                                                                              ^
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:558:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  558 |   OrientationTools<T>::ortInvCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/ascldap/users/jhu/trilinos/Trilinos-trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:396:222: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  396 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortInvCoeffData;
      |                                                                                                                                                                                                                              ^
```

**Comment by CamelliaDPG** [comment]
@jhux2 But you don't see any errors coming from the static_assert lines?

If not, could you add these lines after the previous static asserts?

```
using map1 = std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> >;
using map2 = std::map<std::pair<string3, int2>, Kokkos::View<double****, DeviceType> >;
using map3 = std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> >;

static_assert(same<map1,map2>, "map1 and map2 should match!");
static_assert(same<map1,map3>, "map1 and map3 should match!");
```

I'll be interested to know whether either of those static asserts fail.  If neither does, then the compiler appears to be inconsistent about whether it thinks those map types are the same: the error you quoted is saying that the `map1` type does not match the `map3` type.  (The earlier static asserts I asked you to add were for the key and value types for those maps.)

**Comment by ndellingwood** [comment]
@csiefer2 I'm not certain, this was a newer version of cuda/12 I was able to test with around the time I opened the issue. I'll need to retest to see if this is still present (and test more cuda/12.x versions as well)

**Comment by mperego** [comment]
PR #13973, should fix this.
@CamelliaDPG I tried checking the maps with your code snippet and the maps are equivalent. I think the compiler gets confused. Adding a typedef seems to fix the issue.
