### PR TITLE
EpetraExt: Add guards around the HDF5 tests

### LINKED ISSUE #3484: EpetraExt cuda-9.2 build on white/ride broken starting 9/6/2018
CC: @trilinos/epetraext, @kddevin (Trilinos Data Services Product Lead), @Sbte, @mhoemmen 

## Next Action Status

Caused by PR #3381 merged by the trilinos-autotester 9/5/2018?  Next: Fix the failure?

## Description

As shown in [this CDash query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-debug-pt&field2=site&compare2=61&value2=white&field3=buildstarttime&compare3=84&value3=now), the build of EpetraExt was broken in the build `Trilinos-atdm-white-ride-cuda-9.2-debug-pt` (that we are trying to get cleaned for a possible Trilinos PR build).

The build error occurs when building `packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp`  and and shows, shown for example [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?onlydeltap&buildid=3909274):

```
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(64): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(71): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(89): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(93): error: identifier "H5T_NATIVE_INT" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(96): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(115): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(124): error: identifier "HDF5" is undefined  7 errors detected in the compilation of "/tmp/tmpxft_0001e190_00000000-6_EpetraExt_HDF5_UnitTest.cpp1.ii".
```

Looking at the new commits pulled that day at:

* https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=3909266#!#note6

shows the the likely commits causing this are:

```
aec9db9:  EpetraExt: Add missing const to HDF5 Write method
Author: Sven Baars <s.baars@rug.nl>
Date:   Mon Sep 3 12:56:20 2018 +0200

M	packages/epetraext/src/inout/EpetraExt_HDF5.cpp
M	packages/epetraext/src/inout/EpetraExt_HDF5.h
M	packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp

fac4dbe:  EpetraExt: Recursively check for existing HDF5 groups
Author: Sven Baars <s.baars@rug.nl>
Date:   Mon Sep 3 09:55:22 2018 +0200

M	packages/epetraext/src/inout/EpetraExt_HDF5.cpp
M	packages/epetraext/src/inout/EpetraExt_HDF5.h
M	packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp

23fa92e:  EpetraExt: Add HDF5 test file
Author: Sven Baars <s.baars@rug.nl>
Date:   Tue Sep 4 10:15:18 2018 +0200

M	packages/epetraext/test/inout/CMakeLists.txt
A	packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp
```

from the PR #3381 approved by @mhoemmen and merged by the trilinos-autotester on 9/5/2018.

## Steps to Reproduce

One can reproduce this build failure on 'white' or 'ride' by cloning the Trilinos GitHub repo, checking out the 'develop' branch and then setting up a build build directory and doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvSettings.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_EpetraExt=ON \
  $TRILINOS_DIR

$ make NP=16
```

### PR DESCRIPTION
**Pull request by Sbte**
@trilinos/EpetraExt

## Description
Add guards around the HDF5 tests to hopefully fix #3484 

## Related Issues

Closes #3484

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
oops, sorry! closed by mistake

File: packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp [hunk 1]
```diff
@@ -51,6 +51,8 @@
 
 #include "EpetraExt_HDF5.h"
 
+#ifdef HAVE_EPETRAEXT_HDF5
```
[the remark this answers is not in the document]
Comment (Sbte) [reply packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp]: I did that to obtain the definition of `HAVE_EPETRAEXT_HDF5`

[the remark this answers is not in the document]
Comment (mhoemmen) [reply packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp]: @Sbte You can and should get that macro from `#include "EpetraExt_ConfigDefs.h"`.

**Comment by Sbte** [comment]
@mhoemmen I looked at how this was done in the rest of EpetraExt, and it seemed to me that this was the way to go. Look for instance at `EpetraExt_HDF5.cpp`. I personally also think that it would be better to do this on the CMake side, but I was unsure if these variables are actually available.

**Comment by mhoemmen** [comment]
@Sbte I'm looking at `epetraext/CMakeLists.txt` right now -- I notice that the `${PACKAGE_NAME}_USING_HDF5` CMake option is what controls the `HAVE_EPETRAEXT_HDF5` macro.  Just use that CMake option to protect the test.  You can even check right before the test whether the option exists:
```
ASSERT_DEFINED(${PACKAGE_NAME}_USING_HDF5)
```

**Comment by Sbte** [comment]
@mhoemmen I changed it to use that instead. Thanks for the help!

**Comment by bartlettroscoe** [comment]
Shoot, I did not know about this PR when I created PR #3522.  Either PR is acceptable.  I guess it is a race to see which PR finishes PR testing first and merges.

**Comment by Sbte** [comment]
The other PR has been merged.
