### PR TITLE
Tpetra WrappedDualView: Don't use deprecated direct access to DualView members

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/tpetra 

## Motivation
#14722

### CODE REVIEW

**Comment by ndellingwood** [comment]
This should fix issues showing up in our nightly integration builds with kokkos@5.0, the breakage occurs with `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`,

```
/root/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp(625): error: member "Kokkos::DualView<DataType, Properties...>::h_view [with DataType=double **, Properties=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>>]" (declared at line 224 of /root/Trilinos/kokkos/containers/src/Kokkos_DualView.hpp) is inaccessible
          return dualView.h_view.data() != dualView.d_view.data();
```

See https://github.com/kokkos/kokkos/pull/7716 for the relevant deprecation
