### ISSUE TITLE
Question, should kokkos_develop branch build with cuda9.1?

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2192]
I am trying to build with cuda 9.1 and I'm seeing errors with the kokkos-develop branch.  Should this work?  Should I post issues when it doesn't?

Matt

**Comment by mhoemmen** [comment]
@bathmatt don't leave us hanging; post the errors at least ;-)

**Comment by bathmatt** [comment]
It's these type of errors, it's been hashed several times in the past.  I'm just curious if this branch is maintained and usable.

```
/remote/mbetten/Trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp:325:130: error: expansion pattern ‘Kokkos::LayoutStride’ contains no argument packs
/remote/mbetten/Trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp:325:148: error: expansion pattern ‘ExecSpaceType’ contains no argument packs
/remote/mbetten/Trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp:325:151: error: template argument 2 is invalid
```
