### ISSUE TITLE
Intrepid2 and Panzer build errors in new cuda-10.1 builds on 'white'

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4963]
CC: @trilinos/intrepid2, @trilinos/panzer @mperego  (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown [here on CDash](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4917892), there are many build failures in Intrepid2 and Panzer shown in the new  build:

* `Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug`

that as been set up on 'white' (see [TRIL-245](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-245)).

This starts with build errors in Intrepid2 as shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?buildid=4917897) that look like:

```
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug/SRC_AND_BUILD/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_In_FEMDef.hpp:451:64: error: invalid conversion from ‘Intrepid2::ordinal_type* {aka int*}’ to ‘Intrepid2::ordinal_type {aka int}’ [-fpermissive]
         tags[i_card+1][0] = 2; // face dof
```

The build errors in Panzer look to be these same errors coming from Intrepid2.

## Current Status on CDash

* [Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug Intrepid2 build summary last 5 days](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-04-19&filtercount=3&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=Intrepid2&field2=buildname&compare2=61&value2=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field3=buildstarttime&compare3=83&value3=5%20days%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'white' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'white' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands on 'white' to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
CC: @nmhamster, @micahahoward, @bathmatt 

@trilinos/intrepid2, @trilinos/panzer, @mperego (Trilinos Discretzation Product Area Lead)

It seems that CUDA 10.1 is going to become the default build on ATS-2 systems soon (they are setting up support for cuda-10.1 right how on 'sierra' and clones at LLNL right now).

In particular @micahahoward (SPARC PI) expressed in [TRIL-245](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-245?focusedCommentId=26693&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26693):

> The sooner we get Trilinos builds with 10.1 to Waterman or better yet Vortex, the better.

The only CUDA 10.1 env we have access to right now is this one on 'white' (not yet syned to 'ride') so it would seem a high priority to get issues with CUDA 10.0 worked out soon.

**Comment by bathmatt** [comment]
Here is a fix for the compiler bug that is causing the intrepid bug.

```
/g/g20/mbetten/work/build/Trilinos.new/packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_In_FEMDef.hpp:451:64: error: invalid conversion from 'Intrepid2::ordinal_type* {aka int*}' to 'Intrepid2::ordinal_type {aka int}' [-fpermissive] /g/g20/mbetten/work/build/Trilinos.new/packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_In_FEMDef.hpp:451:64: error: invalid conversion from 'Intrepid2::ordinal_type* {aka int*}' to 'Intrepid2::ordinal_type {aka int}' [-fpermissive] 


        tags[i_card][0] = 2; // face dof
        tags[i_card][1] = i; // face id
        tags[i_card][2] = 2*j; // local face id
        tags[i_card][3] = 2*numPtsPerFace; // total face dof
        const ordinal_type i_c=i_card+1;  // create a temp and the code compiles because nvcc gets confused too easily 
        tags[i_c][0] = 2; // face dof
        tags[i_c][1] = i; // face id
        tags[i_c][2] = 2*j+1; // local face id
        tags[i_c][3] = 2*numPtsPerFace; // total face dof


```

**Comment by bathmatt** [comment]
@nmhamster this is that stupid nvcc compiler bug I told you about a couple of days ago.

**Comment by mperego** [comment]
@bathmatt Thanks. OK, I'll submit a PR.

**Comment by bartlettroscoe** [comment]
With the merge of PR #5004, these build errors have gone away today as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4945222).  Now we just have failing tests that we need to address.  Those will be covered in other issues.

Thanks for finish this @mperego!

Closing as compete.
