### ISSUE TITLE
 Amesos2 test file amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp build failure for ATDM Trilinos CUDA 9.0 builds on 'hansen/'shiller'

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2866]
CC: @trilinos/amesos2 (Package Team), @srajama1 (Product Lead), @fryeguy52 

## Description

As shown in the query:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-05-31&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-hansen-shiller-cuda-9.0-&field2=subprojects&compare2=93&value2=Amesos2&field3=buildstarttime&compare3=84&value3=2018-06-02

the Amesos2 has had a single build failure in both of the CUDA 9.0 builds on 'hansen'/'shiller':

* `Trilinos-atdm-hansen-shiller-cuda-9.0-debug`
* `Trilinos-atdm-hansen-shiller-cuda-9.0-opt`

since this CUDA 9.0 build was first set up (see #2706).

The build failure is for the file `packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp` and is shown, for example, at:

* https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3564003

and shows:

```
/home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-9.0-debug/SRC_AND_BUILD/Trilinos/packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp(106): error: member "<unnamed>::test_traits<Scalar>::test_mat [with Scalar=double]" was referenced but not defined

1 error detected in the compilation of "/tmp/tmpxft_00007af7_00000000-4_Tpetra_CrsMatrix_Adapter_UnitTests.cpp4.ii".
```

This results in the "Not Run" test `Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4` as shown, for example, at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlynotrun&buildid=3564003

The only other failures in these CUDA 9.0 builds are failures do to the Kokos update described in #2728 which also impact the CUDA 8.0 builds.  I fully expect those to go away once those issues are fixed in #2728.

## Steps to Reproduce

Following the instructions in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#shillerhansen

which is linked to from:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos

one should be able to figure out how to reproduce this.

But to be specific, the exact instructions to reproduce this build failure are:

1. Log onto 'hansen' (SON) or 'shiller' (SON)

2. Clone the Trilinos repo (pointed to by `$TRILINOS_DIR` below) and get on the 'develop' branch

3. Create `<some_build_dir>` and do:

    ```
    $ cd <some_build_dir>/

    $ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.0-opt

    $ cmake \
      -GNinja \
      -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
      -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Amesos2=ON \
      $TRILINOS_DIR
    
    $ make NP=16
    ```

That should reproduce the build error.

**Comment by bartlettroscoe** [comment]
@trilinos/amesos2, this looks pretty easy to fix. But in case it can't be fixed in a reasonable amount of time, we can disable the build and running of this one test for just these CUDA 9.0 builds (and for no other builds) in the ATDM Trilinos configuration files (using the disable vars described [here](https://trilinos.org/docs/files/TrilinosBuildReference.html#id58) and [here](https://trilinos.org/docs/files/TrilinosBuildReference.html#id57)).

But no sense in disabling the build of this one test until the other errors related to #2827 are fixed.  I just wanted to get this issue on the board so that the Amesos2 team has time to get this build error fixed.

**Comment by crtrott** [comment]
Note: one potential problem here is the use of something in an anonymous namespace (`<unnamed>::test_traits<Scalar>::test_mat`). CUDA doesn't like that in some cases.

**Comment by ndellingwood** [comment]
I'll get a build going and take a look at this, hopefully moving the static variable definitions within the struct and making them `constexpr` will suffice.

**Comment by bartlettroscoe** [comment]
@ndellingwood, shoot, there was a copy-and-paste error in the Steps to Reproduce".   The correct build is `cuda-9.0-opt` **not** `intel-opt-openmp` (I have corrected it now).    Can you try it with `load-env.sh cuda-9.0-opt`?

**Comment by ndellingwood** [comment]
@bartlettroscoe thanks for update, rebuilding now.

**Comment by ndellingwood** [comment]
PR #2876 issued with a fix, verified that Trilinos compiles with the reproducer instructions provided in the issue.

**Comment by ndellingwood** [comment]
Issue was resolved by moving the the `test_traits` out of the anonymous namespace and into a named namespace, as @crtrott pointed out Cuda does not seem to like the previous impl.

**Comment by bartlettroscoe** [comment]
The build failure was gone in the CUDA 9.0 builds on 'hansen' today as shown, for example, at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3582389

Note the "-1" subscript by the "0" number of build errors and "Not Run" tests and the "+1" superscript by the "6" passing tests.

Closing as complete.

Thanks @ndellingwood !
