### ISSUE TITLE
MueLu: link error when building Albany with gcc-9.2.1 + OpenMP KokkosNode

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5879]
We're seeing a MueLu/Xpetra-related link error in the Albany KokkosNode = OpenMP nightlies on my workstation which uses gcc-9.2.1.  Here is the error: 

```
[100%] Linking CXX executable Albany
/usr/bin/ld: /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-openmp/install/lib/libmuelu-interface.a(MueLu_ParameterListInterpreter.cpp.o): in function `Xpetra::ImportFactory >::Build(Teuchos::RCP > const> const&, Teuchos::RCP > const> const&, Teuchos::RCP const&)':

MueLu_ParameterListInterpreter.cpp:(.text._ZN6Xpetra13ImportFactoryIiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE5BuildERKN7Teuchos3RCPIKNS_3MapIiiS6_EEEESF_RKNS9_INS8_13ParameterListEEE[_ZN6Xpetra13ImportFactoryIiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE5BuildERKN7Teuchos3RCPIKNS_3MapIiiS6_EEEESF_RKNS9_INS8_13ParameterListEEE]+0x3ca): undefined reference to `Xpetra::TpetraImport >::TpetraImport(Teuchos::RCP > const> const&, Teuchos::RCP > const> const&, Teuchos::RCP const&)'

/usr/bin/ld: /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-openmp/install/lib/libmuelu.a(MueLu_CloneRepartitionInterface.cpp.o):
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=88789

I suspect it may be related to adding the following configure option yesterday ```-D Epetra_ENABLE_OpenMP:BOOL=OFF``` which was needed to get Trilinos to compile with gcc-9.2.1.  

@trilinos/muelu 
@trilinos/xpetra

**Comment by brian-kelley** [comment]
@ikalash A permanent fix for #5390 was merged to develop a few minutes ago, so if you pull from develop now you should be able to build either with or without OpenMP.

**Comment by ikalash** [comment]
Thanks @brian-kelley !

**Comment by cgcgcg** [comment]
Closing. If this is still an issue, please reopen.
