### ISSUE TITLE
Ifpack2 build error on darwin: Clang, SERIAL_RELEASE

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#726]
(@mhoemmen) On darwin (clang compiler, other TPLS installed via homebrew), using the checkin-test.py script to configure/build/test, I get the following error for the SERIAL_RELEASE build (the MPI_DEBUG build is fine):

[ 99%] Building CXX object packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_Issue234.dir/Ifpack2_UnitTest234.cpp.o
[ 99%] Linking CXX executable Ifpack2_ContainerFactory.exe
Undefined symbols for architecture x86_64:
  "Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::LocalSparseTriangularSolver(Teuchos::RCP<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Ifpack2::ILUT<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::compute() in Ifpack2_UnitTestContainerFactory.cpp.o
  "Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::LocalSparseTriangularSolver(Teuchos::RCP<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Ifpack2::ILUT<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::compute() in Ifpack2_UnitTestContainerFactory.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [packages/ifpack2/test/unit_tests/Ifpack2_ContainerFactory.exe] Error 1
make[1]: **\* [packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_ContainerFactory.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 99%] Building CXX object packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_Issue234.dir/**/**/__/teuchos/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
[ 99%] Linking CXX executable Ifpack2_AdditiveSchwarz.exe
[ 99%] Built target Ifpack2_AdditiveSchwarz
1 warning generated.
[ 99%] Linking CXX executable Ifpack2_LocalSparseTriangularSolver.exe
[ 99%] Built target Ifpack2_LocalSparseTriangularSolver
[ 99%] Linking CXX executable Ifpack2_Issue234.exe
[ 99%] Built target Ifpack2_Issue234
make: **\* [all] Error 2

Attached is the concatenation of the the do-configure.base and do-configure scripts generated by checkin-test.py

[configure.txt](https://github.com/trilinos/Trilinos/files/545647/configure.txt)

Other relevant information:
System: Apple Mac OSX 10.11.6
Compiler family: Apple clang
Branch: develop (fresh checkout)
Build: SERIAL_RELEASE

**Comment by tjfulle** [comment]
@mhoemmen, using the gcc compilers (identical configuration as above) configure/build/test passes

**Comment by mhoemmen** [comment]
Could you try one thing for me?  Just do the same Clang build as before, but enable explicit template instantiation, by adding the following option:

Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON

Thanks!  Most of us test with this option ON, since it makes building tests and examples a lot faster.  However, it is possible to get subtle bugs like this if one only ever tests with ETI ON.

**Comment by tjfulle** [comment]
Same error with Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON:

```sh
[ 99%] Linking CXX executable Ifpack2_ContainerFactory.exe
Undefined symbols for architecture x86_64:
  "Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::LocalSparseTriangularSolver(Teuchos::RCP<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Ifpack2::ILUT<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::compute() in Ifpack2_UnitTestContainerFactory.cpp.o
  "Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::LocalSparseTriangularSolver(Teuchos::RCP<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Ifpack2::ILUT<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::compute() in Ifpack2_UnitTestContainerFactory.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/ifpack2/test/unit_tests/Ifpack2_ContainerFactory.exe] Error 1
make[1]: *** [packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_ContainerFactory.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_RILUKSingleProcessUnitTests.dir/__/__/__/teuchos/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
```

**Comment by mhoemmen** [comment]
@tjfulle Thanks for the update!  (Sorry, the Trilinos Users' Group meeting has been eating all my time over the past couple days.)

**Comment by jhux2** [comment]
@tjfulle You might try rerunning your configure to see if cmake is printing warning or informational messages. For example, this message really helped me recently to resolve undefined symbols:
```
NOTE: Kokkos::Serial is ON (the CMake option Kokkos_ENABLE_Serial is ON), but the corresponding Tpetra Node type is disabled.  If you want to enable instantiation and use of Kokkos::Serial in Tpetra, please also set the CMake option Tpetra_INST_SERIAL:BOOL=ON.  If you use the Kokkos::Serial Node type in Tpetra without doing this, you will get link errors!
```
Btw, I doubt the content of this exact message is the root of your build problem.

**Comment by jhux2** [comment]
@trilinos/ifpack2

**Comment by mhoemmen** [comment]
I'm trying out the build (Clang 3.5, MacOS X) now.

**Comment by mhoemmen** [comment]
Fresh checkout with Clang 3.5, SERIAL_RELEASE, on Mac builds just fine for me.  Please feel free to reopen if this is still an issue :)  Thanks!

**Comment by tjfulle** [comment]
@mhoemmen, could you post/send your configuration?  A fresh checkout with Clang 3.9, MacOS X, running `checkin-script.py --local-do-all` still fails with the same error for me.  I have not defined any options except those that are standard in the checkin script.  The only warning in configure.out are:

```sh
*** Warning: Setting Trilinos_ENABLE_ForTrilinos=OFF because Trilinos_ENABLE_Fortran=OFF!
-- WARNING: Not Setting Trilinos_ENABLE_Zoltan2=ON even though Ifpack2 has an optional dependence on Zoltan2 because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- WARNING: Not Setting Trilinos_ENABLE_Amesos2=ON even though Ifpack2 has an optional dependence on Amesos2 because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- WARNING: Not Setting Trilinos_ENABLE_Amesos2=ON even though Ifpack2 has an optional dependence on Amesos2 because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
--   WARNING:  Setting ML_ENABLE_Zoltan=OFF since ML_ENABLE_MPI=OFF!
```

Again, the error is:

```sh
[ 99%] Linking CXX executable Ifpack2_ContainerFactory.exe
Undefined symbols for architecture x86_64:
  "Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::LocalSparseTriangularSolver(Teuchos::RCP<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Ifpack2::ILUT<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::compute() in Ifpack2_UnitTestContainerFactory.cpp.o
  "Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::LocalSparseTriangularSolver(Teuchos::RCP<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Ifpack2::ILUT<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::compute() in Ifpack2_UnitTestContainerFactory.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/ifpack2/test/unit_tests/Ifpack2_ContainerFactory.exe] Error 1
make[1]: *** [packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_ContainerFactory.dir/all] Error 2
```

**Comment by mhoemmen** [comment]
Sorry for missing this one!  Here is my Clang 3.5 configuration:
```
-D Trilinos_ENABLE_Fortran:BOOL=OFF
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-D TPL_ENABLE_Cholmod:BOOL=ON
  -D Cholmod_INCLUDE_DIRS:FILEPATH="$HOME/pkg/SuiteSparse-4.2.1/include"
  -D Cholmod_LIBRARY_DIRS:FILEPATH="$HOME/pkg/SuiteSparse-4.2.1/lib"
-D TPL_ENABLE_SuperLU:BOOL=ON
  -D SuperLU_INCLUDE_DIRS:FILEPATH="$HOME/pkg/superlu-4.3-clang-3.2/include"
  -D SuperLU_LIBRARY_DIRS:FILEPATH="$HOME/pkg/superlu-4.3-clang-3.2/lib"
-D TPL_ENABLE_Boost:BOOL=OFF
-D TPL_ENABLE_BoostLib:BOOL=OFF
-D TPL_ENABLE_SWIG:BOOL=OFF
-D CMAKE_CXX_FLAGS:STRING="-Wall --pedantic"
-D BUILD_SHARED_LIBS:BOOL=ON
-D CMAKE_BUILD_TYPE:STRING=DEBUG
-D Kokkos_ENABLE_DEBUG:BOOL=ON
-D Teuchos_ENABLE_DEBUG:BOOL=ON
-D TPL_ENABLE_MPI:BOOL=ON
  -D MPI_BASE_DIR:FILEPATH="$HOME/pkg/openmpi-1.10.2-clang-3.5"
  -D MPI_EXEC:FILEPATH="$HOME/pkg/openmpi-1.10.2-clang-3.5/bin/mpiexec"
  -D MPI_CXX_COMPILER:FILEPATH="$HOME/pkg/openmpi-1.10.2-clang-3.5/bin/mpicxx"
  -D MPI_C_COMPILER:FILEPATH="$HOME/pkg/openmpi-1.10.2-clang-3.5/bin/mpicc"
```

**Comment by mhoemmen** [comment]
I also build with Clang 3.9 on Linux, and that works just fine.  My TPL enables in the above configuration should not affect `Ifpack2::LocalSparseTriangularSolver` (yet).
