### PR TITLE
Intrepid2: fix seg-fault related to structured integration

### PR DESCRIPTION
**Pull request by mperego**
Intrepid2: Reduce container overhead for Data, TensorData, VectorData, BasisValues, and TransformedBasisValues.

We achieve this by adopting a std::variant type for storage of the underlying fixed-rank View in Data, and by reducing the maximum number of families supported by VectorData (from 7 to 3).

With Kokkos 5 (which adds somewhat to the overhead associated with Views, due to its use of 64-bit indices), the overhead costs were as follows (in bytes):
```
Data:                   616
TensorData:             4552
VectorData:             223184
BasisValues:            255088
TransformedBasisValues: 255720
```

With the present changes, these reduce to:
```
Data:                   312
TensorData:             2424
VectorData:             51040
BasisValues:            68048
TransformedBasisValues: 68376
```

@trilinos/intrepid2 

## Motivation
With Kokkos 5.0, under some builds, tests would fail with a seg fault traceable to a stack overflow, due to the stack allocation costs of these containers in Intrepid2's `integrate()` method in particular.  These changes not only resolve the immediate issue, but also make similar issues much less likely in the future, and may marginally improve performance as well.

### CODE REVIEW

**Comment by crtrott** [comment]
Is this inside a member function of a class? If so you might be capturing a class member that in optimized build is optimized away. This should likely have used KOKKOS_CLASS_LAMBDA.

**Comment by mperego** [comment]
> Is this inside a member function of a class? If so you might be capturing a class member that in optimized build is optimized away. This should likely have used KOKKOS_CLASS_LAMBDA.

It's a static function member, so it looks like I cannot use KOKKOS_CLASS_LAMBDA.

**Comment by mperego** [comment]
@CamelliaDPG Unfortunately one of the CUDA builds failed. It seems there is an issue with `TransformedBasisValues` objects. 
In a CUDA build on blake (gcc/12.2.0, cuda/12.0.0), I got an error compiling 
https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/unit-test/MonolithicExecutable/StructuredIntegrationTests_Utils.hpp#L153
I replaced the KOKKOS_LAMBDA function with a functor and it gives a `Invalid memory reference` compilation error due to accessing the `TransformedBasisValues` objects in the functor operator() body. 
Another clue is that, even in a serial build, when linking Kokkos develop I had to pass the _reference_ of `TransformedBasisValues` objects to the functor added in this PR, otherwise I would get a seg-fault. 
I'm off for a long weekend and I won't be able to work on this further for a while.

**Comment by CamelliaDPG** [comment]
Marked issue as WIP while I try to distill the issue down.

**Comment by CamelliaDPG** [comment]
I finally have clarity on what's happening here.  It's a stack overflow.  Several of Intrepid2's containers are pretty sizeable to begin with, and their sizes depend on the sizes of Kokkos Views.  Kokkos 5 increases somewhat the sizes of Views.  In `integrate()` in particular, we have a bunch of stuff in the local stack frame; probably the compiler is able to optimize some of this away in optimized builds because of mutually exclusive branches.  But in an unoptimized build, it won't do that.  So prior to Kokkos 5 we were already getting close to stack size limits, and the changes in Kokkos 5 put us over the edge.

Here's summary size information for the key Kokkos and Intrepid2 types, with Kokkos 4.x:
```
Sizes (in bytes):
View (rank 1): 24
View (rank 2): 40
View (rank 3): 40
View (rank 4): 40
View (rank 5): 48
View (rank 6): 48
View (rank 7): 56
DynRankView:   64
Array<int,7>:  28

Data:                   496
TensorData:             3712
VectorData:             182024
BasisValues:            208040
TransformedBasisValues: 208552
```

And here they are with Kokkos 5:
```
Sizes (in bytes):
View (rank 1): 32
View (rank 2): 40
View (rank 3): 48
View (rank 4): 56
View (rank 5): 64
View (rank 6): 72
View (rank 7): 80
DynRankView:   88
Array<int,7>:  28

Data:                   616
TensorData:             4552
VectorData:             223184
BasisValues:            255088
TransformedBasisValues: 255720
```

So the overall stack storage cost of each of the Intrepid2 containers has gone up about 25% with Kokkos 5.  I can tweak the code in `integrate()` to get us under the stack limit (at least in the test that I'm focused on), but a fuller solution will pull down the costs of our Intrepid2 types further; it's better not to be so close to the stack limit.  We could also try to move some of the allocations onto the heap, though that would add complexity with regard to device vs host data residence, I think.

Anyway, I have a couple ideas for modifying `Data` to reduce its size; since the cost of the others is roughly proportional to the cost of `Data`, that will help us across the board, if successful.  We can also adjust policies in `Parameters` to reduce some of our maximum allowable sizes in `VectorData` in particular, which is the biggest contributor to `BasisValues` and `TransformedBasisValues`.

**Comment by CamelliaDPG** [comment]
I've made two changes, which affect the sizes of Data and VectorData directly:
1. In Data, switched from storing empty Views of various ranks, alongside one active View, to using a std::variant<> instance to basically overlap the memory requirement (so the cost is a maximum of the possible sizes, rather than a sum of them).
2. Made the outer size of the vector components container correspond to a new parameter, MaxBasisFamilies, which I set to 3, rather than MaxTensorComponents, which is 7.

With those two changes, here are the new Intrepid2 sizes:

```
Data:                   312
TensorData:             2424
VectorData:             51040
BasisValues:            68048
TransformedBasisValues: 68376
```

I've only really run one test so far.  But this did pass on my local machine (serial, debug).

**Review by mperego — COMMENTED** [review]
@CamelliaDPG, your changes look good to me. Thanks!
