### ISSUE TITLE
Trilinos failing to compile on Summit (gcc 10.2.0 cuda 11.3.1)

### ISSUE THREAD

**Issue by PaulMullowney** [trilinos/Trilinos#10113]
SHA: dd53a1e0f
Using gcc/10.2.0 and cuda/11.3.1

[ 80%] Building CXX object packages/stk/stk_expreval/stk_expreval/CMakeFiles/stk_expreval.dir/Function.cpp.o
/gpfs/alpine/cfd116/scratch/mullowne/Trilinos/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h: In instantiation of 'const std::vector<double>& Iotm::text_mesh::Coordinates<EntityId, Topology>::operator[](EntityId) const [with EntityId = long int; Topology = Iotm::TopologyMapEntry]':
/gpfs/alpine/cfd116/scratch/mullowne/Trilinos/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.C:370:59:   required from here
/gpfs/alpine/cfd116/scratch/mullowne/Trilinos/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h:567:13: error: '__T0' was not declared in this scope; did you mean '__y0'?
  567 |         auto it(m_nodalCoords.find(nodeId));
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         __y0

Has anyone seen this before?
-Paul

**Comment by alanw0** [comment]
This build output seems to be a little garbled, as stk_expreval doesn't include nor have anything to do with Iotm_TextMeshUtils.h.
However, perhaps @tokusanya can take a look at the TextMesh issue.

**Comment by jhux2** [comment]
@PaulMullowney I'm able to compile Trilinos develop https://github.com/trilinos/Trilinos/commit/a5a5bf9a6f118b6bfc886e697e6c1a10c355b68f (with the patch https://github.com/kokkos/kokkos/pull/4673 applied) on Summit with gcc 10.2.0 and CUDA 11.3.1.

**Comment by PaulMullowney** [comment]
With a serial build:

[ 31%] Building CXX object packages/seacas/libraries/ioss/src/text_mesh/CMakeFiles/Iotm.dir/Iotm_TextMesh.C.o
/gpfs/alpine/cfd116/scratch/mullowne/Trilinos/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h: In instantiation of 'const std::vector<double>& Iotm::text_mesh::Coordinates<EntityId, Topology>::operator[](EntityId) const [with EntityId = long int; Topology = Iotm::TopologyMapEntry]':
/gpfs/alpine/cfd116/scratch/mullowne/Trilinos/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.C:370:59:   required from here
/gpfs/alpine/cfd116/scratch/mullowne/Trilinos/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h:567:13: error: '__T0' was not declared in this scope; did you mean '__y0'?
  567 |         auto it(m_nodalCoords.find(nodeId));
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         __y0

**Comment by PaulMullowney** [comment]
@jhux2 I'll try that commit

**Comment by PaulMullowney** [comment]
That commit doesn't build for me with gcc 10.2.0. Same error. SHA dd53a1e, which is more recent, builds with 9.3.0.
@jhux2 Can you send me your cmake line? I'm using exawind-builder to configure/build.

**Comment by PaulMullowney** [comment]
I can build with gcc 10.2.0 and cuda 11.1.1, but not 11.3.1

**Comment by cgcgcg** [comment]
I just saw a similar error on my workstation. The way I got past it was to change
```
auto it(m_nodalCoords.find(nodeId));
```
to
```
auto it = m_nodalCoords.find(nodeId);
```
No idea why that makes a difference.

**Comment by PaulMullowney** [comment]
Is this change going to be pushed to develop?

**Comment by cgcgcg** [comment]
@PaulMullowney No, I only saw a similar issue in a completely different spot. My (implied) suggestion was to make that change in STK and see if that fixes anything (and it might not do anything at all).

**Comment by PaulMullowney** [comment]
@cgcgcg Got it. I'll try building again and see if this resolves the issue. Thanks.

**Comment by PaulMullowney** [comment]
diff --git a/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h b/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h
index b1d45099b7f..3ce41531e52 100644
--- a/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h
+++ b/packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h
@@ -318,7 +318,8 @@ namespace Iotm {

       const std::vector<double> &operator[](const EntityId nodeId) const
       {
-        auto it(m_nodalCoords.find(nodeId));
+        auto it = m_nodalCoords.find(nodeId);

         if (it == m_nodalCoords.end()) {
           std::ostringstream errmsg;
diff --git a/packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h b/packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h
index b996649c9ea..7249e7d8f4a 100644
--- a/packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h
+++ b/packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h
@@ -795,7 +795,8 @@ namespace Iotm {

         const std::vector<double> &operator[](const EntityId nodeId) const
         {
-          auto it(m_nodalCoords.find(nodeId));
+          auto it = m_nodalCoords.find(nodeId);
           return it->second;
         }

Trilinos builds on summit with gcc 10.2 and cuda 11.4.2 with the following changes:

diff --git a/packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshUtils.hpp b/packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshUtils.hpp
index 896abddef4d..cac47e797d4 100644
--- a/packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshUtils.hpp
+++ b/packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshUtils.hpp
@@ -304,7 +304,8 @@ class Coordinates

   const std::vector<double> &operator[](const EntityId nodeId) const
   {
-    auto it(m_nodalCoords.find(nodeId));
+    auto it = m_nodalCoords.find(nodeId);

**Comment by jhux2** [comment]
@PaulMullowney Can you post a PR or send the changes to me to put in one?

**Comment by PaulMullowney** [comment]
@jhux2 I sent you the changes in a slack message.

**Comment by alanw0** [comment]
@PaulMullowney Is the change in this github issue the only change for stk? We'll get it put into the develop branch.

**Comment by alanw0** [comment]
@tokusanya Please see the above changes, one in stk two in seacas. It looks like this iterator needs to be assigned rather than parenthesis-initialized for some reason on certain compiler(s).

**Comment by PaulMullowney** [comment]
Cuda is the issue here, not gcc.

**Comment by jhux2** [comment]
@alanw0 @gsjaardema I summited a PR before I noticed this issue had been updated.   If you'd prefer to handle the changes another way, please let me know.

**Comment by jhux2** [comment]
@PaulMullowney Your suggested fixes in #10290 have merged to develop.

**Comment by PaulMullowney** [comment]
Excellent. Thanks!
