### ISSUE TITLE
MueLu:  Compilation error with cuda/10.1.105, various cusparse variables undefined in MatvecKernelDriver.cpp

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#10243]
## Bug Report
@trilinos/muelu 

### Description
Compilation errors in MueLu's MatvecKernelDriver.cpp in Cuda builds on Weaver with cuda/10.1.105, error snip:

```
[ 96%] Building CXX object packages/muelu/test/unit_tests/CMakeFiles/MueLu_UnitTests_Blocked.dir/MueLu_UnitTests.cpp.o
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(393): error: identifier "cusparseDnVecDescr_t" is undefined

Scanning dependencies of target MueLu_UnitTests_kokkos
[ 96%] Building CXX object packages/muelu/test/unit_tests_kokkos/CMakeFiles/MueLu_UnitTests_kokkos.dir/Aggregates_kokkos.cpp.o
[ 96%] Linking CXX executable MueLu_KokkosKernels.exe
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(339): error: identifier "cusparseCreateCsr" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(339): error: identifier "cusparseGetErrorString" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(344): error: identifier "cusparseCreateDnVec" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(344): error: identifier "cusparseGetErrorString" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(345): error: identifier "cusparseCreateDnVec" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(345): error: identifier "cusparseGetErrorString" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

[ 96%] Built target MueLu_KokkosKernels
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(349): error: identifier "cusparseGetErrorString" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here

[ 96%] Building CXX object packages/muelu/test/unit_tests/CMakeFiles/MueLu_UnitTests_Blocked.dir/MueLu_TestHelpers.cpp.o
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/MatvecKernelDriver.cpp(350): error: identifier "cusparseDestroyDnVec" is undefined
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=long long, Node=KokkosClassic::DefaultNode::DefaultNodeType]"
/ascldap/users/ndellin/trilinos/Trilinos-1/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp(178): here
...
```

I checked for changes on some of the failing lines, it looks like some changes made in #10186 may have triggered?

### Steps to Reproduce
1. SHA1:  be18a07c07b77784da28ad2d400e1e5cec7b4284
2. Configure script:  Weaver testbed
```bash
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/weaver
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF

module list

cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX=$TRILINOS_INSTALL_DIR \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DMueLu_ENABLE_TESTS=ON \
 -DMueLu_ENABLE_EXAMPLES=ON \
$TRILINOS_DIR
```

In case helpful, I didn't see these errors with SHA 55d7185956289a91f9f75d4510b1a734ed4efd22 which I had previously used during a round of testing

**Comment by cgcgcg** [comment]
I recently changed that test to be compatible with more recent CUDA. Seems that this will more tricky than anticipated..

**Comment by ndellingwood** [comment]
@cgcgcg yeah, if I remember correctly I think the API was updated at a patch release rather than major or minor which is pretty inconvenient. Here is a link that may be helpful to skim for macro definitions etc from KokkosKernels for spmv with cusparse version macro guards - https://github.com/kokkos/kokkos-kernels/blob/8381db0486674c1be943de23974821ddfb9e6c29/src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp#L91-L93

**Comment by cgcgcg** [comment]
Instead of dealing with all the different cases, I just made this driver experimental. So this shouldn't be an issue anymore.

**Comment by ndellingwood** [comment]
Thanks @cgcgcg !

**Comment by cgcgcg** [comment]
Please reopen if this is still an issue.
