### PR TITLE
change std::unary_function and std::binary_function call to C++17 com…

### LINKED ISSUE #12378: C++17 compatability
### Description
Trilinos defaults to c++17 standard, but there are functions, e.g. [`unary_function`](https://en.cppreference.com/w/cpp/utility/functional/unary_function) and [`binary_function`](https://en.cppreference.com/w/cpp/utility/functional/binary_function) that are removed in c++17 and replaced with `__binary_function` and `__unary_function`, these must be replaced 

The incomplete compatibility with the default c++17 standard creates problems for more pedantic compilers (I'm looking at you apple-clang).  

https://github.com/trilinos/Trilinos/labels/pkg%3A%20Percept @rppawlo
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Piro @ikalash
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Panzer @rppawlo

### Fixes

- Piro:  #12201  

- Panzer:  *none filed*

- Percept: *none filed*

- Tpetra:  Already fixed in Tpetra by #11920 

### Fix

Starting with trilinos-release-14.4.0, I've created a patch  [cxx17.patch](https://github.com/trilinos/Trilinos/files/12848080/cxx17.patch) (I can't push) that will change two functions in multiple packages: piro, panzer, and percept.

### PR DESCRIPTION
**Pull request by cjobrie**
Trilinos defaults to c++17 standard, but there are functions, e.g. [unary_function](https://en.cppreference.com/w/cpp/utility/functional/unary_function) and [binary_function](https://en.cppreference.com/w/cpp/utility/functional/binary_function) that are removed in c++17 and replaced with __binary_function and __unary_function, these must be replaced

The incomplete compatibility with the default c++17 standard creates problems for more pedantic compilers (I'm looking at you apple-clang).

https://github.com/trilinos/Trilinos/labels/pkg%3A%20Panzer
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Percept
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Piro
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Stokhos
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Amesos2
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Belos
@rppawlo
@ikalash
 @rppawlo

## Motivation
#12378 #12201

### CODE REVIEW

**Comment by cjobrie** [comment]
review @cgcgcg

**Comment by cjobrie** [comment]
I just made a few bug fixes and pushed, can you start the CI pipeline again ? @cgcgcg

**Comment by cjobrie** [comment]
Unfortunately, the oldest gcc I can access on SNL systems is gcc@9.2.0 that has the required versions of `cmake` and `netcdf`. I don't have any errors when compiling with those compilers. 

I'll leave this PR open until someone on the @trilinos team has a better idea of how to debug this issue or can do it on a system with a much older compiler.

**Comment by cgcgcg** [comment]
@trilinos/framework: @cjobrie was trying to follow the instructions for reproducing PR builds on SRN but got a permission error in the `git clone` in `./packages/framework/get_dependencies.sh --srn`. Moreover, the build artifacts seem to be gone. Do they get deleted after some time?

**Comment by cgcgcg** [comment]
@trilinos/framework ping

**Comment by sebrowne** [comment]
@cjobrie pinged me directly earlier today, I granted him access to the correct repository.  The build artifacts on Jenkins do get cleaned up, but the ones on CDash should stick around.

**Comment by cjobrie** [comment]
@cgcgcg @sebrowne I am unable to retrieve the `packageEnables.cmake` file from the [CDASH interface](https://trilinos-cdash.sandia.gov/viewFiles.php?buildid=1196272). The ultimate error is:
```console 
In file included from /fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_DataLayout.hpp:51,
                 from /fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_DataLayout.cpp:45:
/fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp:23:26: error: ‘OpenMP’ in namespace ‘Kokkos’ does not name a type
   23 |   using Device = Kokkos::OpenMP;
      |                          ^~~~~~
```

Other issues in reproducing PR instructions:
- I also had to manually load the `aue/cmake/3.24.3` module to get a recent version of CMAKE. 
- ninja isn't on the path nor is the configuration file `build.ninja`

 I instead tried to use the `GeneratedPRfragment.cmake` but using this file results in many errors during build with

**Comment by sebrowne** [comment]
Do not use `GeneratedPRfragment.cmake`, it contains many paths, etc. that are particular to the automated process.

OpenMP should not be enabled to replicate that build line.  Also, GenConfig should be loading the cmake you need for you prior to running cmake.  Can you post the exact command you ran?

**Comment by cjobrie** [comment]
I ran the configure command 

First I have to load: 
```
 module load aue/cmake/3.24.3
```
Then
```
 ./packages/framework/get_dependencies.sh --srn
```
Then,
```
source /projects/sems/modulefiles/utils/sems-modules-init.sh
```
Finally I run the configure command:
```
source ../Trilinos-fork/packages/framework/GenConfig/gen-config.sh --cmake-fragment genconfig.cmake rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables ../Trilinos-fork 
```
However,  I continue to get errors with OPENMP:
```/fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp:23:26: error: ‘OpenMP’ in namespace ‘Kokkos’ does not name a type
   23 |   using Device = Kokkos::OpenMP;
```

**Comment by sebrowne** [comment]
@cjobrie 

Running this on my HPWS replicates the build errors from the dashboard (I've already checked out your branch in $MY_TRILINOS_CLONE and merged the current develop branch):

`cd $MY_TRILINOS_CLONE
mkdir build
cd build/packages/framework
./get_dependencies.sh --srn
cd ../../
source /projects/sems/modulefiles/utils/sems-modules-init.sh
source ../packages/framework/GenConfig/gen-config.sh --cmake-fragment genconfig.cmake rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables ..
cmake -C ./gen-config.sh -DTrilinos_ENABLE_ALL_PACKAGES=ON ..
ninja`

You definitely should not need to load an AUE module to replicate those builds.  GenConfig will load an appropriate CMake for you.  When I run it, the cmake in my PATH (at the beginning of the process) is /usr/bin/cmake, which is the RHEL7 default of 2.8, and once I'm in the GenConfig-set-up shell, it is a SEMS cmake (3.24.3).

Note that the build time will be a bit hefty, as it is building everything.

**Comment by cjobrie** [comment]
Following the instructions in the previous comment, I am still unable to get past the issue with OPENMP. 

```console
In file included from /fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_DataLayout.hpp:51,
                 from /fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_DataLayout.cpp:45:
/fgs/cjobrie/Trilinos-fork/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp:23:26: error: ‘OpenMP’ in namespace ‘Kokkos’ does not name a type
   23 |   using Device = Kokkos::OpenMP;
      |                          ^~~~~~
```

**Comment by cgcgcg** [comment]
@cjobrie That line should be masked out in that build, see:
https://github.com/trilinos/Trilinos/blob/d1f042da58a3e1de8bb198a5bfc3821608db625b/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp#L22-L23
I would suggest you try to track down why it gets enabled.

File: packages/belos/src/BelosTsqrOrthoManagerImpl.hpp
Comment (hkthorn) [inline packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:1]: This is experimental code, which is not enabled or tested by default PR testing.  This seems to be confirmed by looking at the PR results.  How was this tested?

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:1]: I'm not clear on what you mean by *experimental*; this in intended to be merged with the develop branch to make the code more strictly compatable with c++17 standards. Specifically, this change will allow Clang@15 to compile the code and still work with gcc@8.6 (the oldest compiler in the test framework).  

@cgcgcg had run this workflow before. I personally tested it locally. I'm not a trilinos developer, but I wanted to help out getting the code to compile on more recent compilers.

Comment (cgcgcg) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:1]: What @hkthorn is saying: you modified a piece of code that is not exercised by the autotester (because it is marked as experimental). I guess it is reasonable to say that you did not run some tests on you system to see if the code still works, but Belos probably wants to check that it's not breaking anything. (I wouldn't think so.)

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:1]: Oh, ok understood.

However, I would prefer to make that change permanent as it is not part of the c++17 standard and once the feature is not experimental, it will break strict c++17 compilers.

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:1]: Can you please review https://github.com/trilinos/Trilinos/labels/pkg%3A%20Belos

Comment (hkthorn) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:1]: I will need the code tested by building Trilinos with the cmake option `-D Belos_ENABLE_TSQR:BOOL=ON` and running the Belos tests.  This will ensure that the code change is safe since PR testing will not check this piece of code.  Please report back on the results of this local verification.  Thanks!
