### ISSUE TITLE
TPetra: Private  access to Kokkos_DualView.hpp t_dev d_view;

### ISSUE THREAD

**Issue by spdomino** [trilinos/Trilinos#14722]
Greetings,

I am supporting a new product, Mare-Nalu (forked from Nalu-proper) and noticed a Trilinos build error in our nightly process (see below).

Versions:

```
COMERI/MareNalu SHA1: bf5da8f7786fdb057913eddb69b0930c21cc5e00
Trilinos/develop SHA1: abe56bf699f3f67b426152f5b98b4b730e22dc90
```

The Trilinos config follows what was done in Nalu, with C++ active:

`-- The Current CXX Standard is : 20`

I can probably execute a bisect since the last "good" was just yesterday:

```
COMERI/MareNalu SHA1: bf5da8f7786fdb057913eddb69b0930c21cc5e00
Trilinos/develop SHA1: bfa0c9fa083eefc68efaf569bd33d984f3bab379
```

Best, Stefan

[ 20%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_MultiVector_LONG_INT_LONG_SERIAL.cpp.o
In file included from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp:34,
                 from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release/packages/tpetra/core/src/Tpetra_MultiVector_LONG_INT_LONG_SERIAL.cpp:34:
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp: In instantiation of ‘bool Tpetra::Details::WrappedDualView<DualViewType>::needsSyncPath() const [with DualViewType = Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >]’:
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp:225:9:   required from ‘typename DualViewType::t_host::const_type Tpetra::Details::WrappedDualView<DualViewType>::getHostView(Tpetra::Access::ReadOnlyStruct) const [with DualViewType = Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >; typename DualViewType::t_host::const_type = Kokkos::View<const long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks, Kokkos::MemoryTraits<0> >; t_host = Kokkos::View<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>]’
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:3740:27:   required from ‘typename Tpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::dual_view_type::t_host::const_type Tpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::getLocalViewHost(Tpetra::Access::ReadOnlyStruct) const [with Scalar = long int; LocalOrdinal = int; GlobalOrdinal = long int; Node = Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial>; typename dual_view_type::t_host::const_type = Kokkos::View<const long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks, Kokkos::MemoryTraits<0> >; typename dual_view_type::t_host = Kokkos::View<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>; dual_view_type = Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >]’
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release/packages/tpetra/core/src/Tpetra_MultiVector_LONG_INT_LONG_SERIAL.cpp:42:3:   required from here
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp:625:25: error: ‘Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::t_host Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::h_view’ is private within this context
  625 |         return dualView.h_view.data() != dualView.d_view.data();
      |                ~~~~~~~~~^~~~~~
In file included from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_Util.hpp:23,
                 from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp:18,
                 from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_DistObject_decl.hpp:16,
                 from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release/packages/tpetra/core/src/Tpetra_DistObject.hpp:1,
                 from /home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp:19:
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/kokkos/containers/src/Kokkos_DualView.hpp:228:10: note: declared private here
  228 |   t_host h_view;
      |          ^~~~~~
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp:625:51: error: ‘Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::t_dev Kokkos::DualView<long int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::d_view’ is private within this context
  625 |         return dualView.h_view.data() != dualView.d_view.data();
      |                                          ~~~~~~~~~^~~~~~
/home/spdomino/gitHubWork/nightlyBuildAndTest/Trilinos/packages/kokkos/containers/src/Kokkos_DualView.hpp:227:9: note: declared private here
  227 |   t_dev d_view;
      |         ^~~~~~
make[2]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/build.make:597: packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_MultiVector_LONG_INT_LONG_SERIAL.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5573: packages/tpetra/core/src/CMakeFiles/tpetra.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by spdomino** [comment]
Well, it only took two iterations on bisect, and since it's a cheap effort (all in Trilinos build), here you go @srkenno and @tjfulle:
```

10f4632215b29062fee92d0ca359c6bd1844cd4c is the first bad commit
commit 10f4632215b29062fee92d0ca359c6bd1844cd4c
Author: Tim Fuller <tjfulle@sandia.gov>
Date:   Wed Oct 8 17:15:55 2025 -0600

    Reimplement copy and permute changes done by @srkenno
    
    The work was originally merged in #13714 and was shown to speed up some solves substantially.
    But, some platforms experienced slowdowns and the work was reverted in #13821.
    
    This commit re-impliments the work, but wraps new code in if(Details::Behavior::useNewCopyAndPermute) {...}
    which in turn is activated by setting the TPETRA_USE_NEW_COPY_AND_PERMUTE environment variable.
    
    Signed-off-by: Tim Fuller <tjfulle@sandia.gov>

```

**Comment by cgcgcg** [comment]
@sebrowne @ccober6 I think that this needs to be sorted out before we can release 16.2.

**Comment by spdomino** [comment]
> [@sebrowne](https://github.com/sebrowne) [@ccober6](https://github.com/ccober6) I think that this needs to be sorted out before we can release 16.2.

More broadly, 17.0, no? At present, I see this issue only appended to 16.2 notes, however, the issue applies to both since it is within Tpetra.

**Comment by cgcgcg** [comment]
Oh, for sure. We won't release 17.0 until after 16.2. So effectively both are blocked.

**Comment by cgcgcg** [comment]
`Kokkos::DualView::d_view` and `Kokkos::DualView::d_host` are private if Kokkos is built with deprecated code disabled:
https://github.com/trilinos/Trilinos/blob/ca2c91920d434254ee36bf1832e85dd9463c1638/packages/kokkos/containers/src/Kokkos_DualView.hpp#L217-L228

This obviously needs to be fixed. But it also exposes a gap in the autotester. @trilinos/framework

**Comment by spdomino** [comment]
Can this bad push simply be reverted? Seems like there is not much movement on the resolution (nightly failed again).

**Comment by jhux2** [comment]
@spdomino The AT is down, no PRs are going through right now.

**Comment by jhux2** [comment]
This is also breaking the Trilinos performance build on Eclipse.

**Comment by jhux2** [comment]
@tjfulle

**Comment by cgcgcg** [comment]
@spdomino I think that the fix is easy enough that we can deal with this directly. Will ping you once we think your builds should pass again. Hopefully later today..

**Comment by ndellingwood** [comment]
This showed up in our nightly integration builds with kokkos@5.0 as well, the breakage occurs when setting `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF` , should be resolved with [#14731](https://github.com/trilinos/Trilinos/pull/14731)

https://github.com/kokkos/kokkos/pull/7716 refers to the associated deprecation

**Comment by cgcgcg** [comment]
@spdomino Should be fixed in your next nightly run.

**Comment by spdomino** [comment]
Great. I will report back tomorrow so that we can close the ticket. Best,

**Comment by spdomino** [comment]
Looks clean now. Thank you:)

COMERI/MareNalu SHA1: bf5da8f7786fdb057913eddb69b0930c21cc5e00
Trilinos/develop SHA1: 205208491198acc70b09124370ed98387a43dee1

**Comment by cgcgcg** [comment]
Perfect, thanks for checking :-)

**Comment by spdomino** [comment]
My pleasure. I am committed to the Mare-Nalu product this next year (and beyond) as I move towards new applications. I am sure we will be in touch. If there is a central Trilinos email list for “external partners”, let me know. Otherwise, ‘until the next diff:)
