### ISSUE TITLE
Sacado: Gtest -Werror with gcc/11.2.0

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#11970]
## Bug Report
While setting up a build with gcc/11.2.0 I ran into this warning in Sacado's copy of gtest that tripped an error with -Werror:
```
In file included from /ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest/src/gtest-all.cc:42:
/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest/src/gtest-death-test.cc: In function 'bool testing::internal::StackGrowsDown()':
/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest/src/gtest-death-test.cc:1306:24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]
 1306 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest/src/gtest-death-test.cc:1295:13: note: by argument 1 of type 'const void*' to 'void testing::internal::StackLowerThanAddress(const void*, bool*)' declared here
 1295 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest/src/gtest-death-test.cc:1304:7: note: 'dummy' declared here
 1304 |   int dummy;
      |       ^~~~~
```

Adding the cxxflag `-Wno-maybe-uninitialized` works around this with -Werror, I'm not sure if a newer version of gtest is needed?

@trilinos/sacado  @etphipp 

This was with an OpenMP debug build on Blake (SKX arch)
