### PR TITLE
Piro: fix compilation error when Teko is not enabled

### LINKED ISSUE #11670: Piro: compilation errors building Albany-LCM
We have compilation errors in Albany-LCM due to things in Piro pertaining to ROL/analysis: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=46293

The errors look like this: 
```
[packages/piro/src/Piro_PerformAnalysis.cpp:662](https://blob/master/packages/piro/src/Piro_PerformAnalysis.cpp#L662):85: error: ‘H_dotP’ was not declared in this scope
```

@mperego , @kliegeois : is this due to changes you pushed recently?

@trilinos/piro

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/piro

## Motivation
Fix bug introduced in #11649 to avoid compilation error when Trilinos is built with Teko disabled.

Closes #11670.

### CODE REVIEW

**Review by ikalash — APPROVED** [review]
I tested it and things look good.  Thanks!

**Comment by mperego** [comment]
> I tested it and things look good. Thanks!

Thanks!
