### ISSUE TITLE
STK build failures in ATDM build on hansen cuda 9.0 build that started failing 10/31/2018

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3793]
CC: @trilinos/stk , @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe 
 
## Next Action Status

Commits to STK from @alanw0 from PR #3765 merged by @prwolfe to 'develop' on 10/30/2018 are likely the cause of this.  Next: Fix the build errors?

## Description
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-11-02&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug&field2=buildstarttime&compare2=84&value2=2018-11-02&field3=buildstarttime&compare3=83&value3=2018-10-28) the tests:
* STKSearch_search_unit_tests_MPI_1
* STKSearch_search_integration_tests_MPI_1

are not running due to build failures in the build:
* Trilinos-atdm-hansen-shiller-cuda-9.0-debug

Full output from the failures can be found [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4125879)

This build began failing on 2018-10-31. There are a lot of errors that look like this:

```
/home/projects/x86-64/gcc/4.9.3/include/c++/4.9.3/bits/basic_string.h(1026): error: identifier "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_empty_rep_storage" is undefined in device code
```

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the system <supported-atdm-system> are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#<system-section-name>
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-hansen-shiller-cuda-9.0-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
  $TRILINOS_DIR

$ make NP=16

$ srun ctest -j16
```

**Comment by mhoemmen** [comment]
@alanw0

**Comment by bartlettroscoe** [comment]
CC: @alanw0, @prwolfe 

FYI: If you look at the build history for this build [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug&field2=site&compare2=61&value2=hansen&field3=buildstarttime&compare3=84&value3=2018-11-02T00%3A00%3A00&field4=buildstarttime&compare4=83&value4=2018-10-03T00%3A00%3A00). you will see that this build started failing on 10/31/2018.  If you look at the new commits that were pulled that day shown [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4121854#!#note6) you can see the commits 2041c5d, 5689fc4, and b49ec15 pulled in with the PR #3765 merged to 'develop' on 10/30/2018.  It seems very likely that merging this PR broke this build.

@alanw0, can you please take a look at what it would take to fix this build error?

**Comment by alanw0** [comment]
@bartlettroscoe @mhoemmen I'll see what I can do.

**Comment by mhoemmen** [comment]
Thanks Alan!

**Comment by bartlettroscoe** [comment]
Looks like PR #3795 merged to 'develop' on 11/2/2018 as fixed this build as shown today [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4132922&filtercount=1&showfilters=1&field1=subproject&compare1=61&value1=STK) (see the `-5' subscript by the `0` "Build Error", the `-2` subscript by the `0` "Not Run" tests and the `+2` superscript by the `3` "Pass" tests).

@alanw0, thanks for taking care of this so quickly!

Closing as complete.

**Comment by bartlettroscoe** [comment]
> No problem, glad it worked. Sierra has a nightly nvidia build, but this issue didn't show up for some reason. Our build is gcc7.2.0/nvcc9.2.88.

@alanw0, this was not Sierra's or your fault for not catching this.  This passed in every other CUDA build and over other platform we test on except for this one `cuda-9.0-debug` build as shown yesterday [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-02&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda&field3=subprojects&compare3=93&value3=STK).  It even passed in the  `cuda-9.0-opt` build on that same platform!

This is why we do portability testing.
