### PR TITLE
removed all noncompliant <c++17 statements

### LINKED ISSUE #12378: C++17 compatability
### Description
Trilinos defaults to c++17 standard, but there are functions, e.g. [`unary_function`](https://en.cppreference.com/w/cpp/utility/functional/unary_function) and [`binary_function`](https://en.cppreference.com/w/cpp/utility/functional/binary_function) that are removed in c++17 and replaced with `__binary_function` and `__unary_function`, these must be replaced 

The incomplete compatibility with the default c++17 standard creates problems for more pedantic compilers (I'm looking at you apple-clang).  

https://github.com/trilinos/Trilinos/labels/pkg%3A%20Percept @rppawlo
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Piro @ikalash
https://github.com/trilinos/Trilinos/labels/pkg%3A%20Panzer @rppawlo

### Fixes

- Piro:  #12201  

- Panzer:  *none filed*

- Percept: *none filed*

- Tpetra:  Already fixed in Tpetra by #11920 

### Fix

Starting with trilinos-release-14.4.0, I've created a patch  [cxx17.patch](https://github.com/trilinos/Trilinos/files/12848080/cxx17.patch) (I can't push) that will change two functions in multiple packages: piro, panzer, and percept.

### PR DESCRIPTION
**Pull request by cjobrie**
@trilinos/Panzer
@trilinos/Percept
@trilinos/Adapt
@trilinos/Piro
@trilinos/Stokhos
@trilinos/Belos
@trilinos/Amesis2
@rppawlo
@ikalash
@rppawlo
@csiefer2 

## Motivation
Ensure compliance with newer c++ compilers that have removed deprecated std library functions `std::unary_function` and `std::binary_function`. Specifically, deriving classes from these functions causes compilers like clang@15 to fail. 

## Related Issues
Related to https://github.com/trilinos/Trilinos/issues/12201
Closes #12378 

Reviewers @csiefer2 @cgcgcg

### CODE REVIEW

**Comment by jhux2** [comment]
@cjobrie This should be merged to `develop`, not `master`.

**Comment by cjobrie** [comment]
@jhux2 Fixed, appologies

**Review by rppawlo — DISMISSED** [review]
Thanks @cjobrie !

**Comment by rppawlo** [comment]
@bricar

**Review by etphipp — DISMISSED** [review]
Stokhos changes look good.

**Comment by mperego** [comment]
Piro changes look good to me

File: packages/belos/src/BelosTsqrOrthoManagerImpl.hpp [hunk 1]
```diff
@@ -128,9 +128,6 @@ namespace Belos {
   /// yourself.
   template<class Scalar>
   class ReorthogonalizationCallback :
```
Comment (ndellingwood) [inline packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:130]:
```suggestion
  class ReorthogonalizationCallback
```

The colon needs to be dropped

**Review by ndellingwood — COMMENTED** [review]
I don't think superlu_dist is tested with CI, can you confirm that these changes are non-breaking?

File: packages/belos/src/BelosTsqrOrthoManagerImpl.hpp (hunk 1 above)
Comment (hkthorn) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:130]: I am likewise concerned that changes made in this PR are not being thoroughly tested and may result in errors when optional code is enabled by the user.

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:130]: Sorry, I'm not a trilinos developer, how can I test superlu_dist?

Comment (ndellingwood) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:130]: @cjobrie you'll need an install of superlu_dist and metis available, and you might need to point to them in the cmake configuration, something like this (where you would need to provide the relevant env variable paths to the tpl installs):

```
-DTPL_ENABLE_SuperLUDist:BOOL=ON \ -DSuperLUDist_INCLUDE_DIRS:PATH="${SUPERLU_DIST_INCLUDE_PATH}" \
-DSuperLUDist_LIBRARY_DIRS:PATH="${SUPERLU_DIST_LIBRARY_PATH};${METIS_LIBRARY_PATH}/libmetis.a;${BLAS_LIBS};${LAPACK_LIBS};gfortran;gomp;m" \
# The gfortran;gomp;m additions may be unnecessary, but some/all may help if you encounter linker errors
```

With Amesos2 you can enable SuperLU_Dist solver with `-DAmesos2_ENABLE_SuperLUDist:BOOL=ON`

If you're a spack user there may be formula you can use as well, though I'm not familiar enough to provide details

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: I'm sorry, Trilinos passed all ctest tests on intel, but I can't quite get `superlu` to build. I've no idea how to do it and the instructions don't tell me where the libraries could be installed. 

Using the `-DfAmesos2...` command errors out as reported below:

```console
CMake Error at cmake/tribits/core/package_arch/TribitsProcessEnabledTpls.cmake:278 (message):
  ERROR: TPL_SuperLUDist_NOT_FOUND=TRUE, aborting!
```

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: The only `libmetis.a` I've found is at "projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/metis-5.1.0-vxnfwinsazp37pgcjusoa3xuvhxvdiiq/lib/libmetis.a" However, using your suggestions, I still can't seems to get Amesos to recognize it. 

```concole
CMake Error at packages/amesos/CMakeLists.txt:16 (MESSAGE):
  The Amesos support for the SuperLUDist TPL requires the ParMETIS TPL.
  Either disable Amesos SuperLUDist support or enable the ParMETIS TPL.
```

Comment (ndellingwood) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: @cjobrie that is picking up Amesos instead of Amesos2, since these changes only impact Amesos2 I'd suggest disabling Amesos (-DTrilinos_ENABLE_Amesos=OFF).
It looks like ParMetis is required in addition to Metis (I don't build with superlu_dist often, had forgotten about this).
You'll need to add parmetis in your spack configuration, and you may need additional config options like:
```
-D TPL_ENABLE_METIS:BOOL=ON \
  -D METIS_INCLUDE_DIRS:PATH="${METIS_PATH}/include" \
  -D METIS_LIBRARY_DIRS:PATH="${METIS_PATH}/lib" \
  -D METIS_LIBRARY_NAMES:STRING="metis" \
-D TPL_ENABLE_ParMETIS:BOOL=ON \
  -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETIS_PATH}/include;${METIS_PATH}/include" \
  -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETIS_PATH}/lib" \
  -D ParMETIS_LIBRARY_NAMES:STRING="parmetis" \
...
  -D SuperLUDist_LIBRARY_DIRS:PATH="${SUPERLU_DIST_PATH}/lib/libsuperlu_dist.a;${METIS_PATH}/lib/libmetis.a;${PARMETIS_PATH}/lib/libparmetis.a;${BLAS_PATH}/lib/libopenblas.a" \
```

Sorry I can't provide more specific guidance rather than configuration snips, using TPLs can be finicky (though spack should help with this).

I'm trying to build superlu_dist and hit some bumps myself. Let me know if any of the above is useful enough to get a complete configuration and build on your end, I'll keep working at it as well

Comment (ndellingwood) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: I added the pretest inspection label so we can check the AT results

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: Unfortunately, this suggestion breaks everything. Is there anyone who has this setup to try this. I don't have the time or expertise to fix this kind of detailed  problem with a build system I don't have any experience with.


```CMake Error at cmake/tribits/core/utils/CombinedOption.cmake:129 (message):
  Error: you can not enable the option TEKO_HAVE_EPETRA unless you also
  enable the options Teko_ENABLE_Epetra, Teko_ENABLE_ThyraEpetraAdapters,
  Teko_ENABLE_ThyraEpetraExtAdapters, Teko_ENABLE_AztecOO,
  Teko_ENABLE_Ifpack, Teko_ENABLE_Amesos, Teko_ENABLE_ML.  The current option
  values are:

    Teko_ENABLE_Epetra='ON'
    Teko_ENABLE_ThyraEpetraAdapters='ON'
    Teko_ENABLE_ThyraEpetraExtAdapters='ON'
    Teko_ENABLE_AztecOO='ON'
    Teko_ENABLE_Ifpack='ON'
    Teko_ENABLE_Amesos='OFF'
    Teko_ENABLE_ML='ON'

Call Stack (most recent call first):
  packages/teko/CMakeLists.txt:25 (COMBINED_OPTION)
```

Comment (ndellingwood) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: @cjobrie yuck... I didn't know so much stuff was turned on. Alright, if you can try one case, reenable Amesos and also enable Parmetis. Reenabling Amesos should resolve the new stuff you just posted, and hopefully enabling Parmetis is sufficient to work out the dependency requested by SuperLU_Dist (this was a couple messages ago)

Comment (cjobrie) [reply packages/belos/src/BelosTsqrOrthoManagerImpl.hpp]: Once again, I've tried:
```cmake -DTrilinos_ENABLE_Amesos=ON -DAmesos2_ENABLE_SuperLUDist:BOOL=ON -DTPL_ENABLE_METIS:BOOL=ON -DTPL_ENABLE_ParMETIS:BOOL=ON -DParMETIS_LIBRARY_DIRS:PATH="/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/parmetis-4.0.3-yj2npclamik5tmk2bj7l2asttqrz3pmc/lib" -DParMETIS_INCLUDE_DIRS:PATH="/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/parmetis-4.0.3-yj2npclamik5tmk2bj7l2asttqrz3pmc/include"  -C ../Trilinos-fork/genconfig.cmake ../Trilinos-fork 
```
and ParMETIS can't be found!!!

**Comment by rppawlo** [comment]
I tried to build trilinos (excluding the changes in this PR) against the latest release of SuperLUDist (8.1.0) and get the errors below. I've never built with SuperLUDist before so it is most likely pilot error, but without the changes in this PR it seems Amesos2 is already broken for SuperLUDist. Could someone on the Amesos2 team test this PR with SuperLUDist? This PR is required for some work in empire.

```
/tmp/Trilinos/packages/amesos2/src/Amesos2_Superludist_decl.hpp:115:30: error: no type named 'type' in 'Amesos2::TypeMap<Amesos2::Superludist, std::complex<double>>'
  typedef typename type_map::type                                  slu_type;
          ~~~~~~~~~~~~~~~~~~~^~~~
/tmp/Trilinos/packages/amesos2/src/Amesos2_Superludist.cpp:102:30: note: in instantiation of template class 'Amesos2::Superludist<Tpetra::CrsMatrix<std::complex<double>>, Tpetra::MultiVector<std::complex<double>>>' requested here
  AMESOS2_SOLVER_TPETRA_INST(Superludist,std::complex<double>,int,long long);
                             ^
In file included from /tmp/Trilinos/packages/amesos2/src/Amesos2_Superludist.cpp:47:
/tmp/Trilinos/packages/amesos2/src/Amesos2_Superludist_decl.hpp:116:30: error: no type named 'magnitude_type' in 'Amesos2::TypeMap<Amesos2::Superludist, std::complex<double>>'
  typedef typename type_map::magnitude_type                  magnitude_type;
          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/tmp/Trilinos/packages/amesos2/src/Amesos2_Superludist_decl.hpp:287:24: error: no type named 'LUstruct_t' in 'Amesos2::TypeMap<Amesos2::Superludist, std::complex<double>>'
    typename type_map::LUstruct_t LU; ///< storage for L and U factors
    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/tmp/Trilinos/packages/amesos2/src/Amesos2_Superludist_decl.hpp:320:5: note: in instantiation of member class 'Amesos2::Superludist<Tpetra::CrsMatrix<std::complex<double>>, Tpetra::MultiVector<std::complex<double>>>::SLUData' requested here
  } data_;
    ^

```

**Comment by GrahamBenHarper** [comment]
@csiefer2 any clue why the master merge workflow didn't trigger?

**Comment by ndellingwood** [comment]
@rppawlo thanks for the update. I was able to build deveop branch with superlu_dist/6.4.0 (old install on my laptop) though I'm running into some test fails (quite likely self-inflicted setup issues). I'll work on a build with superlu_dist/8.1.0, it's possible there were some interface/type/namespace updates in the tpl that are missing in Amesos2 for newer versions of sludist

**Comment by ndellingwood** [comment]
@GrahamBenHarper does the master merge testing include superlu_dist, and if so which version? The issues Roger posted may be specific to more recent versions of SuperLUDist (I didn't run into compilation errors with version 6.4.0)

**Comment by GrahamBenHarper** [comment]
Sorry @ndellingwood , yes I was referring to the workflow which comments when a PR is opened against master. It seems something strange is happening with the workflows.

**Comment by cjobrie** [comment]
Do I need to close the request and reopen based on the mistake?

**Comment by ndellingwood** [comment]
> Do I need to close the request and reopen based on the mistake?

@cjobrie it looks like you reset the PR to point at develop so I wouldn't think so. @csiefer2 @sebrowne any guidance or insight to add?

**Comment by ndellingwood** [comment]
@cjobrie regarding the superlu_dist testing in Amesos2, I tested your PR locally and the Amesos2 tests passed 👍 

```
s1067110:Amesos2MPI-SLUDist-parmetis ndellin$ ctest -R Amesos2
Test project /Users/ndellin/Research/trilinos/Trilinos/Build/Amesos2MPI-SLUDist-parmetis
      Start  1: Amesos2_klu2_simple_MPI_4
 1/12 Test  #1: Amesos2_klu2_simple_MPI_4 ............................   Passed    0.75 sec
      Start  2: Amesos2_KLU2_UnitTests_MPI_2
 2/12 Test  #2: Amesos2_KLU2_UnitTests_MPI_2 .........................   Passed    2.25 sec
      Start  3: Amesos2_KLU2_Solver_Test_MPI_2
 3/12 Test  #3: Amesos2_KLU2_Solver_Test_MPI_2 .......................   Passed    1.90 sec
      Start  4: Amesos2_Umfpack_Solver_Test_MPI_4
 4/12 Test  #4: Amesos2_Umfpack_Solver_Test_MPI_4 ....................   Passed    2.16 sec
      Start  5: Amesos2_SuperLU_DIST_Solver_Test_MPI_4
 5/12 Test  #5: Amesos2_SuperLU_DIST_Solver_Test_MPI_4 ...............   Passed    7.40 sec
      Start  6: Amesos2_LAPACK_Solver_Test_MPI_4
 6/12 Test  #6: Amesos2_LAPACK_Solver_Test_MPI_4 .....................   Passed    1.13 sec
      Start  7: Amesos2_Basker_UnitTests_MPI_2
 7/12 Test  #7: Amesos2_Basker_UnitTests_MPI_2 .......................   Passed    1.81 sec
      Start  8: Amesos2_Basker_Solver_Test_MPI_1
 8/12 Test  #8: Amesos2_Basker_Solver_Test_MPI_1 .....................   Passed    0.74 sec
      Start  9: Amesos2_SolverFactory_UnitTests_MPI_4
 9/12 Test  #9: Amesos2_SolverFactory_UnitTests_MPI_4 ................   Passed    2.10 sec
      Start 10: Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4
10/12 Test #10: Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4 ...   Passed    0.86 sec
      Start 11: Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4
11/12 Test #11: Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4 .....   Passed    1.29 sec
      Start 12: Amesos2_GappedMtxGIDs-1proc_MPI_1
12/12 Test #12: Amesos2_GappedMtxGIDs-1proc_MPI_1 ....................   Passed    1.65 sec

100% tests passed, 0 tests failed out of 12

Subproject Time Summary:
Amesos2    =  77.11 sec*proc (12 tests)

Total Test time (real) =  24.31 sec
```

**Review by rppawlo — APPROVED** [review]

**Comment by ndellingwood** [comment]
Amesos2 Testing Reproducer Reference:

**Compiler + TPLs**:
```
gcc/10.4, openmpi/4.1.1, openblas/0.3.20, parmetis/4.0.3, metis/5.1.0, superlu_dist/6.4.0,
```

**SuperLU_Dist/6.4.0 Configuration and Build**:
```
cmake \
    -DTPL_ENABLE_COMBBLASLIB=OFF \
    -DTPL_ENABLE_PARMETISLIB=ON \
    -DTPL_PARMETIS_INCLUDE_DIRS="${PARMETIS_PATH}/include;${METIS_PATH}/include" \
    -DTPL_PARMETIS_LIBRARIES="${PARMETIS_PATH}/lib/libparmetis.a;${METIS_PATH}/lib/libmetis.a" \
    -DTPL_ENABLE_BLASLIB=ON \
      -D TPL_BLAS_LIBRARIES=${BLAS_PATH}/lib/libopenblas.a \
    -DTPL_ENABLE_LAPACKLIB=ON \
      -D TPL_LAPACK_INCLUDE_DIRS=${LAPACK_PATH}/include \
      -D TPL_LAPACK_LIBRARIES=${LAPACK_PATH}/lib/libopenblas.a \
    -DCMAKE_INSTALL_PREFIX=$PWD/../install-parmetis \
    -DCMAKE_C_FLAGS="-std=c99 -g" \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpicxx \
    -DCMAKE_CXX_FLAGS="-std=c++14" \
    -DBUILD_SHARED_LIBS=OFF \
..

make -j4
make install
```

**Trilinos Configuration**:
MPI+OpenMP build; requires -D Tpetra_INST_INT_INT=ON for Amesos2 SuperLUDIst tests
```bash
cmake \
\
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D CMAKE_MAKE_PROGRAM:STRING="make" \
-D CMAKE_BUILD_TYPE:STRING=DEBUG \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D TPL_ENABLE_MPI:BOOL=ON \
  -D CMAKE_CXX_COMPILER:FILEPATH="`which mpicxx`" \
  -D CMAKE_C_COMPILER:FILEPATH="`which mpicc`" \
  -D CMAKE_Fortran_COMPILER:FILEPATH="`which mpifort`" \
\
-D TPL_ENABLE_METIS:BOOL=ON \
  -D METIS_INCLUDE_DIRS:PATH="${METIS_PATH}/include" \
  -D METIS_LIBRARY_DIRS:PATH="${METIS_PATH}/lib" \
  -D METIS_LIBRARY_NAMES:STRING="metis" \
-D TPL_ENABLE_ParMETIS:BOOL=ON \
  -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETIS_PATH}/include;${METIS_PATH}/include" \
  -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETIS_PATH}/lib" \
  -D ParMETIS_LIBRARY_NAMES:STRING="parmetis" \
-D TPL_ENABLE_Scotch:BOOL=OFF \
  -D Scotch_INCLUDE_DIRS:PATH="${SCOTCH_PATH}/include" \
  -D Scotch_LIBRARY_DIRS:PATH="${SCOTCH_PATH}/lib" \
  -D Scotch_LIBRARY_NAMES:STRING="scotch;scotcherr" \
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH=${BLAS_PATH}/lib \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${LAPACK_PATH}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH=${LAPACK_PATH}/lib \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_SuperLU:BOOL=OFF \
  -D SuperLU_INCLUDE_DIRS:FILEPATH="${SUPERLU_PATH}/include" \
  -D SuperLU_LIBRARY_DIRS:FILEPATH="${SUPERLU_PATH}/lib" \
  -D SuperLU_LIBRARY_NAMES:STRING="superlu" \
-D TPL_ENABLE_UMFPACK:STRING=ON \
  -D UMFPACK_INCLUDE_DIRS:PATH="${SS_PATH}/include" \
  -D UMFPACK_LIBRARY_DIRS:PATH="${SS_PATH}/lib" \
  -D UMFPACK_LIBRARY_NAMES:STRING="umfpack;suitesparseconfig;amd" \
-D TPL_ENABLE_SuperLUDist:BOOL=ON \
  -D SuperLUDist_INCLUDE_DIRS:PATH="${SUPERLU_DIST_PATH}/include" \
  -D SuperLUDist_LIBRARY_DIRS:PATH="${SUPERLU_DIST_PATH}/lib;${METIS_PATH}/lib/libmetis.a;${PARMETIS_PATH}/lib/libparmetis.a;${BLAS_PATH}/lib/libopenblas.a" \
\
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
\
-D Trilinos_ENABLE_OpenMP:BOOL=ON \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Kokkos_ENABLE_OPENMP:BOOL=ON \
  -D Kokkos_ENABLE_SERIAL:BOOL=ON \
  -D Kokkos_ENABLE_EXAMPLES:BOOL=OFF \
  -D Kokkos_ENABLE_TESTS:BOOL=OFF \
  -D Kokkos_ENABLE_DEBUG_BOUNDS_CHECK:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=OFF \
  -D Epetra_ENABLE_EXAMPLES:BOOL=OFF \
  -D Epetra_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EpetraExt:BOOL=OFF \
  -D EpetraExt_ENABLE_EXAMPLES:BOOL=OFF \
  -D EpetraExt_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Tpetra_ENABLE_EXAMPLES:BOOL=OFF \
  -D Tpetra_ENABLE_TESTS:BOOL=OFF \
  -D Tpetra_INST_SERIAL:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_INST_INT_INT=ON \
-D Trilinos_ENABLE_ShyLU_NodeBasker:BOOL=OFF \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
  -D Amesos2_ENABLE_EXAMPLES:BOOL=ON \
  -D Amesos2_ENABLE_TESTS:BOOL=ON \
  -D Amesos2_ENABLE_KLU2:BOOL=ON \
  -D Amesos2_ENABLE_Basker:BOOL=ON \
  -D Amesos2_ENABLE_UMFPACK:BOOL=ON \
  -D Amesos2_ENABLE_SuperLU:BOOL=OFF \
  -D Amesos2_ENABLE_SuperLUDist:BOOL=ON \
${TRILINOS_DIR}
```

**Comment by ndellingwood** [comment]
> @ndellingwood So we're clear to merge then?

@csiefer2 I can approve the Amesos2 changes, though the testing is limited to the one config I posted [above](https://github.com/trilinos/Trilinos/pull/12494#issuecomment-1802411258)

**Review by ndellingwood — APPROVED** [review]
Approving the Amesos2 changes (caveat that testing is limited to an MPI+OpenMP build)

**Comment by GrahamBenHarper** [comment]
> Do I need to close the request and reopen based on the mistake?

@cjobrie no need to close! you did the right thing by switching the branch. sorry for the confusion; I didn't realize the workflows were treating you as an outside contributor, but @csiefer2 cleared up what was happening.

**Comment by cjobrie** [comment]
Thank you everyone!

**Comment by ndellingwood** [comment]
> I tried to build trilinos (excluding the changes in this PR) against the latest release of SuperLUDist (8.1.0) and get the errors below.

@rppawlo just to follow up, I built superlu_dist/8.1.2 and was able to compile Amesos2 against it without issue following these [steps](https://github.com/trilinos/Trilinos/pull/12494#issuecomment-1802411258), this was with an MPI+OpenMP build. Should we follow up offline to compare configurations etc.?
