### PR TITLE
MueLu: Fix abstract type in matrix-free

### LINKED ISSUE #11660: MueLu: Build errors in matrix-free example
## Bug Report
```
/home/caglusa/Trilinos/packages/muelu/research/graham/mf_example_01.cpp:627:7: error: 'sleep' was not declared in this scope
       sleep(my_rank);
       ^~~~~
```

Also:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=11498666

### PR DESCRIPTION
**Pull request by GrahamBenHarper**
@trilinos/muelu @cgcgcg 

This fixes the bug in the experimental build introduced by #11664, but hopefully it actually fixes #11660.

### Testing
I have confirmed that MueLu experimental builds correctly with this.

### CODE REVIEW

**Review by mayrmt — DISMISSED** [review]

**Comment by jhux2** [comment]
@GrahamBenHarper #11621?

**Comment by GrahamBenHarper** [comment]
Yes, that's the one. `ROL_example_PinT_parabolic-control_AugmentedSystem_test_MPI_2`

**Review by cgcgcg — APPROVED** [review]
