### ISSUE TITLE
Ifpack2/Epetra:  Trilinos from the repo fails to build with HYPRE on Linux

### ISSUE THREAD

**Issue by jrobcary** [trilinos/Trilinos#9149]
## Bug Report
@trilinos/Epetra
@trilinos/Ifpack2

### Description
Trilinos from the repo fails to build with HYPRE on Linux.  trilinos-13.0.0 does build with Hypre.  In all cases, trilinos was configured the same, with the attached configure script.  There are integer mismatches for any choices we have so far made for Hypre.  In one case the error is in Ifpack2, in the other case, the error is in Epetra.  We need Epetra to work to 
to keep our software working.  We need the new stack to work to migrate to it.  Details below.  Any suggestions?

The configure script is:

[vcloud.txcorp.com-trilinos-par-config.sh.txt](https://github.com/trilinos/Trilinos/files/6502489/vcloud.txcorp.com-trilinos-par-config.sh.txt)

The errors are

For no particle choice of Hypre integer, which works with trilinos-13.13.0, the build fails in ifpack2:

```
In file included from /home/research/cary/projects/vorpalall-dev2/builds/trilinos/par/packages/ifpack2/src/Ifpack2_Hypre_Serial.cpp:50:
/home/research/cary/projects/vorpalall-dev2/trilinos/packages/ifpack2/src/Ifpack2_Hypre_def.hpp: In instantiation of ‘void Ifpack2::Hypre<MatrixType>::setParameters(const Teuchos::ParameterList&) [with MatrixType = Tpetra::RowMatrix<float, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >]’:
/home/research/cary/projects/vorpalall-dev2/builds/trilinos/par/packages/ifpack2/src/Ifpack2_Hypre_Serial.cpp:61:1:   required from here
/home/research/cary/projects/vorpalall-dev2/trilinos/packages/ifpack2/src/Ifpack2_Hypre_def.hpp:261:42: error: call of overloaded ‘FunctionParameter(Hypre_Chooser, std::__cxx11::string&, long long int)’ is ambiguous
         IFPACK2_CHK_ERR(AddFunToList(rcp(new FunctionParameter(Hypre_Is_Solver, funct_name , Teuchos::as<global_ordinal_type>(Teuchos::getValue<int>(it->second))))));
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/research/cary/projects/vorpalall-dev2/trilinos/packages/ifpack2/src/Ifpack2_Hypre_decl.hpp:61,
                 from /home/research/cary/projects/vorpalall-dev2/builds/trilinos/par/packages/ifpack2/src/Ifpack2_Hypre_Serial.cpp:49:
/home/research/cary/projects/vorpalall-dev2/trilinos/packages/ifpack2/src/Ifpack2_Hypre_FunctionParameters.hpp:140:5: note: candidate: ‘Ifpack2::FunctionParameter::FunctionParameter(Hypre_Chooser, std::__cxx11::string, double)’
     FunctionParameter(Hypre_Chooser chooser, std::string funct_name, double param1):
     ^~~~~~~~~~~~~~~~~
/home/research/cary/projects/vorpalall-dev2/trilinos/packages/ifpack2/src/Ifpack2_Hypre_FunctionParameters.hpp:127:5: note: candidate: ‘Ifpack2::FunctionParameter::FunctionParameter(Hypre_Chooser, std::__cxx11::string, HYPRE_Int)’
     FunctionParameter(Hypre_Chooser chooser, std::string funct_name, HYPRE_Int param1) :
     ^~~~~~~~~~~~~~~~~
```

For -DHYPRE_ENABLE_MIXEDINT:BOOL=ON or -DHYPRE_ENABLE_BIGINT:BOOL=ON
the build fails in Epetra:

```
In file included from /home/research/cary/dev1/contrib-gcc830/hypre-2.20.0-parsh/include/HYPRE_parcsr_ls.h:13,
                 from /home/research/cary/projects/vorpalall-dev1/trilinos/packages/epetraext/src/hypre/EpetraExt_HypreIJMatrix.h:55,
                 from /home/research/cary/projects/vorpalall-dev1/trilinos/packages/epetraext/src/hypre/EpetraExt_HypreIJMatrix.cpp:48:
/home/research/cary/dev1/contrib-gcc830/hypre-2.20.0-parsh/include/HYPRE_parcsr_mv.h:48:95: note:   initializing argument 3 of ‘HYPRE_Int HYPRE_ParCSRMatrixGetRow(HYPRE_ParCSRMatrix, HYPRE_BigInt, HYPRE_Int*, HYPRE_BigInt**, HYPRE_Complex**)’
 HYPRE_Int HYPRE_ParCSRMatrixGetRow( HYPRE_ParCSRMatrix matrix , HYPRE_BigInt row , HYPRE_Int *size , HYPRE_BigInt **col_ind , HYPRE_Complex **values );

    ~~~~~~~~~~~^~~~
/home/research/cary/projects/vorpalall-dev1/trilinos/packages/epetraext/src/hypre/EpetraExt_HypreIJMatrix.cpp:92:68: error: cannot convert ‘int*’ to ‘HYPRE_Int*’ {aka ‘long long int*’}
     ierr += HYPRE_ParCSRMatrixRestoreRow(ParMatrix_, i+MyRowStart_,&num_entries,&indices,&values);

```

**Comment by jhux2** [comment]
@trilinos/epetra @trilinos/ifpack2

**Comment by jhux2** [comment]
@csiefer2

**Comment by cgcgcg** [comment]
@jrobcary It looks like you're using `long long` global ordinals for Tpetra. Epetra is always using `int` global ordinals. Hypre can only build one ordinal type at a time, so this will not work.

**Comment by jrobcary** [comment]
Thanks.  So it sounds like the only way to have a successful build is for Hypre to be built with int, Epetra with int, and then configure Tpetra to use int.  Is that correct?
And if so, what is the configuration flag for configuring Tpetra with int?

**Comment by cgcgcg** [comment]
Either that, or disable Hypre support in either Ifpack or Ifpack2. I think
```
-D Tpetra_INST_INT_INT:BOOL=ON
-D Tpetra_INST_INT_LONG_LONG:BOOL=OFF
```
should do the trick.

**Comment by jrobcary** [comment]
Thanks for your help.  Adefault build of HYPRE with -DIfpack2_ENABLE_HYPRE=OFF works, and so I presume that a BIGINT build of HYPRE with -DIfpack_ENABLE_HYPRE=OFF would work.

**Comment by jrobcary** [comment]
Problem solved so closing.
