### ISSUE TITLE
Kokkos/commonTools build error on Intel 19.1

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#11568]
## Bug Report
I am attempting an Intel 19.1 build of Trilinos, modules are as follows:

 1) intel/19.1   2) mkl/19.1   3) openmpi-intel/4.0   4) gnu/10.2.1   5) cmake/3.20.3

 I am noticing a common error in Kokkos and commonTools (see below). I thought I could remove gtest, 

-DTrilinos_ENABLE_Gtest:BOOL=OFF \

to deal with this error:

[  0%] Building CXX object commonTools/gtest/CMakeFiles/gtest.dir/gtest/gtest-all.cc.o
/opt/rh/devtoolset-10/root/usr/include/c++/10/tuple(566): error: pack "_UElements" does not have
 the same number of elements as "_Elements"
  	    __and_<is_nothrow_constructible<_Elements, _UElements>...>::value;
  	                                               ^
          detected during:
            instantiation of "bool std::tuple<_Elements...>::__nothrow_constructible<_UElements.
..>() [with _Elements=<const std::string &>, _UElements=<>]" at line 502 of "/opt/rh/devtoolset-
10/root/usr/include/c++/10/bits/stl_map.h"
            instantiation of "std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type &std::map<_Key,
 _Tp, _Compare, _Alloc>::operator[](const std::map<_Key, _Tp, _Compare, _Alloc>::key_type &) [wi
th _Key=std::string, _Tp=size_t={unsigned long}, _Compare=std::less<std::string>, _Alloc=std::al
locator<std::pair<const std::string, size_t={unsigned long}>>]" at line 2582 of "/projects/netpu
b/nalu/scratch_build/packages/Trilinos/commonTools/gtest/gtest/gtest-all.cc"

however, then the error showed up in Kokkos.

[  0%] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Command_Line_Parsing.cpp.o
/opt/rh/devtoolset-10/root/usr/include/c++/10/tuple(566): error: pack "_UElements" does not have the same number of elements as "_Elements"
  	    __and_<is_nothrow_constructible<_Elements, _UElements>...>::value;

What is the Intel coverage for Trilinos? Should I bump up or down?

@ajpowelsnl FYI...

SHA1:
commit 18630472ab6c8f7acbf76cf3e5e4395beaba0ae6 (HEAD -> develop, origin/develop)
Merge: 304ac3f4676 1feaba17f79
Author: trilinos-autotester <trilinos@sandia.gov>
Date:   Wed Feb 15 11:42:46 2023 -0600

**Comment by spdomin** [comment]
I attempted to build with Intel 21.3.0, however, now see an error that seems to have been reported ~five years ago:

undefined reference to `dlarnd_'

I will sit back and wait to see how to proceed.

**Comment by sebrowne** [comment]
We've been experiencing issues getting the Intel PR build back online after the C++17 transition.  I am actively trying to get it re-enabled, and at that point it will use 2021.3.0.  I hope to have it back online by next week (waiting on some other confounding issues to get resolved first).

**Comment by spdomin** [comment]
@sebrowne, sounds good. Thank you. The Intel build is important to support and is required for current work on our institutional clusters. Is there any path forward that you could suggest in the meantime?

By way of process, perhaps a question for @jwillenbring, @ccober6, and the Trilinos leadership: how did we push forward a major compiler update and let a major compiler (Intel-based) fall through the cracks? I seem to recall a strong driver to push forward with the 17-standard (and beyond).

Best,

**Comment by sebrowne** [comment]
@spdomin I can actually answer that one as well (hopefully semi-completely).  The Intel compiler build is very expensive compared to nearly all of our other PR test toolchains, particularly in the build phase.  One such expense is the high sensitivity to machine memory (the Intel compiler will frequently crash when memory on the machine gets too low), leading to a variety of spurious failures.  We have been working on multiple paths forwards to address this, by monitoring our build machine statuses with new tooling as well as potentially enabling cached builds in the PR system.  We have also been working to isolate failure-prone tests, which have shown up in some packages.  We did not want to re-enable the Intel build until it was demonstrably stable on a nightly basis and introduce instability to the PR system.

I've been mentioning this issue at the tri-weekly meetings that Trilinos Framework has with some of our internal ASC customers to provide visibility on the lack of Intel testing, as well as at the Framework sprint reviews.  We do recognize that it is important (critical) for nearly all of our internal customers on many of the HPC platforms, and the lack of testing has been fortunate not to lead to any failing tests (yet).

As is frequently the case with these types of scenarios, we had a number of requirements that were difficult to orchestrate in a satisfactory way (the C++17 requirement was needed for a new Kokkos integration, which was needed prior to releasing a new version of Trilinos, so it was pretty high priority, but we also need PR testing to be stable which the Intel compiler has caused headaches with, but we also need to support the Intel compiler due to stakeholder requirements for the institutional clusters).

Hopefully that provides at least a high-level answer.  I'll defer to any additional input from Jim or Curt.

**Comment by rppawlo** [comment]
@sebrowne - you are probably already aware of this, but just wanted to mention. There are issues with the intel classic compiler stack with Kokkos 4.0 release that are going to be hard to work around for some packages in trilinos. If you are working on a new intel build we should really switch to the new compiler chain.

**Comment by spdomin** [comment]
Thank you for the response. I will tune into the next Trilinos Developers meeting. 

_We did not want to re-enable the Intel build until it was demonstrably stable on a nightly basis and introduce instability to the PR system._

I had no idea Intel was strategically un-enabled - especially given the extensive usage of Sierra on our Intel-based clusters.

Let me know if you have any breakthroughs in the next week or so.

**Comment by spdomin** [comment]
I am trying to reconcile this conversation with others that note that teams (Sierra and SPARC) are able to build Trilinos with the lasted 2021.3.0 version:

  1) intel/21.3.0   3) openmpi-intel/4.0   5) cde/v3/anaconda3/2021.05
  2) mkl/21.3.0     4) gnu/10.2.1          6) cmake/3.20.3

However, with the config file noted below:

```
netcdf_install_dir=$nalu_install_dir/netcdf/4.7.4
hdf_install_dir=$nalu_install_dir/hdf5/1.10.6
pnetcdf_install_dir=$nalu_install_dir/pnetcdf/1.12.1

# Where trilinos will be installed
trilinos_install_dir=$nalu_install_dir/Trilinos_stable_release

echo "nalu_install_dir = \"$nalu_install_dir\""

# extra
includes="/projects/global/toss3/compilers/intel/intel_2021/oneapi/mkl/2021.3.0/include"
libdirs="/projects/global/toss3/compilers/intel/intel_2021/oneapi/mkl/2021.3.0/lib/intel64;/projects/globa
l/toss3/compilers/intel/intel_2021/oneapi/compiler/2021.3.0/linux/compiler/lib/intel64"
libnames="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5"

EXTRA_ARGS=$@

# Cleanup old cache before we configure
# Note:  This does not remove files produced by make.  Use "make clean" for this.
find . -name "CMakeFiles" -exec rm -rf {} \;
rm -f CMakeCache.txt

cmake \
-DCMAKE_INSTALL_PREFIX=$trilinos_install_dir \
-DTrilinos_ENABLE_CXX11=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG:BOOL=ON \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
  -DMPI_BASE_DIR:PATH=$mpi_base_dir \
-DTPL_ENABLE_SuperLU=OFF \
-DTPL_ENABLE_Boost:BOOL=OFF \
-DTrilinos_ENABLE_Epetra:BOOL=OFF \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=OFF \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_Stratimikos:BOOL=OFF \
-DTrilinos_ENABLE_Stokhos:BOOL=OFF \
-DTrilinos_ENABLE_Thyra:BOOL=OFF \
-DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
-DTrilinos_ENABLE_AztecOO:BOOL=OFF \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=OFF \
-DTrilinos_ENABLE_Amesos:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
-DTrilinos_ENABLE_Gtest:BOOL=OFF \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetCDF_ROOT:PATH=${netcdf_install_dir} \
-DHDF5_ROOT:PATH=${hdf_install_dir} \
-DHDF5_NO_SYSTEM_PATHS=ON \
-DPNetCDF_ROOT:PATH=${pnetcdf_install_dir} \
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
-DBLAS_INCLUDE_DIRS:PATH="${includes}" \
-DBLAS_LIBRARY_DIRS:PATH="${libdirs}" \
-DBLAS_LIBRARY_NAMES:STRING="${libnames}" \
-DLAPACK_INCLUDE_DIRS:PATH="${includes}" \
-DLAPACK_LIBRARY_DIRS:PATH="${libdirs}" \
-DLAPACK_LIBRARY_NAMES:STRING="${libnames}" \
$EXTRA_ARGS \
../
```

I am seeing the following error: 

/projects/cmake/toss3/3.20.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_12b75.dir/link.txt --verbose=1
/opt/openmpi/4.0/intel/bin/mpicxx -O3 -DNDEBUG CMakeFiles/cmTC_12b75.dir/src.cxx.o -o cmTC_12b75 
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/cmTC_12b75.dir/src.cxx.o:
 in function `main':
src.cxx:(.text+0x47): undefined reference to `A::theFunction()'
gmake[1]: *** [CMakeFiles/cmTC_12b75.dir/build.make:100: cmTC_12b75] Error 1
gmake[1]: Leaving directory '/projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_in
tel-21.3.0/CMakeFiles/CMakeTmp'

**Comment by sebrowne** [comment]
I think you may need to change BLAS_* and LAPACK_* variables near the end of your configure script to TPL_BLAS_* and TPL_LAPACK_* .  Looking at that link test, it doesn't appear to have added any of the blas/lapack stuff to the link line, so that undefined symbol makes sense.

**Comment by spdomin** [comment]
I will try that. The above was based on a SPARC config file. I'll report back.

**Comment by spdomin** [comment]
Same issue... Moreover, I know that the config file routinely specifies environment variables without the TPL_*, take for instance,

```
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetCDF_ROOT:PATH=${netcdf_install_dir} \

```

**Comment by sebrowne** [comment]
It works in some specific instances because of how those variables get propagated down to lower-level cmake script components.  In most cases, TriBITS needs the TPL_${TPLNAME}... syntax.  That TPL_X*** is what we test with in PR testing.

Can you share the link command that is failing now (the one starting with /opt/openmpi/4.0/intel/bin/mpicxx)?  Given the addition of that error, I would hope to see that something changed from before

**Comment by spdomin** [comment]
I know that I have been building on Linux for years without issue. As such, this fully feels like a "user error"... 

To be complete, I changed to use the following config options:

`
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
-DTPL_BLAS_INCLUDE_DIRS:PATH="${includes}" \
-DTPL_BLAS_LIBRARY_DIRS:PATH="${libdirs}" \
-DTPL_BLAS_LIBRARY_NAMES:STRING="${libnames}" \
-DTPL_LAPACK_INCLUDE_DIRS:PATH="${includes}" \
-DTPL_LAPACK_LIBRARY_DIRS:PATH="${libdirs}" \
-DTPL_LAPACK_LIBRARY_NAMES:STRING="${libnames}" \
`
In the past, I never set these on Intel. Perhaps I was lucky?

My modules are as follows:

Currently Loaded Modules:
  1) intel/21.3.0   3) openmpi-intel/4.0   5) cde/v3/anaconda3/2021.05
  2) mkl/21.3.0     4) gnu/10.2.1          6) cmake/3.20.3

The configure results in the following:

```
Performing C++ SOURCE FILE Test HAVE_TEUCHOS_LAPACKLARND failed with the followi
ng compile output:
Change Dir: /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_r
elease_intel-21.3.0/CMakeFiles/CMakeTmp

Run Build Command(s):/opt/rh/devtoolset-10/root/usr/bin/gmake -f Makefile cmTC_e
4349/fast && /opt/rh/devtoolset-10/root/usr/bin/gmake  -f CMakeFiles/cmTC_e4349.
dir/build.make CMakeFiles/cmTC_e4349.dir/build
gmake[1]: Entering directory '/projects/netpub/nalu/scratch_build/packages/Trili
nos/build_stable_release_intel-21.3.0/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_e4349.dir/src.cxx.o
/opt/openmpi/4.0/intel/bin/mpicxx -DHAVE_TEUCHOS_LAPACKLARND  -O3 -DNDEBUG -std=
c++17 -MD -MT CMakeFiles/cmTC_e4349.dir/src.cxx.o -MF CMakeFiles/cmTC_e4349.dir/
src.cxx.o.d -o CMakeFiles/cmTC_e4349.dir/src.cxx.o -c /projects/netpub/nalu/scra
tch_build/packages/Trilinos/build_stable_release_intel-21.3.0/CMakeFiles/CMakeTm
p/src.cxx
Linking CXX executable cmTC_e4349
/projects/cmake/toss3/3.20.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e434
9.dir/link.txt --verbose=1
/opt/openmpi/4.0/intel/bin/mpicxx -O3 -DNDEBUG CMakeFiles/cmTC_e4349.dir/src.cxx
.o -o cmTC_e4349  /usr/lib64/liblapack.so 
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles
/cmTC_e4349.dir/src.cxx.o: in function `main':
src.cxx:(.text+0x42): undefined reference to `dlarnd_'
gmake[1]: *** [CMakeFiles/cmTC_e4349.dir/build.make:101: cmTC_e4349] Error 1
gmake[1]: Leaving directory '/projects/netpub/nalu/scratch_build/packages/Trilin
os/build_stable_release_intel-21.3.0/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_e4349/fast] Error 2


...and run output:

Return value: 1
Source file was:

#define F77_BLAS_MANGLE(name,NAME) name ## _

#define DLARND_F77   F77_BLAS_MANGLE(dlarnd,DLARND)

extern "C" { double DLARND_F77(const int* idist, int* seed); }

int main()
{

  const int idist = 1;
  int seed[4] = { 0, 0, 0, 1 };

  double val = DLARND_F77(&idist, seed);

  return (val < 0.0 ? 1 : 0);

}
  
Performing C++ SOURCE FILE Test HAVE_CXX_PRAGMA_WEAK failed with the following o
utput:
Change Dir: /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_r
elease_intel-21.3.0/CMakeFiles/CMakeTmp

Run Build Command(s):/opt/rh/devtoolset-10/root/usr/bin/gmake -f Makefile cmTC_a
945a/fast && /opt/rh/devtoolset-10/root/usr/bin/gmake  -f CMakeFiles/cmTC_a945a.
dir/build.make CMakeFiles/cmTC_a945a.dir/build
gmake[1]: Entering directory '/projects/netpub/nalu/scratch_build/packages/Trili
nos/build_stable_release_intel-21.3.0/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a945a.dir/src.cxx.o
/opt/openmpi/4.0/intel/bin/mpicxx -DHAVE_CXX_PRAGMA_WEAK  -O3 -DNDEBUG -std=c++1
7 -MD -MT CMakeFiles/cmTC_a945a.dir/src.cxx.o -MF CMakeFiles/cmTC_a945a.dir/src.
cxx.o.d -o CMakeFiles/cmTC_a945a.dir/src.cxx.o -c /projects/netpub/nalu/scratch_
build/packages/Trilinos/build_stable_release_intel-21.3.0/CMakeFiles/CMakeTmp/sr
c.cxx
Linking CXX executable cmTC_a945a
/projects/cmake/toss3/3.20.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a945
a.dir/link.txt --verbose=1
/opt/openmpi/4.0/intel/bin/mpicxx -O3 -DNDEBUG CMakeFiles/cmTC_a945a.dir/src.cxx
.o -o cmTC_a945a 
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles
/cmTC_a945a.dir/src.cxx.o: in function `main':
src.cxx:(.text+0x47): undefined reference to `A::theFunction()'
gmake[1]: *** [CMakeFiles/cmTC_a945a.dir/build.make:100: cmTC_a945a] Error 1
gmake[1]: Leaving directory '/projects/netpub/nalu/scratch_build/packages/Trilin
os/build_stable_release_intel-21.3.0/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_a945a/fast] Error 2


Source file was:

#include <iostream>

namespace A {
// theFunction never gets defined, because we
// don't link with a library that defines it.
// That's OK, because it's weak linkage.
#pragma weak theFunction
extern void theFunction ();
}

int main() {
  std::cout << "Hi!  I am main." << std::endl;
  if (A::theFunction != NULL) {
    // Should never be called, since we don't link
    // with a library that defines A::theFunction.
    A::theFunction ();
  }
  return 0;
}
```

**Comment by spdomin** [comment]
Focusing on Intel 21.3.0, I was able to configure Trilinos and build. However, the final Nalu execution is failing due to:

naluX: symbol lookup error: naluX: undefined symbol: __libm_exp_table_128

I am digging into this more. If anyone has seen this error, let me know how to resolve it:)

**Comment by jhux2** [comment]
@spdomin This is a complete guess, but can you try adding `-lm` to the end of the Nalu link line?

**Comment by spdomin** [comment]
@jhux2 , thank you for the suggestion. I added the following:

-D CMAKE_EXE_LINKER_FLAGS="-lm -ldl" \

and still see this issue. I plan on resting up this weekend and tackling this on Monday.

**Comment by sebrowne** [comment]
Oddly enough, that symbol isn't in the libm that is installed on my machine (checked with `nm /usr/lib/libm.so.6 | grep exp_table_128`).  I'm a bit at a loss, but [this](https://community.intel.com/t5/Intel-Fortran-Compiler/undefined-symbol-libm-feature-flag/td-p/1076401) article made me think that maybe it's a problem with how your Intel compiler environment is initialized?  Maybe there's a newer version of libm that comes with the gcc/intel that is in-use?

**Comment by spdomin** [comment]
@sebrowne, something is off with my module selection on the Intel-based institutional cluster. I was able to build a full Intel 21.3.0 on my local CEE resource. I will keep looking into this, however, at this point, we can probably close the ticket. After all, it seems like the path forward is to push to a 21.* version of Intel. I am fine with that path. I will touch base with you via internal email as I work through the cluster Intel builds.
