### ISSUE TITLE
SEACAS build error in ATDM Trilinos debug builds starting 2020-05-07

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7331]
CC: @trilinos/seacas, @kddevin (Trilinos Data Services Product Lead), @gsjaardema 

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label "impacting: tests"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-07&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=builderrors&compare2=43&value2=0&field3=subprojects&compare3=93&value3=SEACAS) there is a build error in SEACAS in the ATDM Trilinos 'debug' builds:

* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg`
* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg_cuda-aware-mpi`
* `Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg`
* `Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg`
* `Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-debug`
* `Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug`
* `Trilinos-atdm-tlcc2-intel-debug-openmp`
* `Trilinos-atdm-waterman-cuda-9.2-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug`
* `Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug`
* `Trilinos-atdm-cts1-intel-18.0.2_openmpi-4.0.1_openmp_static_dbg`
* `Trilinos-atdm-van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_dbg`

started on testing day 2020-05-07.

These all look to be build errors of the source file `packages/seacas/applications/conjoin/Conjoin.C` showing the build error (for example [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5435434)) showing:

```
/scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug/SRC_AND_BUILD/Trilinos/packages/seacas/applications/conjoin/Conjoin.C(2915): error: identifier "glob_entity_count" is undefined
        SMART_ASSERT(global_loc < glob_entity_count);
        ^
          detected during:
            instantiation of "int <unnamed>::read_write_master_values(Excn::Variables &, const Excn::Mesh<INT> &, std::vector<U, std::allocator<U>> &, std::vector<Excn::Mesh<INT>, std::allocator<Excn::Mesh<INT>>> &, std::vector<std::vector<U, std::allocator<U>>, std::allocator<std::vector<U, std::allocator<U>>>> &, std::vector<T, std::allocator<T>> &, size_t={unsigned long}, Excn::ExodusFile &, int, int) [with T=float, U=Excn::NodeSet<int>, INT=int]" at line 924
            instantiation of "int conjoin(Excn::SystemInterface &, T, INT) [with T=float, INT=int]" at line 404

/scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug/SRC_AND_BUILD/Trilinos/packages/seacas/applications/conjoin/Conjoin.C(2869): error: identifier "glob_entity_count" is undefined
        SMART_ASSERT(global_loc < glob_entity_count);
        ^
          detected during:
            instantiation of "int <unnamed>::read_write_master_values(Excn::Variables &, const Excn::Mesh<INT> &, std::vector<U, std::allocator<U>> &, std::vector<Excn::Mesh<INT>, std::allocator<Excn::Mesh<INT>>> &, std::vector<std::vector<U, std::allocator<U>>, std::allocator<std::vector<U, std::allocator<U>>>> &, std::vector<T, std::allocator<T>> &, size_t={unsigned long}, Excn::ExodusFile &, int, int) [with T=double, U=Excn::SideSet<int>, INT=int]" at line 914
            instantiation of "int conjoin(Excn::SystemInterface &, T, INT) [with T=double, INT=int]" at line 412

/scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug/SRC_AND_BUILD/Trilinos/packages/seacas/applications/conjoin/Conjoin.C(2902): error: identifier "glob_entity_count" is undefined
        SMART_ASSERT(global_loc < glob_entity_count);
        ^
          detected during:
            instantiation of "int <unnamed>::read_write_master_values(Excn::Variables &, const Excn::Mesh<INT> &, std::vector<U, std::allocator<U>> &, std::vector<Excn::Mesh<INT>, std::allocator<Excn::Mesh<INT>>> &, std::vector<std::vector<U, std::allocator<U>>, std::allocator<std::vector<U, std::allocator<U>>>> &, std::vector<T, std::allocator<T>> &, size_t={unsigned long}, Excn::ExodusFile &, int, int) [with T=double, U=Excn::NodeSet<int>, INT=int]" at line 924
            instantiation of "int conjoin(Excn::SystemInterface &, T, INT) [with T=double, INT=int]" at line 412

compilation aborted for /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug/SRC_AND_BUILD/Trilinos/packages/seacas/applications/conjoin/Conjoin.C (code 2)
```

The new commits that were pulled on testing day 2020-05-07 as shown, for example, [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5435434#!#note1).  Looking at those commits, it seems likely this may have been caused by commits from the PR #7304.

## Current Status on CDash

* [SEACAS builds for current testing day](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=subprojects&compare2=93&value2=SEACAS).

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'sems-rhel7' (e.g. any CEE RHEL7 machine) are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
 $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
One thing a bit troubling about this is that this build error does not seem to be triggering any test failures.  This suggests that this code may not be under any automated testing.

@gsjaardema, is ATDM using the functionality associated with this build error?  If not, then we should just disable this and make this go away.  Otherwise, we really need to fix this as it is spamming the CDash site and our CDash summary emails.

**Comment by gsjaardema** [comment]
I will fix.

**Comment by gsjaardema** [comment]
Should be fixed by #7333

**Comment by bartlettroscoe** [comment]
Been fixed since testing day 2020-05-09 as shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-01&end=2020-05-14&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=subprojects&compare2=93&value2=SEACAS). 

Closing as complete.
