### ISSUE TITLE
Teuchos: Compilation errors with cuda/11.1+gcc/9.2.0 with c++17 support enabled

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#10845]
## Bug Report
@trilinos/teuchos 

### Description
Compilation of Trilinos https://github.com/trilinos/Trilinos/commit/35b4d4d70f930fee3412063a904ea659b366d824 fails in builds with cuda/11.1+gcc/9.2.0 and c++17 support enabled:
```
[  6%] Building CXX object packages/teuchos/parser/src/CMakeFiles/teuchosparser.dir/Teuchos_make_lalr1_parser.cpp.o
cd /ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/teuchos/parser/src && /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.5/bin/mpicxx -DTEUCHOSPARSER_LIB_EXPORTS_MODE -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17 -I/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/teuchos/core/src -I/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/core/src -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/kokkos/core/src -I/ascldap/users/ndellin/Trilinos-dev/packages/kokkos/core/src -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/kokkos -pedantic -Wall -Wno-long-long -Wwrite-strings -Wshadow -Woverloaded-virtual    -Xcompiler -fopenmp -expt-extended-lambda -Wext-lambda-captures-this -arch=sm_70  -O3 -DNDEBUG -std=c++17 -o CMakeFiles/teuchosparser.dir/Teuchos_make_lalr1_parser.cpp.o -c /ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp
/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp(50): error: more than one instance of overloaded function "Teuchos::size" matches the argument list:
            function template "auto std::size(const _Container &)->decltype((<expression>))"
            function template "int Teuchos::size(const std::vector<T, std::allocator<T>> &)"
            argument types are: (const Teuchos::Grammar::Productions)

/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp(52): error: more than one instance of overloaded function "Teuchos::size" matches the argument list:
            function template "auto std::size(const _Container &)->decltype((<expression>))"
            function template "int Teuchos::size(const std::vector<T, std::allocator<T>> &)"
            argument types are: (const Teuchos::Grammar::RHS)
...
```

This came up in discussion from https://github.com/kokkos/kokkos/issues/5320

I tested with sems-archive modules, so hopefully this is reproducible across any system where they are available

### Steps to Reproduce
1. SHA1: 35b4d4d70f930fee3412063a904ea659b366d824
2. Configure script: (the blas+lapack tpl overrides are specific to the system I tested on, the rest should be generic)

```bash
source /projects/sems/modulefiles/utils/sems-archive-modules-init.sh
module load sems-archive-env sems-archive-cuda/11.1 sems-archive-gcc/9.2.0 sems-archive-openmpi/4.0.5 sems-archive-cmake/3.19.1

export OMPI_CXX=$TRILINOS_DIR/packages/kokkos/bin/nvcc_wrapper

cmake \
 -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_STANDARD:STRING=17 \
 -DTPL_ENABLE_MPI=ON -DTPL_ENABLE_CUDA=ON \
 -DTPL_ENABLE_BLAS:BOOL=ON -DTPL_ENABLE_LAPACK:BOOL=ON  -DTPL_BLAS_LIBRARIES="/usr/lib64/libblas.so.3" -DTPL_LAPACK_LIBRARIES="/usr/lib64/liblapack.so.3" \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE -DTrilinos_ENABLE_OpenMP=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
  -DKokkos_ARCH_VOLTA70=ON \
  -DKokkos_ENABLE_OPENMP=ON \
  -DKokkos_ENABLE_CUDA=ON \
  -DKokkos_ENABLE_CUDA_UVM=OFF \
  -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DTrilinos_ENABLE_Amesos2=ON \
 -DTrilinos_ENABLE_Belos=ON \
 -DTrilinos_ENABLE_MueLu=ON \
  -DMueLu_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ROL=ON \
 -DTrilinos_ENABLE_Ifpack2=ON \
 -DTrilinos_ENABLE_Zoltan2=ON \
$TRILINOS_DIR
```

**Comment by bartlettroscoe** [comment]
@ibaned, from looking at:

```
$ git log-short --name-status -- packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp

a9b2842f7c3 "Teuchos:  Remove Unused Parameter Warnings"
Author: Jason M. Gates <jmgate@sandia.gov>
Date:   Fri Aug 17 08:13:28 2018 -0600 (3 years, 7 months ago)

M       packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp

50ad535b701 "TeuchosParser: refactor YAML grammar and indent"
Author: Dan Ibanez <daibane@sandia.gov>
Date:   Wed Sep 13 18:56:21 2017 -0600 (4 years, 11 months ago)

M       packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp

5078b1f99c8 "Teuchos: Document Parser"
Author: Dan Ibanez <daibane@sandia.gov>
Date:   Sun Jun 4 10:31:56 2017 -0600 (5 years ago)

M       packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp

63fd67d9a9d "Teuchos: Backport Parser to C++98"
Author: Dan Ibanez <daibane@sandia.gov>
Date:   Wed May 31 11:21:21 2017 -0600 (5 years ago)

A       packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp
```

it seems you were the author of this code.  Do you know how to fix this?

**Comment by ibaned** [comment]
@bartlettroscoe My guess would be that every call to `Teuchos::size` needs to be fully namespace qualified. Let me see how much effort it would take to do a PR. In the long term, for everyone to think about, this functionality has moved to the separate open-source package [ParseGen](github.com/sandialabs/parsegen-cpp) and its presence in Teuchos may be viewed as technical debt.
