### PR TITLE
Intrepid2: fix syntax of fold expression

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/intrepid2

## Motivation
Fix syntax of fold expression introduced in PR #14875 that triggers compilation error with some compilers.

### CODE REVIEW

**Comment by ndellingwood** [comment]
@mperego I'm curious which compilers ran into issues with this, just for reference?

**Comment by mperego** [comment]
> @mperego I'm curious which compilers ran into issues with this, just for reference?

gcc/12.2.0 with cuda/12.8.0 on blake. You have to disable Sacado to compile that piece of code.
Thanks for approving!

**Comment by ndellingwood** [comment]
> gcc/12.2.0 with cuda/12.8.0 on blake. You have to disable Sacado to compile that piece of code.

thanks for the info, I was curious because we have nightly integration testing with gcc/11.5.0 + cuda/12.6.2 and the issue doesn't occur there, maybe it is sensitive to the version of gcc? Or maybe I didn't enable something that triggers it?

**Comment by mperego** [comment]
> > gcc/12.2.0 with cuda/12.8.0 on blake. You have to disable Sacado to compile that piece of code.
> 
> thanks for the info, I was curious because we have nightly integration testing with gcc/11.5.0 + cuda/12.6.2 and the issue doesn't occur there, maybe it is sensitive to the version of gcc? Or maybe I didn't enable something that triggers it?

I'm not sure, here is the error:
```
/home/mperego/blake/trilinos-src-tmp/packages/intrepid2/src/Shared/Intrepid2_Utils.hpp(361): error: parameter pack "views" was referenced but not expanded
          (void)views, ...;
```
The Gemma team also encountered the same error, but I don't know what compiler they are using.

**Comment by ndellingwood** [comment]
Weird we haven't seen it but very helpful to know, thanks @mperego !
