### PR TITLE
zoltan2: replace use of char* code with std::string with istringstream

### PR DESCRIPTION
**Pull request by ndellingwood**
Replace the use of char* code with a std::string in the readChacoGraphHeaderInfo routine

This resolves compilation errors with cuda/12.4+gcc/13.2.0 with c++20:
```
/home/ndellin/Trilinos/packages/zoltan2/test/core/unit/input/XpetraMultiVectorInput.cpp(179): error: no operator ">>" matches these operands
            operand types are: std::basic_istream<char, std::char_traits<char>> >> char *
    issHeader >> nIDs >> nEdges >> code;
```

The `char* code` variable is not used outside of the `readChacoGraphHeaderInfo` routine, so it was removed from the function signature and the corresponding input variables were removed as well, replaced by use of `std::string s_code` variable within the routine to receive the istringstream input and for comparison (via c_str())

@trilinos/zoltan2 @egboman 

## Motivation

Change made to resolve compilation errors in builds with cuda/12.4 + gcc/13.2.0 with c++20 support enabled:

```
/home/ndellin/Trilinos/packages/zoltan2/test/core/unit/input/XpetraMultiVectorInput.cpp(179): error: no operator ">>" matches these operands
            operand types are: std::basic_istream<char, std::char_traits<char>> >> char *
    issHeader >> nIDs >> nEdges >> code;
```

## Related Issues

* Closes `put-issue-number-here`

## Testing
Local testing with sems modules:

```
export TRILINOS_DIR=<your-path>
export KOKKOS_DIR=$TRILINOS_DIR/packages/kokkos
module load sems-gcc/13.2.0 sems-cuda/12.4.0 sems-openblas/0.3.10 sems-openmpi/4.1.6 sems-cmake sems-ninja
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="20" \
 -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_CUDA=ON \
  -DTPL_ENABLE_BLAS:STRING=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:STRING=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
   -DLAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_CUSPARSE:BOOL=ON \
  -DTPL_ENABLE_CUBLAS:BOOL=ON \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_COMPLEX=ON \
 -DTrilinos_ENABLE_OpenMP=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
   -D Kokkos_ENABLE_TESTS=ON \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Ifpack2=OFF \
   -D Ifpack2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Belos=ON \
   -D Belos_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
  -DTrilinos_ENABLE_ShyLU_NodeTacho=OFF \
\
$TRILINOS_DIR
```

### CODE REVIEW

**Comment by ndellingwood** [comment]
@egboman , or maybe someone from @trilinos/xpetra , if you get a chance to review this PR passed the required CI checks

**Review by jhux2 — APPROVED** [review]
Lgtm.
