### PR TITLE
Tpetra: Fixing vortex compile issue

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: n/a
Test:n/a
Stakeholder feedback: Email

```
.../Trilinos/vortex/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp: In function 'void Tpetra::Details::Blas::fill(const ExecutionSpace&, const ViewType&, const ValueType&, IndexType, IndexType)':
.../Trilinos/vortex/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp:81:31: error: 'pair' was not declared in this scope
     auto X_j = Kokkos::subview (X, Kokkos::pair{IndexType(0), numRows}, Kokkos::pair{IndexType(0), numCols});
                               ^~~~
.../Trilinos/vortex/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp:81:31: note: suggested alternatives:
/my/path/gcc/gcc-8.3.1/rh/usr/include/c++/8/bits/stl_pair.h:208:8: note:   'std::pair'
     struct pair
```

### CODE REVIEW

**Comment by cwpearson** [comment]
Thanks! I'd love to know why this only pops up on Vortex

**Review by cwpearson — APPROVED** [review]

**Comment by cwpearson** [comment]
Introduced in https://github.com/trilinos/Trilinos/pull/12292
