### ISSUE TITLE
Tpetra: CUDA packCrs build failure

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1673]
Nightly CUDA builds of Albany using the Trilinos develop branch have spotted the following:
```
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1088): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &) [with DataType=const Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(474): here
            instantiation of "Kokkos::pair<int, size_t> Tpetra::Details::packCrsMatrixRow<ST,ColumnMap,BufferDeviceType>(const ColumnMap &, const Kokkos::View<char *, BufferDev
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(621): here
            instantiation of "void Tpetra::Details::PackCrsMatrixFunctor<LocalMatrix, LocalMap, BufferDeviceType>::operator()(Tpetra::Details::PackCrsMatrixFunctor<LocalMatrix,
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(687): here
            instantiation of "std::enable_if<std::is_same<TagType, void>::value, void>::type Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerTy
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(719): here
            instantiation of "void Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerType, Kokkos::Cuda>::run(const Kokkos::Impl::ParallelReduce<
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(697): here
            [ 4 instantiation contexts not shown ]
            instantiation of "void Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const std::__cxx11::string &, const PolicyType &, const Fun
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel_Reduce.hpp(1213): here
            instantiation of "void Kokkos::parallel_reduce(const PolicyType &, const FunctorType &, ReturnType &, Kokkos::Impl::enable_if<Kokkos::is_execution_policy<PolicyType
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(702): here
            instantiation of "void Tpetra::Details::do_pack(const LocalMatrix &, const LocalMap &, const Kokkos::View<char *, BufferDeviceType> &, const Tpetra::Details::PackTr
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(901): here
            instantiation of "void Tpetra::Details::packCrsMatrixImpl(const Tpetra::CrsMatrix<ST, LO, GO, NT, NT::classic> &, Kokkos::DualView<char *, BufferDeviceType, void, v
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(965): here
            instantiation of "void Tpetra::Details::packCrsMatrix(const Tpetra::CrsMatrix<ST, LO, GO, NT, false> &, Teuchos::Array<char> &, const Teuchos::ArrayView<size_t> &,
/home/projects/albany/build/TriBuild/packages/stokhos/src/Tpetra_Details_packCrsMatrix_MP_Vector_Cuda.cpp(54): here
```
This was initially recorded as gahansen/Albany#176.

@trilinos/tpetra

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
btw what version of CUDA is this?  I've been testing all the way through Stokhos (takes forever) with CUDA 8.0.  Does this use 7.5?

**Comment by jhux2** [comment]
It appears to be CUDA 8:  http://cdash.sandia.gov/CDash-2-3-0/buildSummary.php?buildid=58670.

**Comment by mhoemmen** [comment]
@jhux2 I'm working on it; thanks!

**Comment by tjfulle** [comment]
With the attached configuration (based on the configuration that @ibaned posted on the Albany issue), I am unable to reproduce the build error with my latest branch (#1665). I am building with the develop branch of Trilinos as we speak. I'll post the results as I get them.

[do-configure-ride.txt](https://github.com/trilinos/Trilinos/files/1273210/do-configure-ride.txt)

**Comment by mhoemmen** [comment]
Hm, my CUDA 7.5 doesn't build with Boost 1.59 (the default SEMS Boost):
```
/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.8.4/base/include/boost/geometry/algorithms/detail/relate/result.hpp(609): error: "boost::geometry::detail::relate::mask_handler<Mask, Interrupt>::mask_handler()" provides no initializer for:
            reference member "boost::geometry::detail::relate::mask_handler<Mask, Interrupt>::m_mask"

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.8.4/base/include/boost/serialization/array.hpp(57): warning: missing return statement at end of non-void function "boost::serialization::array<T>::operator="
```

**Comment by tjfulle** [comment]
I get a clean build on the develop branch with the attached configure script.  I have requested the actual configure script that is showing a failure during build.

[do-configure-ride-develop.txt](https://github.com/trilinos/Trilinos/files/1273312/do-configure-ride-develop.txt)

**Comment by tjfulle** [comment]
I was able to reproduce the error with a different configuration just now.  Looking in to this as part of #1665

**Comment by mhoemmen** [comment]
OK, I get it.  `vals_in` uses `device_type`; its memory space is `CudaUVMSpace`.  `vals_out` is a subview of `exports`, and therefore its memory space is `CudaSpace`.

I'm not sure why some compilers accepted this; it could be that Kokkos defines some kind of conversion, since `input_buffer_type` and `output_buffer_type` in `PackTraits` are both `MemoryUnmanaged`.

**Comment by tjfulle** [comment]
If that were the problem, Shouldn't `gids_in` also fail to compile?  Why does it only fail for Stokhos' Sacado UQ types?

**Comment by mhoemmen** [comment]
> If that were the problem, Shouldn't gids_in also fail to compile? Why does it only fail for Stokhos' Sacado UQ types?

Yeah, that's weird.  I still think the issue I observed is important so I'll fix it.

**Comment by tjfulle** [comment]
@mhoemmen , with the fix you suggested, the code compiles, but two stokhos tests (`Stokhos_KokkosCrsMatrixUQPCEUnitTest_Cuda_MPI_1`, `Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4`) fail with similar segfaults:

```
[ride17:30534] Signal: Segmentation fault (11)
[ride17:30534] Signal code: Address not mapped (1)
[ride17:30534] Failing at address: 0x4059aad4ad4ad4a6
[ride17:30534] [ 0] [0x100000050478]
...
```

Is it legal to create an unmanaged view from a raw pointer on one device type on another (`LocalMap::device_type` to `BufferDeviceType` in this case)?

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> but two stokhos tests ... fail ....

Those tests may have been failing before; they look pretty familiar.





> Is it legal to create an unmanaged view from a raw pointer on one device type on another (LocalMap::device_type to BufferDeviceType in this case)?

If `LocalMap::device_type::memory_space` is `Kokkos::CudaUVMSpace`, and `BufferDeviceType::memory_space` is `Kokkos::CudaSpace`, then yes, it is legal.  The key is _unmanaged_.  I was careful to use compile-time unmanaged Views (via `Kokkos::MemoryUnmanaged`) to make the point clear.

**Comment by mhoemmen** [comment]
Kokkos has some Impl namespace type traits for determining whether an execution space can access a memory space.  They are a bit weird (you have to use the execution space's memory space for the first argument, not the execution space itself) and are in the Impl namespace (therefore not technically legit for external use).

You could also do this, though it will need revision if other non-CUDA, non-host memory spaces show up that aren't host or device accessible.
```
template<class ExecSpace, class MemSpace>
struct ExecutionSpaceCanAccessMemorySpace {
  // Let either template argument be a Kokkos::Device, 
  // execution space, or memory space.
  typedef typename ExecSpace::execution_space execution_space;
  typedef typename MemSpace::memory_space memory_space;

#ifdef KOKKOS_ENABLE_CUDA
  static constexpr bool exec_space_is_cuda =
    std::is_same<execution_space, Kokkos::Cuda>::value;
  static constexpr bool mem_space_is_host_accessible =
    ! std::is_same<memory_space, Kokkos::CudaSpace>::value;
  static constexpr bool mem_space_is_cuda_accessible =
    std::is_same<memory_space, Kokkos::CudaSpace>::value ||
    std::is_same<memory_space, Kokkos::CudaUVMSpace>::value ||
    std::is_same<memory_space, Kokkos::CudaHostPinnedSpace>::value;
#else
  static constexpr bool exec_space_is_cuda = false;
  static constexpr bool mem_space_is_host_accessible = true;
  static constexpr bool mem_space_is_cuda_accessible = false; // trivially
#endif // KOKKOS_ENABLE_CUDA

  static constexpr bool value = 
    std::is_same<
      typename execution_space::memory_space,
      memory_space>::value ||
    (! exec_space_is_cuda && mem_space_is_host_accessible) ||
    (exec_space_is_cuda && mem_space_is_cuda_accessible);
};
```

**Comment by mhoemmen** [comment]
See #1697.

**Comment by tjfulle** [comment]
@mhoemmen, If those two failing Stokhos tests are okay with you, I'll forego losing another night's sleep over this!

For the pack/unpack routines, unmanaged `Kokkos::View`s are created from the input `Teuchos::ArrayView`s in `local_map::device_type`.  Should that be modified so that all of the unmanaged `Kokkos::View`s involved in the packing/unpacking procedures are created in `buffer_device_type`?

**Comment by ibaned** [comment]
The Albany dashboard in question successfully compiled this morning. This issue is resolved, for me at least.

**Comment by mhoemmen** [comment]
> For the pack/unpack routines, unmanaged `Kokkos::Views` are created from the input Teuchos::ArrayViews in local_map::device_type. Should that be modified so that all of the unmanaged `Kokkos::Views` involved in the packing/unpacking procedures are created in buffer_device_type?

Which Views specifically?  We'll need to revisit all this when we make CrsMatrix implement the "new" DistObject interface; that will completely eliminate the need for intermediate `Teuchos::ArrayView`.
