### ISSUE TITLE
RCP fails to compile with intel 17.0.1

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2128]
WHen I try to use 17.0.1 to compile trilinos I get an error with RCPNode

```

[  0%] Building CXX object packages/teuchos/core/src/CMakeFiles/teuchoscore.dir/Teuchos_RCPNode.cpp.o
cd /remote/mbetten/Trilinos/build/packages/teuchos/core/src && /projects/sems/install/rhel6-x86_64/sems/compiler/intel/17.0.1/openmpi/1.10.1/bin/mpicxx   -DTEUCHOSCORE_LIB_EXPORTS_MODE -I/remote/mbetten/Trilinos/build -I/remote/mbetten/Trilinos/build/packages/teuchos/core/src -I/remote/mbetten/Trilinos/Trilinos/packages/teuchos/core/src -I/remote/mbetten/Trilinos/build/packages/kokkos/core/src -I/remote/mbetten/Trilinos/Trilinos/packages/kokkos/core/src -I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/intel/17.0.1/base/include  -std=c++11 -qopenmp -O3 -DNDEBUG   -o CMakeFiles/teuchoscore.dir/Teuchos_RCPNode.cpp.o -c /remote/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp
/remote/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp(497): error: class "std::multimap<const void *, <unnamed>::RCPNodeInfo, std::less<const void *>, std::allocator<std::pair<const void *const, <unnamed>::RCPNodeInfo>>>" has no member "emplace_hint"
      (*rcp_node_list()).emplace_hint(
                         ^



```

@trilinos/teuchos 

## Expectations

This was working a bit ago, not sure why it would fail
## Current Behavior

fails to compile for me
## Your Environment

This is with the current develop, rhel6.9 intel 17.0.1 sems modules and all the packages enabled.

**Comment by ibaned** [comment]
That line of code was changed recently, and technically should be available in C++11. However, I know there are versions of GCC (like version 4.7.2) whose headers don't support that function. My understanding is the Intel compiler is connected to headers from the GCC compiler, so it may be that the Intel compiler you're using is pulling in headers from a version of GCC that Trilinos doesn't support. I'll run a quick test to confirm this happens for me too on a SEMS machine

**Comment by bartlettroscoe** [comment]
It came in PR #2091 at line https://github.com/trilinos/Trilinos/pull/2091/files#diff-4b14016cc207870a551134c8b8e261f3R497.

**Comment by bathmatt** [comment]
So, what is the minimum gcc that you support on trilinos?

**Comment by ibaned** [comment]
I believe its GCC 4.8.4, possibly 4.8.3.

Loading `sems-intel/17.0.1` loads gcc 4.7.2:

```
  1) sems-env            2) sems-gcc/4.7.2      3) sems-intel/17.0.1
```

**Comment by bartlettroscoe** [comment]
> So, what is the minimum gcc that you support on trilinos?

Officially, GCC 4.8.4 is the minimum version.  If you try to configure with Kokkos enabled with less thatn GCC 4.8.4, it will error out.  What version of the GCC headers is the SEMS intel 17.0.1 build pointing to?

**Comment by bartlettroscoe** [comment]
> `sems-gcc/4.7.2`

Okay, so it looks like Trilinos really should not be supporting that SEMS compiler then.  How is Kokkos getting away with this?

**Comment by bathmatt** [comment]
Well, ok, i updated to 4.9.3 and it goes past this..  you need to load the gcc prior to the icc module

**Comment by ibaned** [comment]
I think Kokkos may still accidentally compile with GCC 4.7.2 headers, GPU interoperability means we don't use much of the standard template library anyway. I think this is still accidental and not officially supported compatibility though.

Yea, I also just confirmed that swapping out the GCC module gets people past this. I think all that SEMS needs to do is change the sems-intel module to point to a newer sems-gcc module by default.
```
09:51:41:cee-compute011:~$ module list
Currently Loaded Modulefiles:
  1) sems-env            2) sems-gcc/4.7.2      3) sems-intel/17.0.1
09:51:43:cee-compute011:~$ module swap sems-gcc/4.7.2 sems-gcc/4.8.4
09:52:45:cee-compute011:~$ module list
Currently Loaded Modulefiles:
  1) sems-env            2) sems-gcc/4.8.4      3) sems-intel/17.0.1
09:52:47:cee-compute011:~$ vim foo.cpp
09:55:18:cee-compute011:~$ icpc --std=c++11 foo.cpp 
09:55:30:cee-compute011:~$ ./a.out 
09:55:32:cee-compute011:~$ module swap sems-gcc/4.8.4 sems-gcc/4.7.2
09:55:45:cee-compute011:~$ rm a.out 
09:55:47:cee-compute011:~$ icpc --std=c++11 foo.cpp 
foo.cpp(5): error: class "std::multimap<int, int, std::less<int>, std::allocator<std::pair<const int, int>>>" has no member "emplace_hint"
    bar.emplace_hint(bar.begin(), std::pair<int, int>{22, 48});
        ^

compilation aborted for foo.cpp (code 2)
```

**Comment by bartlettroscoe** [comment]
> Yea, I also just confirmed that swapping out the GCC module gets people past this. I think all that SEMS needs to do is change the sems-intel module to point to a newer sems-gcc module by default.

I created the SEMS server request:

* https://sems.sandia.gov/content/submit-service-request

to have the `sems-intel/17.0.1` module load the `sems-gcc/4.8.4` module by default instead of the `sems-gcc/4.7.2` module.

But since that will break existing builds of Intel 17.0.1 they may not rightfully want to make that change.  Does this not mean that they would have to build all of the TPLs again with GCC 4.8.4 headers?

**Comment by ibaned** [comment]
> But since that will break existing builds of Intel 17.0.1 they may not rightfully want to make that change. Does this not mean that they would have to build all of the TPLs again with GCC 4.8.4 headers?

There is a small probability it will be needed for TPLs written in C++, I don't think its needed for TPLs written in C. Either way its the right thing to do, I think its worse to deal with reports of compilation errors using the default modules indefinitely into the future than to have a few builds redone now.

**Comment by bathmatt** [comment]
Can we put in an error check for the gcc version somewhere and error out with a understandable message somewhere?  I didn't think to look at my gcc version, if it would say something like you need at least gcc 4.8.xxx  then I'd not started this thread...

**Comment by ibaned** [comment]
It is a little complicated since by default the compiler version just shows up as "Intel 17.0.1", with no indication of which GCC its using. According to [this page](https://software.intel.com/en-us/node/522750) it picks a GCC by default based on what is in the `PATH` environment variable. So we could have a complex special-case check for Intel. More generally, we could just do a "try to compile" during CMake configure using this `emplace_hint` thing as a test to check that we really have full C++11 support. That won't tell you that your gcc version is the issue though, only that something is wrong with the compiler when you configure.

**Comment by bartlettroscoe** [comment]
> More generally, we could just do a "try to compile" during CMake configure using this emplace_hint thing as a test to check that we really have full C++11 support. 

That is what I was thinking.  We already have a set of checks that are done for C++11.  We should add this and other examples as they come up.  I can add that check if there is no objection.

**Comment by bartlettroscoe** [comment]
FYI: I created the issue #2142 to drive getting the `sems-intel/17.0.1` env to work with Trilinos and get a Trilinos Nightly build set up for this.

**Comment by ibaned** [comment]
As expected, users are starting to send in complaints about this (see #2172). SEMS needs to fix this module.
