### ISSUE TITLE
EpetraExt cuda-9.2 build on white/ride broken starting 9/6/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3484]
CC: @trilinos/epetraext, @kddevin (Trilinos Data Services Product Lead), @Sbte, @mhoemmen 

## Next Action Status

Caused by PR #3381 merged by the trilinos-autotester 9/5/2018?  Next: Fix the failure?

## Description

As shown in [this CDash query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-debug-pt&field2=site&compare2=61&value2=white&field3=buildstarttime&compare3=84&value3=now), the build of EpetraExt was broken in the build `Trilinos-atdm-white-ride-cuda-9.2-debug-pt` (that we are trying to get cleaned for a possible Trilinos PR build).

The build error occurs when building `packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp`  and and shows, shown for example [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?onlydeltap&buildid=3909274):

```
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(64): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(71): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(89): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(93): error: identifier "H5T_NATIVE_INT" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(96): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(115): error: identifier "HDF5" is undefined
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp(124): error: identifier "HDF5" is undefined  7 errors detected in the compilation of "/tmp/tmpxft_0001e190_00000000-6_EpetraExt_HDF5_UnitTest.cpp1.ii".
```

Looking at the new commits pulled that day at:

* https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=3909266#!#note6

shows the the likely commits causing this are:

```
aec9db9:  EpetraExt: Add missing const to HDF5 Write method
Author: Sven Baars <s.baars@rug.nl>
Date:   Mon Sep 3 12:56:20 2018 +0200

M	packages/epetraext/src/inout/EpetraExt_HDF5.cpp
M	packages/epetraext/src/inout/EpetraExt_HDF5.h
M	packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp

fac4dbe:  EpetraExt: Recursively check for existing HDF5 groups
Author: Sven Baars <s.baars@rug.nl>
Date:   Mon Sep 3 09:55:22 2018 +0200

M	packages/epetraext/src/inout/EpetraExt_HDF5.cpp
M	packages/epetraext/src/inout/EpetraExt_HDF5.h
M	packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp

23fa92e:  EpetraExt: Add HDF5 test file
Author: Sven Baars <s.baars@rug.nl>
Date:   Tue Sep 4 10:15:18 2018 +0200

M	packages/epetraext/test/inout/CMakeLists.txt
A	packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp
```

from the PR #3381 approved by @mhoemmen and merged by the trilinos-autotester on 9/5/2018.

## Steps to Reproduce

One can reproduce this build failure on 'white' or 'ride' by cloning the Trilinos GitHub repo, checking out the 'develop' branch and then setting up a build build directory and doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvSettings.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_EpetraExt=ON \
  $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
FYI: This is not a current critical promoted "ATDM" build that directly impacts ATDM applications but this build is a possible target for a Trilinos auto PR build that would cover all current Primary Tested code so it would be good to clean this up so that we can get an CUDA build running as part of auto PR testing.

**Comment by Sbte** [comment]
As stated in the pull request:

> Also, I have no clue how to handle compiling these tests only when linked to the right version of HDF5. I would know how to do this with standard CMake, but not with the Trilinos build environment.

**Comment by bartlettroscoe** [comment]
@Sbte, what are the "right" versions of HDF5?

**Comment by Sbte** [comment]
@bartlettroscoe I'm not sure, but nothing should have changed about that from this pull request. It's just that when I first started to use HDF5 output, I had to try multiple versions of HDF5 to get everything it to work. So there must be some requirement on the HDF5 version/implementation. I suppose that is already handled somewhere in the Trilinos build.

**Comment by bartlettroscoe** [comment]
@Sbte, I think the issue is that almost no one uses the HDF5 support in EpetraExt.  It has not been maintained over the years and does not get any portability testing w.r.t. different versions of HDF5 so people just don't use it.

I guess that is what we could do for these ATDM builds of Trilinos too, just set `EpetraExt_ENABLE_HDF5=OFF` and then these errors go away.  But then that does not do much to help protect this code for customers like yourself.

**Comment by Sbte** [comment]
In that case, is there an actual proper solution to this problem, or should I just guard the whole file with `#ifdef HAVE_EPETRAEXT_HDF5`?

People I collaborate with always ask for HDF5 files by the way, so I'm not sure about nobody using it.

**Comment by bartlettroscoe** [comment]
> People I collaborate with always ask for HDF5 files by the way, so I'm not sure about nobody using it.

@Sbte, it is not that people don't use HDF5.  They do.  It is just that most of the major Trilinos customers are application codes that use tools and file formats like SEACAS/Exodus that I think use HDF5 internally.  What I mean is that I don't know of any major Trilinos customer that uses the EpertraExt/HDF5 adapters.

**Comment by bartlettroscoe** [comment]
FYI: This problem is addressed in PR #3522.

**Comment by bartlettroscoe** [comment]
The merge of PR #3522 on 9/27/2018 caused this build error go away on 9/28/2018 as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=3987357) (see `-1` subscript by the `0` build errors).  Basically that test should not be built if HDF5 support in EpetraExt is not enabled.

Closing as complete.
