### PR TITLE
Intrepid2, fix compiler bug (issue 13135)

### LINKED ISSUE #13135: Panzer, Intrepid2: Compilation errors with cuda/12.4 + gcc/13.2.0
## Bug Report
@trilinos/panzer  @trilinos/intrepid2 

### Description
When testing a Cuda build with cuda/12.4 and gcc/13.2.0 I encountered compilation errors with Panzer, though they refer to Intrepid2 files:

```
FAILED: packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/evaluators/Panzer_Dirichlet_Residual_EdgeBasis.cpp.o
...
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:580:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  580 |   OrientationTools<T>::ortCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:421:205: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortCoeffData'
  421 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortCoeffData;
      |                                                                                                                                                                                                             ^
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:584:1: error: conflicting declaration 'std::map<std::pair<__remove_cv(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), __remove_cv(int)>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  584 |   OrientationTools<T>::ortInvCoeffData;
      | ^ ~~~~~~~~~~~~~~~~~~
/home/ndellin/Trilinos/packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:422:205: note: previous declaration as 'std::map<std::pair<std::__cxx11::basic_string<char>, int>, Kokkos::View<double****, DeviceType> > Intrepid2::OrientationTools<DeviceType>::ortInvCoeffData'
  422 |     static std::map<std::pair<std::string,ordinal_type>,CoeffMatrixDataViewType> ortInvCoeffData;
```

### Steps to Reproduce
1. SHA1:  4c2c77595fa7c3c22dd609491e33d6b011692fb9
1. Configure script:  (sems modules)
```bash
export TRILINOS_DIR=<your-path>
export KOKKOS_DIR=$TRILINOS_DIR/packages/kokkos

module load sems-gcc/13.2.0 sems-cuda/12.4.0 sems-openblas/0.3.10 sems-openmpi/4.1.6 sems-cmake sems-ninja
module list
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

export TPETRA_ASSUME_GPU_AWARE_MPI=0

# Configure Trilinos
cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="17" \
 -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_CUDA=ON \
  -DTPL_ENABLE_BLAS:STRING=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:STRING=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
   -DLAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_CUSPARSE:BOOL=ON \
  -DTPL_ENABLE_CUBLAS:BOOL=ON \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_COMPLEX=ON \
 -DTrilinos_ENABLE_OpenMP=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
   -D Kokkos_ENABLE_TESTS=OFF \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Belos=ON \
   -D Belos_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Intrepid2=ON \
   -D Intrepid2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Panzer=ON \
   -D Panzer_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_MueLu=ON \
   -D MueLu_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
  -DTPL_ENABLE_Netcdf=OFF \
  -DTrilinos_ENABLE_ShyLU_NodeTacho=OFF \
  -DTrilinos_ENABLE_SEACAS=OFF \
$TRILINOS_DIR

make -j16
```

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/intrepid2

## Motivation
Fixes compilation bug in OrientationTools

## Related Issues

* Closes #13135

### CODE REVIEW

**Comment by sebrowne** [comment]
> @trilinos/framework Tests are failing with this error: `ccache: error: Failed to create directory /fgs/trilinos/ccache/cache/7/5: No such file or directory`

Tracked in https://github.com/trilinos/Trilinos/issues/13976

**Comment by jhux2** [comment]
@trilinos/framework Looks like there's a filesystem problem of some kind.

**Comment by sebrowne** [comment]
> @trilinos/framework Looks like there's a filesystem problem of some kind.

https://github.com/trilinos/Trilinos/issues/13976 tracks this, it's the filesystem we use for CI ccache storage.  It's undergoing maintenance, should be back soon.

**Comment by jhux2** [comment]
> > @trilinos/framework Looks like there's a filesystem problem of some kind.
> 
> #13976 tracks this, it's the filesystem we use for CI ccache storage. It's undergoing maintenance, should be back soon.

@sebrowne I completely missed your earlier comment, sorry about that.
