### ISSUE TITLE
Panzer: MiniEM example compilation error in Cuda build - calling host function from device function

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#11371]
## Bug Report
@trilinos/panzer 

### Description
While building Panzer with examples turned on in a Cuda build with cuda/11.2.2 and the Kokkos develop branch, compilation errors occurred in the mini-em example:

Here are warnings and error following the compile line from `make -j1 VERBOSE=1` 
```
/ascldap/users/ndellin/trilinos/Trilinos/packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp(18): warning: function "Teko::PreconditionerFactory::buildPreconditionerOperator(Teko::LinearOp &, Teko::PreconditionerState &) const" is hidden by "mini_em::FullMaxwellPreconditionerFactory::buildPreconditionerOperator" -- virtual function override intended?

/ascldap/users/ndellin/trilinos/Trilinos/packages/panzer/mini-em/src/solvers/MiniEM_HigherOrderMaxwellPreconditionerFactory.hpp(18): warning: function "Teko::PreconditionerFactory::buildPreconditionerOperator(Teko::LinearOp &, Teko::PreconditionerState &) const" is hidden by "mini_em::HigherOrderMaxwellPreconditionerFactory::buildPreconditionerOperator" -- virtual function override intended?

/ascldap/users/ndellin/trilinos/Trilinos/packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory_Augmentation.hpp(18): warning: function "Teko::PreconditionerFactory::buildPreconditionerOperator(Teko::LinearOp &, Teko::PreconditionerState &) const" is hidden by "mini_em::FullMaxwellPreconditionerFactory_Augmentation::buildPreconditionerOperator" -- virtual function override intended?

/ascldap/users/ndellin/trilinos/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp(81): error: calling a __host__ function("shards::CellTopology::~CellTopology") from a __device__ function("Kokkos::Impl::ParallelFor< ::Kokkos::Impl::ViewValueFunctor< ::Kokkos::Device< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> ,  ::shards::CellTopology, (bool)0> ,  ::Kokkos::RangePolicy< ::Kokkos::Cuda,  ::Kokkos::IndexType<long> ,     ::Kokkos::Impl::ViewValueFunctor< ::Kokkos::Device< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> ,  ::shards::CellTopology, (bool)0> ::DestroyTag > ,  ::Kokkos::Cuda> ::operator () const") is not allowed

/ascldap/users/ndellin/trilinos/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp(81): error: identifier "shards::CellTopology::~CellTopology" is undefined in device code

2 errors detected in the compilation of "/ascldap/users/ndellin/trilinos/Trilinos/packages/panzer/mini-em/example/BlockPrec/main.cpp".
make[2]: *** [packages/panzer/mini-em/example/BlockPrec/CMakeFiles/PanzerMiniEM_BlockPrec.dir/build.make:75: packages/panzer/mini-em/example/BlockPrec/CMakeFiles/PanzerMiniEM_BlockPrec.dir/main.cpp.o] Error 1
```

Possibly a missing `KOKKOS_INLINE_FUNCTION` marking is missing on a function to give the proper `__host__ __device__` annotation?

### Steps to Reproduce
SHA1:  Built with changes from PR #11370 

Aside from enabling Cuda and Panzer's examples in the build, I'm not sure if these configuration options may be relevant

```

      -D Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON \
      -D Kokkos_ARCH_VOLTA70=ON \
      -D Kokkos_ARCH_POWER9=ON \
      -D Kokkos_ENABLE_CUDA=ON \
      -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
      -D Kokkos_ENABLE_CUDA_UVM=ON \
      -D TPL_ENABLE_CUSPARSE:BOOL=OFF \
      -D Sacado_ENABLE_HIERARCHICAL_DFAD:BOOL=ON \
      -D Teuchos_ENABLE_DEBUG_RCP_NODE_TRACING=ON \
      -D Trilinos_AUTOGENERATE_TEST_RESOURCE_FILE=ON \

```

**Comment by cgcgcg** [comment]
@ndellingwood This should be fixed on develop.

**Comment by ndellingwood** [comment]
Thanks @cgcgcg !
