### ISSUE TITLE
Trilinos-atdm-tlcc2-intel-opt-openmp Failing starting March/15/2021

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8883]
There are 50+ failures similar to

packages/nox/test/epetra/NOX_Operators/CMakeFiles/NOX_NOX_Operators.dir/test.C.o: In function `main':
test.C:(.text+0x2b4): undefined reference to `Teuchos::ParameterList::sublist(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Which seems to indicate Teuchos is not matching the expectations of downstream libraries. I am thinking this may be an ETI issue but have not looked into that.

@trilinos/framework 
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
Looking at [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-02-01&end=2021-03-15&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-tlcc2-intel-opt-openmp) for this build, the errors stared on testing day 2020-03-07 but was clean on 2020-03-06.  If you look at CDash, the Trilinos git version https://github.com/trilinos/Trilinos/commit/c5f524f678b22120271e5b7f6f7e3348f3d5338f on 2020-03-06 with zero errors was the same as on 2020-03-07 when the errors started.  Therefore, this can't be due to any changes in Trilinos.  Also, we don't see this in any other Intel build on other systems.  Therefore, one must conclude that these errors must be due to a change in the env that system that occurred between when those two builds ran.

Therefore, I marked this as `ATDM: Env Issue` since this is not a Trilinos code defect.

**Comment by e10harvey** [comment]
#8862 recently changed the tlcc2 environment. Is there another gcc module we can test via `ctest-s-local-test-driver` on tlcc2?

**Comment by bartlettroscoe** [comment]
The ATDM Trilinos 'tlcc2' env needs to be switched over to use the `sparc-dev` modules on that system.

**Comment by prwolfe** [comment]
Looking at the dashboard I find
* Failure on the 6th due to unknown - all run-time failures
* Failures compiling starting on the 7th due to no module for gcc
* Failures linking starting on the 10th after merging #8862 due to "undefined reference to `Kokkos::Impl::throw_runtime_exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'" 

So my best guess is that this is not a matter of changing the module we load. If it was both the calling function and Kokkos should change together.

**Comment by prwolfe** [comment]
What does it take to get a clean build on this? I am guessing that is our issue.

**Comment by bartlettroscoe** [comment]
> What does it take to get a clean build on this? I am guessing that is our issue.

Just delete the Jenkins workspace for the project:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-tlcc2-intel-opt-openmp/

and it will reclone and create new a build dir from scratch.

**Comment by prwolfe** [comment]
> > What does it take to get a clean build on this? I am guessing that is our issue.
> 
> Just delete the Jenkins workspace for the project:
> 
> * https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-tlcc2-intel-opt-openmp/
> 
> and it will reclone and create new a build dir from scratch.

That is owned by the Jenkins user and there are no group or world permissions. Who can do this?

**Comment by prwolfe** [comment]
This has been building clean since 3/18, so the clean build seems to have sorted this out.
