### ISSUE TITLE
StkMeshIoBroker changes (?) killing Nalu builds

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#8618]
## Bug Report
@trilinos/\STK

### Description

New build error as follows: @alanw0 is STK moving headers around?

```
/usr/bin/ld: warning: libgfortran.so.3, needed by /lib/../lib64/liblapack.so, may conflict with libgfortran.so.5
libnalu.a(Realm.C.o): In function `sierra::nalu::Realm::create_mesh()':
Realm.C:(.text+0xbaa): undefined reference to `stk::io::StkMeshIoBroker::StkMeshIoBroker(ompi_communicator_t*)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(StkMeshIoBroker.cpp.o): In function `stk::io::StkMeshIoBroker::create_bulk_data()':
StkMeshIoBroker.cpp:(.text+0x695e): undefined reference to `stk::mesh::BulkData::BulkData(stk::mesh::MetaData&, int, stk::mesh::BulkData::AutomaticAuraOption, bool, stk::mesh::FieldDataManager*, unsigned int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(StkMeshIoBroker.cpp.o): In function `stk::io::StkMeshIoBroker::update_sidesets()':
StkMeshIoBroker.cpp:(.text+0x8b6b): undefined reference to `stk::parallel_machine_size(int)'
StkMeshIoBroker.cpp:(.text+0x8d30): undefined reference to `stk::all_reduce_impl(int, unsigned long const*, unsigned long*, unsigned int, int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(StkMeshIoBroker.cpp.o): In function `void stk::io::process_node_sharing<int>(Ioss::Region&, stk::mesh::BulkData&)':
StkMeshIoBroker.cpp:(.text._ZN3stk2io20process_node_sharingIiEEvRN4Ioss6RegionERNS_4mesh8BulkDataE[_ZN3stk2io20process_node_sharingIiEEvRN4Ioss6RegionERNS_4mesh8BulkDataE]+0x2d3): undefined reference to `stk::parallel_machine_rank(int)'
StkMeshIoBroker.cpp:(.text._ZN3stk2io20process_node_sharingIiEEvRN4Ioss6RegionERNS_4mesh8BulkDataE[_ZN3stk2io20process_node_sharingIiEEvRN4Ioss6RegionERNS_4mesh8BulkDataE]+0x484): undefined reference to `stk::parallel_machine_size(int)'
StkMeshIoBroker.cpp:(.text._ZN3stk2io20process_node_sharingIiEEvRN4Ioss6RegionERNS_4mesh8BulkDataE[_ZN3stk2io20process_node_sharingIiEEvRN4Ioss6RegionERNS_4mesh8BulkDataE]+0x493): undefined reference to `stk::parallel_machine_rank(int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(StkMeshIoBroker.cpp.o): In function `void stk::io::process_node_sharing<long>(Ioss::Region&, stk::mesh::BulkData&)':
StkMeshIoBroker.cpp:(.text._ZN3stk2io20process_node_sharingIlEEvRN4Ioss6RegionERNS_4mesh8BulkDataE[_ZN3stk2io20process_node_sharingIlEEvRN4Ioss6RegionERNS_4mesh8BulkDataE]+0x2d1): undefined reference to `stk::parallel_machine_rank(int)'
StkMeshIoBroker.cpp:(.text._ZN3stk2io20process_node_sharingIlEEvRN4Ioss6RegionERNS_4mesh8BulkDataE[_ZN3stk2io20process_node_sharingIlEEvRN4Ioss6RegionERNS_4mesh8BulkDataE]+0x484): undefined reference to `stk::parallel_machine_size(int)'
StkMeshIoBroker.cpp:(.text._ZN3stk2io20process_node_sharingIlEEvRN4Ioss6RegionERNS_4mesh8BulkDataE[_ZN3stk2io20process_node_sharingIlEEvRN4Ioss6RegionERNS_4mesh8BulkDataE]+0x493): undefined reference to `stk::parallel_machine_rank(int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(Heartbeat.cpp.o): In function `stk::io::impl::Heartbeat::Heartbeat(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, stk::io::HeartbeatType, Ioss::PropertyManager, int, bool)':
Heartbeat.cpp:(.text+0x62): undefined reference to `stk::parallel_machine_rank(int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(IOHelpers.cpp.o): In function `stk::io::communicate_shared_side_entity_fields(stk::mesh::BulkData const&, stk::mesh::FieldBase const*, std::vector<stk::mesh::Entity, std::allocator<stk::mesh::Entity> >&)':
IOHelpers.cpp:(.text+0xfe9): undefined reference to `stk::parallel_machine_size(int)'
IOHelpers.cpp:(.text+0xff4): undefined reference to `stk::parallel_machine_rank(int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(ProcessSetsOrBlocks.cpp.o): In function `stk::io::create_shared_edges(stk::mesh::BulkData&, stk::mesh::Part*)':
ProcessSetsOrBlocks.cpp:(.text+0x1e55): undefined reference to `stk::parallel_machine_size(int)'
ProcessSetsOrBlocks.cpp:(.text+0x1e63): undefined reference to `stk::parallel_machine_rank(int)'
/home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/Trilinos_nightly_release/lib/libstk_io.a(ProcessSetsOrBlocks.cpp.o): In function `stk::io::move_sideset_to_follow_element(stk::mesh::BulkData&, std::map<unsigned long, int, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, int> > > const&, std::vector<stk::io::ElemSidePartOrds, std::allocator<stk::io::ElemSidePartOrds> > const&)':
ProcessSetsOrBlocks.cpp:(.text+0x3a15): undefined reference to `stk::parallel_machine_size(int)'
ProcessSetsOrBlocks.cpp:(.text+0x3a20): undefined reference to `stk::parallel_machine_rank(int)'
collect2: error: ld returned 1 exit status
make[2]: *** [naluX] Error 1
make[1]: *** [CMakeFiles/naluX.dir/all] Error 2
make: *** [all] Error 2
```

### Steps to Reproduce
1. SHA1:  Trilinos/develop SHA1: 019ab01473d29346079c007edc07642ee0f41ba7

**Comment by alanw0** [comment]
Hmm, these are link errors, not finding BulkData, StkMeshIoBroker, nor stk::parallel_machine_rank (a function in stk_util/parallel. We haven't moved or changed any of these things recently. Our last stk-to-trilinos update was 11/08/2020. So right now I'm puzzled. What else can you tell me about this build? New machine? Changed environment such as mpi version or compiler version? I wonder if a build-clean and re-build would make this work.

**Comment by spdomin** [comment]
This is my standard gcc 8.3.0 nightly test - nothing new or out of the ordinary. The nightly process blasts everything in Trilinos and Nalu build directories. 

The last Nalu activity was ten days ago and we had a number of clean builds and tests during that purpose. However, that commit only deprecated SuperLU - no Nalu code change.

I am running a bisect now.

**Comment by spdomin** [comment]
This may be a false positive? @seheracer - sorry to pull you in, however, is there any chance you were changing something in Trilinos that would affect an application build?

```
8098d56e9edea90f3bf2f7bc068d6dbaf75fa3b4 is the first bad commit
commit 8098d56e9edea90f3bf2f7bc068d6dbaf75fa3b4
Author: Seher Acer <sacer@sandia.gov>
Date:   Thu Jan 14 01:48:49 2021 -0500

    Add quotient algorithm and communication graph model

:040000 040000 827b27108cc37c2069098068874165f7f45b354f 9839d909603669380750eb8b2fcdf15b7f2bfeea M	packages
```

**Comment by seheracer** [comment]
@spdomin Sorry to hear that it crashed after my PR got merged, but I do not think I changed anything that could affect a build.

@kddevin based on the discussions we had today, do you have any idea why this could be happening? 
(The files that have been changed with my PR: https://github.com/trilinos/Trilinos/pull/8576/files)

**Comment by spdomin** [comment]
I am learning more and believe that this was a false positive pointing to your commit. Sorry.

I have a circumstance now where I have a nightly Trilinos update (this clone is used for nightly testing), and a stable Trilinos update that is one week old (from 1/11/2021 - I use this for production development to shield myself from nightly Trilinos issues). Both clones are pointing to the same SHA1, however, the nightly configuration and install is failing while the previous one works fine? 

A mystery... Don't worry about this until I learn more about this odd behavior.

**Comment by spdomin** [comment]
@gdsjaar - I guess I am going to pull you in since I am totally stuck/confused.. You can see the history above. Luckily, I am at a simple problem state here... 

Specifically, I have an Installation from 1/11/2021 using: 7f5c64a6151e315d1b320f38f35c89e84b97246c
Nalu builds and links fine with the installation from 1/11/2021.

However, if I re-configure Trilinos, build, and install (using the same Trilinos config file as on 1/11/2021), I see the above link issues. What is most strange to me is if I "diff" the installation directory between then and now, I see all of these different Seacas executable size differences.

Can these possibly be related? Many thanks in advance...

**Comment by gsjaardema** [comment]
I don't think I could have made any changes that would affect this.  It looks like they are all above the SEACAS/IOSS/Exodus level...

I don't think I've snapshotted seacas into Trilinos since December, so not sure why executable sizes would change unless build or TPL changes have been introduced...

**Comment by spdomin** [comment]
I am totally stuck - tried a few number of things this past two days. I reached out to some local expertise offline... I do not think that this is a Trilinos issue, hence the closure..

**Comment by bartlettroscoe** [comment]
@spdomin,

Responding to your email about this that you just sent out here ...

I don’t think I have seen this before and looking at:

*  https://github.com/trilinos/Trilinos/issues?q=is%3Aissue+undefined+reference++StkMeshIoBroker

only shows this issue you just created :-(

Have you used ‘nm’ to look at the unsatisfied reference 'U' in the NaLU object file `UnitTestUtils.C.o`  and then searched for this in the Trilinos libraries shown on the link line for that executable looking for that 'T' defined reference in those files (or the Trilinos `*o` files for that matter)?    What does that show?

**Comment by bartlettroscoe** [comment]
FYI: On a likely unrelated issue, looking at:

* https://github.com/NaluCFD/Nalu/blob/master/build/do-configTrilinos_release

I see you are setting `-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF` and then trying to enable all of the intermediate packages you want.  For Trilinos (an many large projects using TriBITS) it is usually better (from several perspectives) to leave `Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON`, only enable the direct packages you need, and then disable the packages that you don't want.  That usually yields a shorter more-robust configure line to future changes in the Trilinos dependency structure.  (I can give some more detail on this and some examples of things that have happened in the past.)

**Comment by crtrott** [comment]
I have seen similar behavior in cases where some files were renamed or removed but somehow those older files were still there (either in the install directory or the checkout directory itself). In particular with auto generated files I have seen stuff like that. But if you say you blasted everything that feels unlikely. Another interesting question is a mismatch of compilers for certain pieces - possible a mismatch of linker and actual compiler used.

**Comment by spdomin** [comment]
Thanks for the suggestions. I will check out the detective work on the *.o files.

Yes, I blast everything before the nightly build and test. I will take another look after I fully check the full build/test process.

Thanks for the suggestion - much appreciated:)

**Comment by spdomin** [comment]
Hi. I am re-opening this... It's probably more "support" than a bug..

I have found that comparing my configuration to a teammate's config using virtually the same bashrc and ENV, I am seeing the following odd config:

```
-- Found CMake configuration file HDF5 ( directory /ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/hdf5/1.10.6 )
-- HDF5 Version: 1.10.7
-- 	HDF5_INCLUDE_DIRS      =/projects/seacas/linux/current/include
-- 	HDF5_LIBRARY_TARGETS   =hdf5_hl;hdf5
-- 	HDF5_LIBRARIES         =/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/hdf5/1.10.6/lib/libhdf5.so;/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/hdf5/1.10.6/lib/libhdf5_hl.so
-- 	HDF5_LIBRARIES_EXPORT  =/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/hdf5/1.10.6/lib/libhdf5.so;/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/hdf5/1.10.6/lib/libhdf5_hl.so
-- 	HDF5_LINK_LIBRARIES    =
-- 	HDF5_IS_PARALLEL       =NO
-- Found the following HDF5 component libraries
-- 	hdf5
-- 	hdf5_hl
-- 	HDF5 Components not found: static;shared;CXX;Fortran;CXX_HL;Fortran_HL;Java;Tools
-- 	HDF5_TOOLS_FOUND: h52gif;h5copy;h5debug;h5diff;

```

**Comment by spdomin** [comment]
Okay, these link errors originated due to older TPLs being found during the Trilinos configure step despite direct paths to these TPLS being provided. This seems to have been caused by a low-level model load.

Once I found this, all seems well now.

**Comment by alanw0** [comment]
Glad you found it, that's tough detective work. I've heard people caution against doing module load in bashrc etc., I should re-confirm that I'm not doing that also...

**Comment by spdomin** [comment]
@alanw0, this was a module environment associated with the gcc 8.3.0 and 8.4.0 environment. I have seen strange issues with loading the seacas module and then running Nalu. This was a new issue where having a sears load active affected a Nalu build and test protocol. I think that we should probably look into the seacas/nalu clash  since running these tools is routinely associated with running Nalu.
