### ISSUE TITLE
Nalu config and build errors due to updated 12/20/2019 STK snapshot

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#6521]
## Bug Report
@trilinos/stk

### Description
Widespread configuration error on all platforms on which Nalu is tested - same behavior with Nalu-Wind.

Tested SHA1:

NaluCFD/Nalu SHA1: 8bfbacb3d141584b646b800d20e3a03a7e193b73
Trilinos/develop SHA1: c858b704ab83574d26a647ff053fa782099cefdd

Config file as found under:

https://github.com/NaluCFD/Nalu/blob/master/build/do-configTrilinos_release

Bisect results based on whether or not the config step during the Nalu build protocol was successful:

naluIt$ git bisect bad
e6c2e1cf182d75b179fa32eb79a96701692a4a61 is the first bad commit
commit e6c2e1cf182d75b179fa32eb79a96701692a4a61
Author: Alan Williams <william@sandia.gov>
Date:   Thu Jan 2 14:57:52 2020 -0700

    stk snapshot as of 12/20/2019

:040000 040000 a46a1e34921e100f7f0bc74e7d5376592482306f cc2ca52fe74e89f5f347cab2f9595cbeb00bf58f M	packages

However, by chance, during a bisect, I noted a few of the below types of build errors - even after a successful config. As such, this issue may be a more nuanced in that there was something pushed that independently broke a config and a build. Luckily, there was not much germane activity yesterday besides an update of STK by @alanw0.

```
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/stk_topology/topology.hpp:38:
/Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/stk_util/stk_config.h:50:10: error: 'STK_Trilinos_config.h' file not found
      with <angled> include; use "quotes" instead
#include <STK_Trilinos_config.h>
```

Full config error is as follows:

```
   Trilinos_DIR = /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos
CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "MueLu" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "STKTransfer" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "STKSearch" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "STKIO" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "STKMesh" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "STKTopology" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Warning at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:140 (MESSAGE):
  Component "STKSimd" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Error at /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/STKUtil/STKUtilTargets.cmake:113 (message):
  The imported target "stk_util_util" references the file

     "/Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/libstk_util_util.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/STKUtil/STKUtilTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/STKUtil/STKUtilConfig.cmake:149 (INCLUDE)
  /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/lib/cmake/Trilinos/TrilinosConfig.cmake:130 (INCLUDE)
  CMakeLists.txt:21 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by alanw0** [comment]
Well, dang it. After replicating multiple cmake builds successfully, and passing the automated pre-pull-request builds/tests, everything looked good, but obviously it's not right. I'll revert ASAP, then figure out the issue before retrying. Please also post your cmake configuration command.

**Comment by bathmatt** [comment]
So, the config file isn't getting installed anymore, 

There are two auto-generated in the build process

./packages/stk/stk_util/stk_util/STK_Trilinos_config.h
./packages/stk/STK_Trilinos_config.h


and they are slightly different.  

If you install the latter it will build.  

Why are there two, why are they different?

```
(DESKTOP)-dir-gnu-opt-openmp-shared [GNU-7.2.0]$ 40 $ diff `find . -name STK_Trilinos_config.h`
42d41
< #define STK_HAVE_BOOSTLIB
```

**Comment by alanw0** [comment]
Thanks for the info @bathmatt . I was attempting to remove the first one and replace it with the second one. The difference is part of our ongoing effort to remove boost from stk. In particular, we no longer require BoostLib (but will still require some boost header-only stuff for a while longer).
My cmake skills are fairly primitive, so obviously I didn't get this right. I'll figure it out before re-pushing. This explains why my cmake builds worked, but Stefan's nalu build failed - i.e., the install step is bad, and not tested by my pre-push builds. I will try to add that to my automated test setup.

**Comment by spdomin** [comment]
No need to revert if this is a quick fix. Moreover, Monday is fine with me:)

Config for my Mac platform is below. I do not have access to my Linux set of builds..

cmake \
-DCMAKE_INSTALL_PREFIX=$trilinos_install_dir \
-DTrilinos_ENABLE_CXX11=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTpetra_INST_INT_LONG:BOOL=ON\
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
  -DMPI_BASE_DIR:PATH=$mpi_base_dir \
-DTPL_ENABLE_SuperLU=ON \
  -DSuperLU_INCLUDE_DIRS:PATH=$superlu_inc_dir \
  -DSuperLU_LIBRARY_DIRS:PATH=$superlu_lib_dir \
-DTrilinos_ENABLE_Epetra:BOOL=OFF \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=OFF \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
-DTrilinos_ENABLE_AztecOO:BOOL=OFF \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=OFF \
-DTrilinos_ENABLE_Amesos:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \
-DTPL_ENABLE_BoostLib:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetCDF_ROOT:PATH=${netcdf_install_dir} \
-DPNetCDF_ROOT:PATH=${pnetcdf_install_dir} \
-DPNetCDF_INCLUDE_DIRS:PATH="${pnetcdf_install_dir}/include" \
-DPNetCDF_LIBRARY_DIRS="${pnetcdf_install_dir}/lib" \
-DTPL_ENABLE_HDF5:BOOL=ON \
-DHDF5_ROOT:PATH=${hdf_install_dir} \
-DHDF5_NO_SYSTEM_PATHS=ON \
-DHDF5_INCLUDE_DIRS:PATH="${hdf_install_dir}/include" \
-DHDF5_LIBRARY_DIRS="${hdf_install_dir}/lib" \
-DZlib_ROOT:PATH=${z_install_dir} \
-DBoostLib_INCLUDE_DIRS:PATH="$boost_dir/include" \
-DBoostLib_LIBRARY_DIRS:PATH="$boost_dir/lib" \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
$EXTRA_ARGS \
../

**Comment by bathmatt** [comment]
We protect ourselves from Trilinos bugs with nightly acceptance testing.  This allows us to go on as there is no critical patches we need currently.  So, early next week is good for us.
Thanks Alan

**Comment by alanw0** [comment]
ok @spdomin and @bathmatt , thanks for the leniency, I'll see if I can get a fix in today or tomorrow, otherwise have a revert done before Monday.

**Comment by bathmatt** [comment]
or, enjoy your weekend, and look at it Monday as it should be pretty straight forward to fix.

**Comment by alanw0** [comment]
enjoy the weekend??? outrageous. :-) It's cold outside anyway.

**Comment by bathmatt** [comment]
Beer and football??  I know the only game that matters is tomorrow morning but ...  Just saying it isn't a rush, just wanted to get it documented but saw @spdomin beat me to it.

**Comment by alanw0** [comment]
Do you like the Saints or the Vikings? I'm taking the long shot and predicting the Seahawks will beat the Patriots in the superbowl.

**Comment by bathmatt** [comment]
Saints.  Lived in NOLA for a good while.  Used to see a lot of games when I was there.  I actually think Saints Ravens with the Saints wining their second...  but then I'm biased

**Comment by alanw0** [comment]
A fix has been pushed to the develop branch. Note that I left the BoostLib dependency in, for now. nalu-wind still uses boost::program_options and I need to make sure that dependency isn't assumed to be inherited from stk's dependency.

**Comment by spdomin** [comment]
@alanw0, okay, the good news is that the build process is working again - many thanks. The bad news is that I have two new diffs - both of which are very small (however, just as small as the last Zoltan2 issue). One test is actuatorLine while the second is oversetHybrid. Both are element-based.

Here is the tricky part... The only good and bad SHA1 that I have to bisect includes a broken build process in the middle. Therefore, at present, I do not know if your snapshot broke the test or something else during this two day time frame. Looking at the log, there does not seem to be any Trilinos commits related to what might normally break a CFD code.

Even worse is that it seems that you may have departed normal STK update procedures that I have seen in the past by pushing a snapshot that may represent a number of STK commits under Sierra-land. Is this correct? Normally, I note individual STK team member commits whereas here, it looks like a copy-paste of the new code base from Sierra.

I know that it is hard on the STK team developing while not able to test for all use-cases that use STK, e.g. Nalu, Albany, etc. Normally, the apps catch up by knowing that we can always bisect.

Let me know how to proceed. It also does not look like Nalu-Wind has yet produced clean build as per the current dash.

**Comment by bathmatt** [comment]
Our testing passed. Thanks

**Comment by alanw0** [comment]
ok, glad the config issue seems to be fixed.

Stefan, I'll work on figuring out what caused the diffs.

As far as the update procedure, it's always a snapshot from sierra, as trilinos and sierra don't share git history. Thus individual stk commits in sierra don't show up in the trilinos snapshot. It is just a copy of the current stk directory from sierra.

**Comment by spdomin** [comment]
My mistake - I must be a number of years out-of-date (as in, when STK was developed under Trilinos?). At any rate, how do you plan on finding the culprit commit?

**Comment by alanw0** [comment]
My current strategy is to confirm that those two tests also diff in nalu-wind (I'm trying to resurrect my build which seems to have gotten torpedoed by using new modules with updated mpi versions...).
If it's diffing, I'll then do a manual process of restoring separate stk subdirectories and figure it out from there. Semi painful, but shouldn't be too bad.

**Comment by spdomin** [comment]
Please do make sure that when you test on Nalu-wind, you have the proper "strict" tolerances. Last I recall, the first implementation of the actuator line approach that I am testing in Nalu was removed from Wind. However, the oversetHybrid case is exactly the same between the projects.

**Comment by alanw0** [comment]
Will do, thanks for the clarification. I'll concentrate on the oversetHybrid case.

**Comment by spdomin** [comment]
Looks like even on Linux, the tolerance set on N-W will be too low to catch this diff:

> Using test tolerance of 0.0005

**Comment by alanw0** [comment]
Thanks, I'll set the tolerance small.
I've been in and out of meetings, and my nalu-wind builds are giving me fits... but I'm actively working on it and I'll keep you posted.

**Comment by spdomin** [comment]
I have all of the scrips required if you want to work in Nalu-proper. Let me know offline.

**Comment by spdomin** [comment]
Okay, as noted, the config error was fixed a while ago. The diffs cased by this update were isolated to a STK_search::coarse_search() optimization.

Checkout out: 

> https://github.com/NaluCFD/Nalu/commit/3565cdd4e34d5d963dc639d1e9f6394bf0f44991


for more gory details.

Thanks to all... Closing..
