### ISSUE TITLE
ifpack2:  undeclared identifier with Mac CLANG

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#6910]
## Bug Report
@trilinos/ifpack2 

### Description
Compile failure with 

```
/Users/ccober/myOffice/Trilinos/packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp:68:31: error: use of undeclared identifier 'canonicalize'
  std::string precTypeUpper = canonicalize(precType);
```

### Steps to Reproduce
1. SHA1:  c4329f158d
1. Configure script:  [build_tempus_s1037643_mac_gcc.sh.txt](https://github.com/trilinos/Trilinos/files/4262763/build_tempus_s1037643_mac_gcc.sh.txt)
1. Configure log:  [build_tempus_s1037643_mac_gcc.sh.log](https://github.com/trilinos/Trilinos/files/4262777/build_tempus_s1037643_mac_gcc.sh.log)
1. Build log:  [ninja.log](https://github.com/trilinos/Trilinos/files/4262988/ninja.log)

**Comment by mhoemmen** [comment]
Weird; this got through PR testing.

**Comment by jhux2** [comment]
@cgcgcg Maybe related to your recent commits?

**Comment by cgcgcg** [comment]
Yup, that's my doing.

**Comment by cgcgcg** [comment]
@ccober6 This seems to be building fine on my system with both clang and gcc, and I can't seem to find this error on any of the automated builds. I don't have apple clang, so not quite sure how to fix this.

**Comment by mhoemmen** [comment]
@ccober6 Is `canonicalize` an instance method?  If so, could you please try sticking `this->` in front of that call?

**Comment by rppawlo** [comment]
Getting the same error on a linux gcc 9.3 build with OpenMP node type (not just a mac error). Adding "this->" did not fix it.
```
In file included from packages/ifpack2/src/Ifpack2_Details_OneLevelFactory.hpp:2,
                 from /ascldap/users/rppawlo/Trilinos/packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp:47,
                 from packages/ifpack2/src/Ifpack2_Details_Factory.hpp:2,
                 from /ascldap/users/rppawlo/Trilinos/packages/ifpack2/src/Ifpack2_Factory_decl.hpp:48,
                 from packages/ifpack2/src/Ifpack2_Factory.hpp:1,
                 from /ascldap/users/rppawlo/Trilinos/packages/ifpack2/src/Ifpack2_Details_LinearSolverFactory_def.hpp:54,
                 from packages/ifpack2/src/Ifpack2_Details_LinearSolverFactory.hpp:2,
                 from /ascldap/users/rppawlo/Trilinos/packages/ifpack2/src/Ifpack2_Details_registerLinearSolverFactory.cpp:45:
/ascldap/users/rppawlo/Trilinos/packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_def.hpp: In member function ‘Teuchos::RCP<Ifpack2::Preconditioner<typename MatrixType::scalar_type, typename MatrixType::local_ordinal_type, typename MatrixType::global_ordinal_type, typename MatrixType::node_type> > Ifpack2::Details::OneLevelFactory<MatrixType>::create(const string&, const Teuchos::RCP<const Tpetra::RowMatrix<typename MatrixType::scalar_type, typename MatrixType::local_ordinal_type, typename MatrixType::global_ordinal_type, typename MatrixType::node_type> >&) const’:
/ascldap/users/rppawlo/Trilinos/packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_def.hpp:86:31: error: there are no arguments to ‘canonicalize’ that depend on a template parameter, so a declaration of ‘canonicalize’ must be available [-fpermissive]
   86 |   std::string precTypeUpper = canonicalize(precType);
      |                               ^~~~~~~~~~~~

```

**Comment by jhux2** [comment]
@rppawlo I just tried `gcc-9.2.0`, the latest gcc available via SEMS.  Everything builds just fine for me on the CEE lan.  Can you post a minimal cmake config script?

**Comment by rppawlo** [comment]
@jhux2 - just sent you an email with my configure script. This is not a sems compiler stack.

**Comment by jhux2** [comment]
> @jhux2 - just sent you an email with my configure script. This is not a sems compiler stack.

Got it, thanks, and was able to modify it to use SEMS gcc 9.2.  I'll let you know the results.

**Comment by jhux2** [comment]
@rppawlo @ccober6 My build with the gcc 9.2 SEMS modules finishes without error.  (SEMS doesn't have gcc 9.3.)  I modified Roger's configures like so.

<details>
<summary>config script</summary>

```
#!/bin/bash

rm -Rf CMakeCache.txt CMakeFiles

ARGS=(
  -GNinja

  -D Teuchos_ENABLE_DEBUG_RCP_NODE_TRACING=OFF
  -G Ninja
  -D Trilinos_ENABLE_Fortran:BOOL=OFF
  -D PYTHON_EXECUTABLE:FILEPATH=/home/rppawlo/anaconda3/bin/python3
  -D Trilinos_ENABLE_DEBUG=OFF
  -D Trilinos_ENABLE_DEBUG_SYMBOLS:BOOL=ON
  -D Kokkos_ENABLE_DEBUG:BOOL=OFF
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
  -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=TRUE
  -D Panzer_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
  -D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF
  -D Trilinos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON
  -D Panzer_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON
  -D NOX_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON
  -D NOX_ENABLE_TESTS:BOOL=ON
  -D NOX_BUILD_PRERELEASE=ON
  -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON
  -D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF
  -D Trilinos_ENABLE_TESTS:BOOL=OFF
  -D EpetraExt_ENABLE_HDF5:BOOL=OFF
  -D Teuchos_ENABLE_FLOAT:BOOL=OFF
  -D Teuchos_ENABLE_COMPLEX:BOOL=OFF
  -D Teuchos_KOKKOS_PROFILING:BOOL=ON
  -D Kokkos_ENABLE_Profiling:BOOL=ON
  -D Teuchos_ENABLE_TESTS=ON
  -D Tpetra_INST_FLOAT:BOOL=OFF
  -D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF
  -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF
  -D Tpetra_INST_INT_INT:BOOL=OFF
  -D Xpetra_ENABLE_Epetra:BOOL=OFF
  -D MueLu_ENABLE_Epetra:BOOL=OFF
  -D Piro_ENABLE_MueLu:BOOL=OFF
  -D Trilinos_ENABLE_Intrepid:BOOL=ON
  -D Intrepid2_ENABLE_TESTS:BOOL=ON
  -D Intrepid2_ENABLE_EXAMPLES:BOOL=ON
  -D SEACASExodus_ENABLE_MPI:BOOL=OFF
  -D Trilinos_ENABLE_SEACASExodiff=ON
  -D Trilinos_ENABLE_SEACASEpu=ON
  -D Trilinos_ENABLE_SEACASNemspread=ON
  -D Trilinos_ENABLE_SEACASNemslice=ON
  -D Trilinos_ENABLE_SEACASAprepro:BOOL=ON
  -D Trilinos_ENABLE_KokkosCore:BOOL=ON
  -D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON
  -D Trilinos_ENABLE_Tempus:BOOL=ON
  -D Tempus_ENABLE_TESTS:BOOL=ON
  -D Tempus_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
  -D Piro_ENABLE_TESTS=OFF
  -D Trilinos_ENABLE_Zoltan2:BOOL=ON
  -D Trilinos_ENABLE_ROL:BOOL=OFF
  -DTrilinos_ENABLE_Xpetra=ON
  -D Trilinos_ENABLE_MueLu:BOOL=ON
  -D MueLu_ENABLE_Kokkos_Refactor:BOOL=ON
  -D Xpetra_ENABLE_Kokkos_Refactor:BOOL=ON
  -D MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=ON
  -D Xpetra_ENABLE_Experimental:BOOL=OFF
  -D Trilinos_ENABLE_Ifpack2:BOOL=ON
  -D Trilinos_ENABLE_Amesos2:BOOL=ON
  -D Amesos2_ENABLE_LAPACK:BOOL=ON
  -D Amesos2_ENABLE_KLU2:BOOL=ON
  -D Ifpack2_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF
  -D Amesos2_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF
  -D Trilinos_ENABLE_Stokhos:BOOL=OFF
  -D Trilinos_ENABLE_Pamgen:BOOL=ON
  -D Phalanx_INDEX_SIZE_TYPE:STRING="INT"
  -D Phalanx_SHOW_DEPRECATED_WARNINGS:BOOL=ON
  -D Phalanx_ENABLE_DEVICE_DAG=ON
  -D Trilinos_ENABLE_Panzer:BOOL=ON
  -D Phalanx_ENABLE_TESTS:BOOL=ON
  -D Phalanx_ENABLE_EXAMPLES:BOOL=ON
  -D Phalanx_ENABLE_DEBUG=OFF
  -D Sacado_ENABLE_HIERARCHICAL_DFAD=OFF
  -D Panzer_ENABLE_FADTYPE:STRING="Sacado::Fad::DFad<RealType>"
  -D Panzer_ENABLE_HESSIAN_SUPPORT:BOOL=OFF
  -D Panzer_ENABLE_TESTS:BOOL=ON
  -D Panzer_ENABLE_EXAMPLES:BOOL=ON
  -D Trilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON
  -D Trilinos_ENABLE_TriKota:BOOL=OFF
  -D TPL_ENABLE_MPI:BOOL=ON
  -D MPI_EXEC_POST_NUMPROCS_FLAGS="-bind-to;None"
  -D TPL_ENABLE_Boost:BOOL=ON
  -D TPL_ENABLE_BoostLib:BOOL=ON
  -D TPL_ENABLE_HDF5:BOOL=ON
  -D TPL_ENABLE_Zlib:BOOL=ON
  -D TPL_ENABLE_Netcdf:BOOL=ON
  -D Netcdf_INCLUDE_DIRS:FILEPATH="$SEMS_NETCDF_INCLUDE_PATH"
  -D Netcdf_LIBRARY_DIRS:FILEPATH="$SEMS_NETCDF_LIBRARY_PATH"
  -DTPL_ENABLE_Matio=OFF
  -DTPL_ENABLE_X11=OFF
  -D TPL_BLAS_LIBRARIES:PATH="/usr/lib64/libblas.so"
  -D TPL_LAPACK_LIBRARIES:PATH="/usr/lib64/liblapack.so"
  -D CMAKE_CXX_COMPILER:FILEPATH="mpicxx"
  -D CMAKE_C_COMPILER:FILEPATH="mpicc"
  -D CMAKE_Fortran_COMPILER:FILEPATH="mpifort"
  -D CMAKE_CXX_FLAGS:STRING="-g -Wshadow -Wall -fdiagnostics-color=always -ansi -Wno-deprecated-declarations"
  -D CMAKE_C_FLAGS:STRING="-g"
  -D CMAKE_Fortran_FLAGS:STRING="-g"
  -D CMAKE_EXE_LINKER_FLAGS:STRING="-lgfortran"
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF
  -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF
  -D CMAKE_BUILD_TYPE:STRING=RELEASE
  -D BUILD_SHARED_LIBS:BOOL=ON
  -D Trilinos_ENABLE_COVERAGE_TESTING:BOOL=OFF
  -D Trilinos_ENABLE_OpenMP:BOOL=ON
  -D Epetra_ENABLE_OpenMP:BOOL=OFF
  -D KOKKOS_ARCH:STRING="BDW"
  -D KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK=OFF

)

cmake "${ARGS[@]}" ${TRILINOS_DIR}

```

</details>

**Comment by ccober6** [comment]
I was wondering if this related to `Tempus_ENABLE_EXPLICIT_INSTANTIATION`.  In my configure script it is ON, and the below is OFF.  @rppawlo is it ON in your original script?

**Comment by ccober6** [comment]
Oh, never mind miss read the script.

**Comment by rppawlo** [comment]
So I've traced it down to this:
```
  -D Ifpack2_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF
  -D Amesos2_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF
```
My configure enabled ETI for all of trilinos but disabled it for Ifpack2 and Amesos2. Once I set the two flags above to ON (so all packages consistently use ETI), then the build works with gcc 9.3. Could be a compiler bug, except that Curt is using clang while I'm using gcc. Also curious, Curt had ETI enabled for all packages and was still seeing it.

**Comment by cgcgcg** [comment]
@rppawlo  Thanks for tracking that down, will try to reproduce that on my system.

**Comment by cgcgcg** [comment]
@ccober6 Could you pull and try building again?

**Comment by ccober6** [comment]
@cgcgcg Sorry for the delay (I have been sick and moving into a new house.), but I just pulled, compiled and ran Tempus tests successfully.  So It looks like your merge fixed it!  Thanks for the help!
