### ISSUE TITLE
Teuchos broken because of timers not if-defed out, 

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2066]
COde does not compile because timers are not if-def'ed 

THis was broken in 8ad30ad7799a5e3f6660136510246c5d80cc72a0

@cgcgcg 
```
/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Time.cpp: In member function ‘void Teuchos::Time::start(bool)’:
/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Time.cpp:125:15: error: ‘Kokkos::Profiling’ has not been declared
     ::Kokkos::Profiling::pushRegion (name_);
               ^~~~~~~~~
/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Time.cpp: In member function ‘double Teuchos::Time::stop()’:
/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Time.cpp:149:17: error: ‘Kokkos::Profiling’ has not been declared
       ::Kokkos::Profiling::popRegion ();
```

I don't have kokkos profiling on 

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by bathmatt** [comment]
@bartlettroscoe are you seeing this??

**Comment by cgcgcg** [comment]
Sorry, I'll revert it for now.

**Comment by cgcgcg** [comment]
Done.

**Comment by mhoemmen** [comment]
@cgcgcg Note that (a) Kokkos is an _optional_ dependency of Teuchos, and (b) it is possible to enable Kokkos but disable Kokkos profiling.

**Comment by cgcgcg** [comment]
Yeah, the fix is probably pretty simple, but I will be unavailable for the next couple of weeks, and I didn't want to push something now ;-)

**Comment by bathmatt** [comment]
Thanks for the quick revert...

**Comment by bartlettroscoe** [comment]
@bathmatt,

> @bartlettroscoe are you seeing this??

I did not see this until you mentioned my @bartlettroscoe.  In order to make sure that someone sees a GitHub issue, you need to mention them specifically or a team they are part of.  See "Mention Associated Teams and Developers" at:

* https://github.com/trilinos/Trilinos/wiki/New-Issue-Cheat-Sheet

**Comment by bathmatt** [comment]
Um, @bartlettroscoe I was asking if you were seeing the failure, I know that I needed to include your name in the issue :)  That is why I added your name when I asked if you were seeing the issue in the testing anywhere

**Comment by bartlettroscoe** [comment]
@bathmatt,

> I was asking if you were seeing the failure, I know that I needed to include your name in the issue :) 

Okay.  Thanks for the clarification.

This chagne did not cause a breakage in the CI build:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

so I would not have noticed this.
