### PR TITLE
ROL: Resolve __host__ function called from __host__ __device__ when building with HIPCC

### LINKED ISSUE #11401: ROL:  ROL HIP compile
Greetings,

Recently I was trying to compile with HIP using rocm 5.3 and got the following error:

/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/ROL_TpetraMultiVector.hpp:83:23: error: reference to __host__ function 'apply' in __host__ __device__ function
        X_(i,j) = f_->apply(X_(i,j));
                      ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/HIP/Kokkos_HIP_Parallel_Range.hpp:81:5: note: called by 'exec_range<void>'
    m_functor(i);
    ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/HIP/Kokkos_HIP_Parallel_Range.hpp:102:22: note: called by 'operator()'
      this->template exec_range<WorkTag>(iwork);
                     ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/HIP/Kokkos_HIP_KernelLaunch.hpp:114:11: note: called by 'hip_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<ROL::TPMultiVector::unaryFunc<double>, Kokkos::RangePolicy<Kokkos::Experimental::HIP>, Kokkos::Experimental::HIP>, 1024U, 1U>'
  driver->operator()();
          ^
/scratch/users/adiaz17/Fierro_HIP_test/Fierro/Trilinos/build/include/ROL_Elementwise_Function.hpp:59:16: note: 'apply' declared here
  virtual Real apply( const Real &x ) const = 0;

Is there a build option to get around this for ROL? I'm using the following cmake config:

export OMPI_CXX=hipcc
cmake -DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_CXX_STANDARD:STRING=17 \
-DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_OpenMP=OFF \
-DKokkos_ENABLE_HIP=ON \
-DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE=ON \
-DKokkos_ENABLE_DEPRECATED_CODE=OFF \
-DTrilinos_ENABLE_KokkosKernels=ON \
-DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
-DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
-DTrilinos_ENABLE_Amesos2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DTpetra_INST_HIP=ON \
-DXpetra_ENABLE_Kokkos_Refactor=ON \
-DMueLu_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DMueLu_ENABLE_TESTS=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF \
-DCMAKE_INSTALL_PREFIX=. \
..

Thanks for any help!

### PR DESCRIPTION
**Pull request by kpwelsh**
@trilinos/rol
@dridzal

## Motivation
When compiling with HIPCC, errors are reported that ROL ElementWise operations are attempting to invoke __host__ functions from __host__ __device__ functions. This is not allowed and the compilation does not complete.

This issue was initially brought up in and closes #11401 .

## Stakeholder Feedback
N/A

## Testing
Modifications are to ROL::ElementWise::[UnaryFunction|BinaryFunction|ReductionOp] and their derived class implementations.

The changes made to UnaryFunction, BinaryFunction, and ReductionOp are tested by elementwise.test_01.cpp.

### CODE REVIEW

**Comment by dridzal** [comment]
Hi @kpwelsh :  ROL does not depend on Kokkos, and it looks like the changes you have suggested would make it directly dependent on Kokkos.  Are there other ways to handle the HIPCC issues?  CCd @gregvw and @dpkouri --- please chime in if you have ideas.

**Comment by gregvw** [comment]
I have a solution to this that does not introduce Kokkos dependence in rol/src. It will require adding a visitor acceptor method to each of the elementwise functions, but all other new code can go into a rol/adapters/kokkos directory. I should be able to get it implemented this week if it's a priority.

**Comment by kpwelsh** [comment]
@dridzal Totally agree. I didn't notice that I was introducing a new dependency when I made that :). 

@gregvw On the timelines -- This is a priority for us. We are currently working on making cross-platform distributions of our software and compiling with HIP is one of our requirements. We would really appreciate it if this use case could be supported.

**Comment by kpwelsh** [comment]
We have taken a closer look at the potential solutions here, and noticed that while ROL has some Kokkos support through the TPetraMultiVector adapter, it doesn't have any GPU support. 

Despite ROL_TpetraMultiVector.hpp defining wrappers for binary functions, unary functions, and reductions a la the following:

```c++
KOKKOS_INLINE_FUNCTION
void operator()(const int i) const {
  const int M = X_.extent(1);
  for(int j=0;j<M;++j) {
    X_(i,j) = f_->apply(X_(i,j),Y_(i,j));
  }
}
```

This ultimately calls a `__host__` function when it calls out to whatever its wrapping. This _compiles_ on CUDA, but it doesn't work. HIP upgrades CUDA's warning to an error and fails the whole compilation (see title). I see a couple of ways forward (open to more creative solutions of course :) ).

1. This PR. Makes Kokkos a primary dependency of ROL, but will upgrade the `__host__` functions to `__host__ __device__` when necessary.
** One alternative here is to re implement KOKKOS_FUNCTION in some ROL header. We could key off of KOKKOS_ENABLE_HIP and KOKKOS_ENABLE_CUDA to insert `__host__ __device__` into the right places (see the [KOKKOS_IMPL_FUNCTION](https://github.com/search?q=repo%3Akokkos%2Fkokkos%20KOKKOS_IMPL_FUNCTION&type=code)). This introduces an optional, weak dependency on Kokkos.
2. Duplicate the Elementwise function code that we need in an adapter and use multiple dispatch to select the Kokkos version. 


Either way, I suspect that we can do the implementation. As it stands I don't see how ROL supports executing on the device, and we would like to use it on the device. So let us know what the best way forward is here.

**Comment by dridzal** [comment]
@kpwelsh : Thank you for the update.  @gregvw has a set of new features, in a private branch, which will address this.  The ROL team will meet on 04-Oct-2023 to review the new features.  Please let us know what your timeline is for deployment, so that we can consider it for merging our changes into Trilinos develop.
