### ISSUE TITLE
MueLu: Hip compilation errors with LWGraph_kokkos test, rocm/5.6.0

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#12691]
## Bug Report
@trilinos/muelu 

The `LWGraph_kokkos.cpp` fails to compile in Hip builds with rocm/5.6.0 with output:
```
22:39:48 /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/Trilinos/packages/muelu/test/unit_tests_kokkos/LWGraph_kokkos.cpp:158:25: error: reference to __host__ function 'operator->' in __host__ __device__ function
22:39:48           if (lclLWGraph->GetNodeNumVertices() != numrows)
```

This follows merge of these commits:

**Changes**:
    Xpetra: Add getLocalGraph* to EpetraCrsGraph ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    MueLu Utilities: Refactor DetectDirichletRows and ApplyRowSumCriterion ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    MueLu: Refactor LWGraphs ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    MueLu Viz test: Use test ETI ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    MueLu RefMaxwell: Fix spelling ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    MueLu: Add H2D regression test ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    Teko: clang-format ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))
    MueLu: Add H2D count specifically for aggregation ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_0_MI210/104/changes#detail))

Likely related to PR #12629 ?

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  Caraway testbed, MI210 queue
```bash
module load python rocm/5.6.0 cmake/3.25.2 mpi/openmpi-x86_64 openblas/0.3.20/rocm ninja/1.7.2
module list
export OMPI_CXX=$ROCM_PATH/bin/hipcc
export TPETRA_ASSUME_GPU_AWARE_MPI=0

cmake \
-G"Ninja" \
-DCMAKE_INSTALL_PREFIX=$PWD/install \
-DCMAKE_CXX_STANDARD="17" \
-DCMAKE_CXX_COMPILER="`which mpicxx`" \
-DCMAKE_C_COMPILER="`which mpicc`" \
-DCMAKE_FORTRAN_COMPILER="`which mpifort`" \
-DCMAKE_BUILD_TYPE="RELEASE" \
-DBUILD_SHARED_LIBS="OFF" \
\
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES=OFF \
-DTrilinos_ENABLE_OpenMP=OFF \
-DTrilinos_ENABLE_TESTS=ON \
\
-DTrilinos_ENABLE_Amesos2=ON \
 -DAmesos2_ENABLE_SuperLU=OFF \
 -DAmesos2_ENABLE_KLU2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Kokkos=ON \
 -DKokkos_ARCH_VEGA90A=ON \
 -DKokkos_ENABLE_CUDA=OFF \
 -DKokkos_ENABLE_HIP=ON \
 -DKokkos_ENABLE_OPENMP=OFF \
-DTrilinos_ENABLE_KokkosKernels=ON \
-DTrilinos_ENABLE_MueLu=ON \
 -DMueLu_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_Tpetra=ON \
 -DTpetra_ENABLE_CUDA=OFF \
 -DTpetra_INST_HIP=ON \
 -DTpetra_INST_SERIAL=OFF \
 -DTpetra_INST_OPENMP=OFF \
 -DTpetra_INST_DOUBLE=ON \
-DTrilinos_ENABLE_Gtest=ON \
-DTrilinos_ENABLE_Teuchos=ON \
-DTrilinos_ENABLE_Xpetra=ON \
 -DXpetra_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DTrilinos_ENABLE_Panzer=ON \
-DTPL_ENABLE_BLAS=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-DTPL_ENABLE_LAPACK=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
-DTPL_ENABLE_Netcdf=OFF \
-DTPL_ENABLE_MPI=ON \
-DMPI_USE_COMPILER_WRAPPERS=ON \
-DMPI_EXEC="mpirun" \
-DMPI_EXEC_NUMPROCS_FLAG="-np" \
-DMPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-bind-to;none" \
\
$TRILINOS_DIR
```

**Comment by ndellingwood** [comment]
Thanks @cgcgcg !
